### ISSUE TITLE
Allow-Cheats Pickup Issue

### ISSUE THREAD

**Issue by SuperDude36** [H4PM/Elywing#100]
When you put allow-cheats on try you can't pickup items. And without allow-cheats set to true, you can't enchant. Picking up items is more important, but I would like todo both.

**Comment by TDMidkwhatisxd** [comment]
If u allow cheats, players can hack items, are you sure?!

**Comment by SuperDude36** [comment]
allow-cheats is the only way player can enchant items.

**Comment by TDMidkwhatisxd** [comment]
And compromise your server 0-0 ! Just give them enchanted kits ;) !

**Comment by SuperDude36** [comment]
I do

**Comment by SuperDude36** [comment]
Whats the fun in that?

**Comment by TDMidkwhatisxd** [comment]
If u allow cheats, players can use old duplication methods! Or even get any item they wanna!

**Comment by SuperDude36** [comment]
Well then can you fix enchanting?

**Comment by Enzoomet** [comment]
Hey,

If you do allow cheats, it wouldn't be as much of a big deal as you can create a plugin that blocks/stops things you don't want it to do.
