### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RedstoneAlmeida** [H4PM/Elywing#105]
It's possible to add Event for example: InventoryClickEvent, InventoryMoveItemEvent........?

**Comment by oGalatico** [comment]
Red *n* para de min segui....

**Comment by Kenner-G** [comment]
Hi there,

Per policy, Elywing does not accept questions via issue tracker, please chat via PocketMine's IRC or Gitter for information. 

_I was about to lock this issue but I cannot, lol._

**Comment by MrReskill** [comment]
Hello, this is possible for others updates :) .
I lock this issues.

Reskill, members of Elywings.
