### ISSUE TITLE
Server Software Usage

### ISSUE THREAD

**Issue by MCITGAMER11** [H4PM/Elywing#106]
I want to use the Elywing Server software.Is its available in Server.pro ?

**Comment by MrReskill** [comment]
Yes, this is available :)

**Comment by MCITGAMER11** [comment]
But, In Server.pro it ia not there in the server software options.
Genisys , PocketMine and ClearSky only are there.

**Comment by MCITGAMER11** [comment]
Please check the site Server.pro

**Comment by Kenner-G** [comment]
Hi there!

Elywing is not available in that server host, you can send them an e-mail to add Elywing to their server-software area!

**Comment by MCITGAMER11** [comment]
Ok thank you for the suggestion

**Comment by MCITGAMER11** [comment]
Can I also use this with PocketMine-MP?
AND HOW TO?

**Comment by MrReskill** [comment]
Hello, 
Please recommand Elywings at your heberger.
Reskill, developper for Elywings with @Pab450 @Misteboss @SuperMaXAleX @Muqsit and [MORE]

**Comment by MCITGAMER11** [comment]
Hi!I reccommended it!
To Server.pro
BY THE WAY how can i use this server software with PocketMine - MP

**Comment by Kenner-G** [comment]
Hi there,

You cannot use a spoon of PocketMine into PocketMine. That makes no sense
whatsoever.
You need to have it as your main server-software on your server. Just wait
for a response from
*Server.pro*, let us know if you have any questions.
