### ISSUE TITLE
0.16 Windows 10 Crash

### ISSUE THREAD

**Issue by RedstoneAlmeida** [H4PM/Elywing#11]
Mu Windows 10 Edition crash on join in server, is possible fix?

**Comment by Misteboss** [comment]
@RedstoneAlmeida Can we have more informations about your crash ? (Errors on the console if there is some)

**Comment by RedstoneAlmeida** [comment]
has no mistakes, only you enter the server and the client crashes

**Comment by RedstoneAlmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/15146680/19736387/ce158b52-9b8d-11e6-9df7-132b6d9ad01d.png)

**Comment by Misteboss** [comment]
@RedstoneAlmeida do you tru without plugins ?

**Comment by Pab450** [comment]
hello, Can you try a new map ?
- stop the server
- delete "world" in folder worlds (or you can rename your world for this test)
- restart the server
- watch if the server has create a new world (name "world") in the folder "worlds"
- join the server with your mcpe client WIN10
- crash ? yes or no ? 
/@Pab45O on twitter/

**Comment by Pab450** [comment]
If you crash you can delete folder Players for reset " inventory or debug player "

**Comment by RedstoneAlmeida** [comment]
continue crashing

**Comment by Pab450** [comment]
:/ plugins in folder "plugins" ?

**Comment by RedstoneAlmeida** [comment]
plugins is removed, continue crashing :(

**Comment by Misteboss** [comment]
Can you delete all your plugin, reboot the server and try ? @RedstoneAlmeida

**Comment by Muqsit** [comment]
Plugins using $living->teleport(...) can cause crashes.

**Comment by RedstoneAlmeida** [comment]
yes, i'm delete all plugins @Misteboss , no have a plugins.

**Comment by RedstoneAlmeida** [comment]
i'm have installed my plugin, not use $living->teleport(...), continue crash @Muqsit

**Comment by MrReskill** [comment]
I use windows 10 and i dont have This problème.

**Comment by Pab450** [comment]
you have an other MCPE client (iOS, Android, windows phone) for test join server, @RedstoneAlmeida   ?

**Comment by RedstoneAlmeida** [comment]
yes, crash with to Windows 10, android not crash

**Comment by isoz** [comment]
engrish no bery gud

**Comment by RedstoneAlmeida** [comment]
sorry :p

**Comment by RedstoneAlmeida** [comment]
@MrReskill i'm crash to join in server

**Comment by Muqsit** [comment]
Rejoin after crashing. Does it show an error in the console?

**Comment by RedstoneAlmeida** [comment]
yes,continue crashing

**Comment by Muqsit** [comment]
Try the genisys branch.

**Comment by RedstoneAlmeida** [comment]
Okay

**Comment by RedstoneAlmeida** [comment]
@Muqsit is crashed by Particles Protocol, THANKS, :d

**Comment by RedstoneAlmeida** [comment]
$player->getInventory()->setItem(SLOT,...) not working

**Comment by SuperMaXAleX** [comment]
Redownload our master branch.
