### ISSUE TITLE
Enderman's Hit Box is only 2 blocks tall

### ISSUE THREAD

**Issue by SuperDude36** [H4PM/Elywing#110]
As you can see in the picture below enderman don't take fire damage. When I punch them, they do. Please fix this because auto enderman farms are not possible if they don't take fire damage. This is because the hit box is two blocks tall. When I punch them, it raises them up.
![img_1241](https://cloud.githubusercontent.com/assets/16578682/20823602/98a05cc4-b80a-11e6-9a93-e0e25f4a77ed.PNG)

**Comment by daniktheboss** [comment]
Might be wrong but this is mcpe bug not server

**Comment by SuperDude36** [comment]
I'll test it on normal world

**Comment by SuperDude36** [comment]
This is a server glitch

**Comment by SuperMaXAleX** [comment]
We can't do nothing. Sorry.
