### ISSUE TITLE
Blocked Players IP

### ISSUE THREAD

**Issue by Frago9876543210** [H4PM/Elywing#116]
On players join their ip blocked:
12:17:37 | RakLibServer thread:NOTICE > Blocked 92.243.166.170 for 5 seconds

**Comment by Kenner-G** [comment]
Hi there!

I am very familiar with this issue, can you please list the plugins you're using?

**Comment by Frago9876543210** [comment]
Плагины (26): EconomyJob v2.0.4, ToyBox v1.2.1, PurePerms v1.2.2, iProtector v3.1a, DevTools v1.1-iTX, WorldGuardian v1.6.1, ClearLagg v1.1.0, Universe v1.0.0, EconomyAPI v2.0.8, Kits v1.0.0, xyz v1.0.1, EconomySell v2.0.6, EconomyShop v2.0.6, MCG76_WorldEdit v0.5.2, static v1, AntiSpam v1.1.1, jail v1, clans v1, call v1, VC_API v1, BossBarAPI v2.0.0, MoreParticle2 v2, Auth v1, deluxe v1, sign v1, PureChat v1.3.3
