### ISSUE TITLE
Client crashes on join

### ISSUE THREAD

**Issue by PragaKart67z** [H4PM/Elywing#123]
Hi, I have been experiencing this issue for awhile now. When any player joins, their MCPE client crashes and closes the app. This happens to most people, but some are still able to join the server.

Recreate this issue:
Try joining any version of ElyWing 1.0.0, and you will crash

**Comment by SuperMaXAleX** [comment]
I'm going to update the README.md. There is a big change on MC:PE 1.0 and it is affecting many servers.

**Comment by Driesboy** [comment]
it dont crash for me

**Comment by xEnzo31** [comment]
Did your level format still mcregion ? @PragaKart67z

**Comment by PragaKart67z** [comment]
Yes

**Comment by PragaKart67z** [comment]
I think

**Comment by Driesboy** [comment]
yes that can 
anvil is supported

**Comment by PragaKart67z** [comment]
Is there an MCR to Anvil world converter?

**Comment by Driesboy** [comment]
yes

**Comment by Driesboy** [comment]
https://github.com/ImagicalCorp/MConverterUltimate/tree/master/MCRegion%20to%20Anvil

**Comment by SuperDude36** [comment]
@PragaKart67z Do you have slapper loaded? Slapper makes it crash. I no longer use Slapper.

**Comment by PragaKart67z** [comment]
How do I update my PHP version for ElyWing? I can't figure out how to do it. I want to install 7.0.14

**Comment by SuperDude36** [comment]
No idea

**Comment by Driesboy** [comment]
update the bin

**Comment by DeathRaven359** [comment]
Hold on... I'm still having this issue, so how do I fix it?

**Comment by SuperDude36** [comment]
Do you have slapper loaded? Slapper makes it crash. I no longer use Slapper.

**Comment by alexbgameson** [comment]
My worlds are in anvil format but clients still crash. I have updated the slapper plugin.
