### ISSUE TITLE
Players Dont Take Damage

### ISSUE THREAD

**Issue by JunkDaCoder** [H4PM/Elywing#124]
Players dont take damage

**Comment by YaBoiBalAnce** [comment]
Yes i get this too

**Comment by Misteboss** [comment]
Check the difficulty @YaBoiBalAnce

**Comment by SuperMaXAleX** [comment]
Maybe difficulty ya

**Comment by Driesboy** [comment]
ja dificulty its working for me

**Comment by NycuRO** [comment]
@Driesboy For me not work.
