### ISSUE TITLE
Planning on implementing a transfer function?

### ISSUE THREAD

**Issue by remotevase** [H4PM/Elywing#125]
Title says it all. Transfer between servers?

**Comment by austina1212** [comment]
How to even download the plugin? Can you make me a link, please.

**Comment by remotevase** [comment]
There is no plugin

**Comment by austina1212** [comment]
How to download the server version, I mean... You able to give me the phar...

**Comment by remotevase** [comment]
You don't need a phar! Just use the src! Click here, then add the bin, then u done!

**Comment by SuperMaXAleX** [comment]
Sure ! Soon.

**Comment by thebigsmileXD** [comment]
SynapsePM is back, several persons updated it also. Servers don't have to add transfer options anymore.

**Comment by remotevase** [comment]
Yup, not needed
