### ISSUE TITLE
Chunks are glitching.

### ISSUE THREAD

**Issue by Driesboy** [H4PM/Elywing#127]
Chunks are glitching when we are teleporting to an another world.

**Comment by Driesboy** [comment]
![img_2903](https://cloud.githubusercontent.com/assets/15795262/21378921/61ce853c-c74a-11e6-94df-54191b032b7f.PNG)

**Comment by SuperMaXAleX** [comment]
This isn't a very big problem. I have this 'issue' too but this part of chunk is going removed if you teleporting to a world and reteleporting to your world.

**Comment by Driesboy** [comment]
k but its best we fix this

**Comment by SuperMaXAleX** [comment]
How ? This bug is very annoying.

**Comment by KillerXtream** [comment]
This is stressing and needs to be fixed ASAP

**Comment by thebigsmileXD** [comment]
I confirm. Seems like above 128 height

**Comment by SuperMaXAleX** [comment]
I don't know who to fix it. It's very annoying for me and for users and I know that.

**Comment by Driesboy** [comment]
https://github.com/pmmp/PocketMine-MP/commit/40d1394e3c533e1bcf718fb8ca6faa5ad9c80c38

**Comment by Driesboy** [comment]
do this fix that?

**Comment by SuperMaXAleX** [comment]
maybe, I'll test

**Comment by thebigsmileXD** [comment]
Recheck if fixed.
