### ISSUE TITLE
Elywing sur HostMyServers

### ISSUE THREAD

**Issue by GamingPilot2** [H4PM/Elywing#13]
Bonjour, Bonsoir,

J'ai eu une idée, reste à voir si elle est réalisable;
Demander à @HostMyServers de mettre votre software dans leurs onglets Mise à Jours !

Est-ce possible ?

Merci d'avance,
GamingPilot2.

> Owner of @LifeCubePE_ & CM of @LifeCubePE_

**Comment by ItsXirano** [comment]
Lidée a dejadu été "Inventée" Il faut voir avec HMS 👍

**Comment by GamingPilot2** [comment]
MAIS VOUS FERMEZ TOUT TOUT LE TEMPS VOUS PRENEZ MEME PAS LA PEINE DE REPONDRE

**Comment by MrReskill** [comment]
Xirano (quelqu'un qui nous aide) vous a clairement répondu que c'est en cours.

**Comment by GamingPilot2** [comment]
Ah, je ne savais pas qu'il faisait parti de votre groupe! Je suis desolé
