### ISSUE TITLE
Map is weird

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [H4PM/Elywing#131]
my map is like this, and if i move a long way , my game crash! Same is to all ppl!
![screenshot_2016-12-21-16-35-20](https://cloud.githubusercontent.com/assets/18122629/21393206/1dd6789c-c79c-11e6-9b85-1c5c6761436b.png)

**Comment by oxxydev** [comment]
wow!

**Comment by Muqsit** [comment]
Delete your pocketmine.yml and genisys.yml (or change those file's names), then start the server.

**Comment by TDMidkwhatisxd** [comment]
Didnt fix my plots map! + the sky is filled with unknown blocks!

This is the corruption that @dktapps warned us? Omg

**Comment by TDMidkwhatisxd** [comment]
Ok! I did all u told me! The map is same! The thing is, maps works fine, just this dont work!
I put a 0.15 Elywing phar, and the map was ok!
Is 1.0 glich!

**Comment by TDMidkwhatisxd** [comment]
I checked and i know why! Mcr maps dont load corectly!

**Comment by Driesboy** [comment]
and if you use a 0.16.2 build from Elywings working?

**Comment by TDMidkwhatisxd** [comment]
Idk i used 0.16.1

**Comment by Infernus102** [comment]
@Muqsit  Didn't work
