### ISSUE TITLE
mcr maps dont load corectly

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [H4PM/Elywing#136]

**Comment by PragaKart67z** [comment]
MCRegion worlds are designed for  Y height to be 128, but since 1.0.0, worlds are now Y 256.  Change MCRegion settings in the pocketmine.yml to "Anvil", which is the currently supported byY  256 worlds.

**Comment by Infernus102** [comment]
will it change the world or something?

**Comment by Driesboy** [comment]
no but there are some chunk glitches

**Comment by SuperMaXAleX** [comment]
We are going to propose today a application who is converting your world to the new supporting format : Anvil.

**Comment by TDMidkwhatisxd** [comment]
I really need that!
