### ISSUE TITLE
Sign tile doesn't spawn when placing a sign.

### ISSUE THREAD

**Issue by YaBoiBalAnce** [H4PM/Elywing#14]
signs dont show up for other players. Rejoining also makes them disapear

**Comment by YaBoiBalAnce** [comment]
well not actually disapear forsay but the text goes blank

**Comment by Misteboss** [comment]
@YaBoiBalAnce Ok we are going to see

**Comment by JackNoordhuis** [comment]
Remove the server side line length checking (PM is a control freak)

**Comment by SuperMaXAleX** [comment]
Re-download our master branch !
