### ISSUE TITLE
Starting up error

### ISSUE THREAD

**Issue by haniokasai** [H4PM/Elywing#141]
in this commit,
https://github.com/H4PM/Elywing/commit/cc19ac5d4f8f3835597ea8bf194f30b4f9668fce

code was changed "$meta = 0" into "int $meta = 0",it makes an error.

09:00:04 | Elywing thread:CRITICAL > TypeError: "Argument 2 passed to pocketmine\item\Item::__construct() must be of the type integer, null given, called in /var/lib/jenkins/workspace/Elywing/src/pocketmine/item/ItemBlock.php on line 32" (EXCEPTION) in "/src/pocketmine/item/Item" at line 393

/*/*/*/
i made jenkins repo.
http://jenkins.haniokasai.com/job/Elywing/1/console

**Comment by SuperMaXAleX** [comment]
@Muqsit

**Comment by thebigsmileXD** [comment]
@Muqsit omg that fix hurts. -1 is invalid as fuck. null is the correct wayto go
