### ISSUE TITLE
Can you give us the choice to enable 128 or 256 world height ? It makes our server too much laggy

### ISSUE THREAD

**Issue by Misteboss** [H4PM/Elywing#144]
### Issue description
**_Suggestion_**
I think (if it's possible) you should add an option like "world.height : 128 or 256" so we will be able to add no load issues
@Muqsit

**Comment by SuperMaXAleX** [comment]
Impossible.

**Comment by SuperMaXAleX** [comment]
Its coming from MC:PE so we can't do nothing.

**Comment by Misteboss** [comment]
@SuperMaXAleX ça vient pas de mcpe il a dit autre chose dylan

**Comment by SuperMaXAleX** [comment]
Bah bien sûr que si lol

**Comment by Muqsit** [comment]
blocks above 128 don't save anyways..
