### ISSUE TITLE
Server is full screen dont work

### ISSUE THREAD

**Issue by TheBluePinguin1** [H4PM/Elywing#145]
If i change the message in the lang or with plugin it shows this

**Comment by TheBluePinguin1** [comment]
![1482430478695555292120](https://cloud.githubusercontent.com/assets/23699326/21435600/f6476554-c87a-11e6-9a7b-82a9c1f124d0.jpg) or sometimes cannot connect to the world

**Comment by SuperMaXAleX** [comment]
Very very strange. What did you change exactly ?

**Comment by TheBluePinguin1** [comment]
The eng.ini and i use cunstom alert

Op 24-dec.-2016 07:56 schreef "SuperMaXAleX" <notifications@github.com>:

**Comment by SuperMaXAleX** [comment]
Don't change eng.ini, it's going to break some things.

**Comment by Driesboy** [comment]
it dont work ! the only way to fix it is change the code
