### ISSUE TITLE
World Hight

### ISSUE THREAD

**Issue by SuperDude36** [H4PM/Elywing#147]
When I make something over 128 blocks and leave the chunk and come back, it's gone. My 3 hour faction base that's 0-256 keeps getting cut off...

**Comment by FunnyBuddys** [comment]
You should build your base under y:128. Drink tea and wait :)

**Comment by Driesboy** [comment]
our the plugin noTower

**Comment by SuperDude36** [comment]
ok, thx

**Comment by SuperMaXAleX** [comment]
Players can't actually higher than 128.
We are working on it.
