### ISSUE TITLE
World Loading Issue

### ISSUE THREAD

**Issue by Dblcut3** [H4PM/Elywing#148]
Whenever I go to load or TP to a world, the game crashes. When looking at the console, this is the error message:

22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level hubworkingzh because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level hubworkingzh because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level hubworkingzh because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level hubworkingzh because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level hubworkingzh because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level hubworkingzh because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level decemberplots because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level decemberplots because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level decemberplots because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level decemberplots because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level kitpvp because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level kingparkour because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level kitpvp because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level kitpvp because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level kitpvp because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level kitpvp because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level kitpvp because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level kitpvp because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level kitpvp because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level kitpvp because that level is not loaded.
22.12 22:25:08 [Server] | Elywing thread:WARNING  Could not load block in level hubworkingzHI because that level is not loaded.

**Comment by TDMidkwhatisxd** [comment]
Mcr regions wont work!

**Comment by MrReskill** [comment]
Hello, MC:PE had got an new update (0.11) and dosen't support MCR format, please use MCA (PC Format) 👍
