### ISSUE TITLE
PvP does not work

### ISSUE THREAD

**Issue by TheAppleGamer** [H4PM/Elywing#15]
Even with pvp on in server.properties and have the difficulty above 0 pvp does not work!

**Comment by Misteboss** [comment]
@TheAppleGamer Do you test without plugins ? Cause actually with the last version the PvP work

**Comment by TheAppleGamer** [comment]
I tried just plain vanilla on the server

**Comment by SuperMaXAleX** [comment]
I know where the bug is coming. The PvP is so hard to fix .-.

**Comment by SuperMaXAleX** [comment]
And what branch did you used ? "genisys" or "master" ?

**Comment by Misteboss** [comment]
@TheAppleGamer UP

**Comment by Muqsit** [comment]
Fixed in genisys branch.

**Comment by SuperMaXAleX** [comment]
Fixed.
