### ISSUE TITLE
I apologize in advance for this "issue," but can anyone link me to the latest .phar file of this?

### ISSUE THREAD

**Issue by DeathRaven359** [H4PM/Elywing#151]
Thanks.

**Comment by erkam2002** [comment]
http://jenkins.haniokasai.com/job/Elywing/
It's not the newest... but it works

**Comment by DeathRaven359** [comment]
Weird. It crashes when I join, with and without any plugins on it. Is this the same issue someone else reported earlier?

**Comment by SuperMaXAleX** [comment]
We are going to give a DevTools for Elywing.
