### ISSUE TITLE
Worlds

### ISSUE THREAD

**Issue by Infernus102** [H4PM/Elywing#152]
Idk what happened but i updated to elywings latest version and it messed up two of my worlds.
![screenshot_20161224-015359](https://cloud.githubusercontent.com/assets/22660649/21461952/bb83ae2a-c97c-11e6-845a-46c794eedc76.png)

**Comment by Infernus102** [comment]
Both had this same thing

**Comment by DeathRaven359** [comment]
I had this same issue too. Thank god for backups.

**Comment by DeathRaven359** [comment]
I believe it may be an issue with the MCregion. 

Speaking of that, does anyone have a link to the MCreigon to Anvil converter?

**Comment by Infernus102** [comment]
what do i do then? i used backup, its still making it like that

**Comment by Infernus102** [comment]
I tried deleting genisys.yml and pocketmine.yml, didn't work @Muqsit . what do i do?

**Comment by Infernus102** [comment]
Works perfectly when elywing 0.16 is used. Didn't even need to use backup. and yes i changed the format to anvil @Muqsit @SuperMaXAleX

**Comment by SuperMaXAleX** [comment]
We have it ! I'm wringing it actually...

**Comment by Infernus102** [comment]
You aren't  supposed to close the issue if it ain't fixed...............

**Comment by Infernus102** [comment]
It makes people believe that you have solved this issue!!!

**Comment by SuperMaXAleX** [comment]
The thing I'm writing is going to fix it. I'm going to reopen it if it isn't

**Comment by Infernus102** [comment]
how much time @SuperMaXAleX ?????
