### ISSUE TITLE
May i oin the proect?

### ISSUE THREAD

**Issue by thebigsmileXD** [H4PM/Elywing#153]
sry, that one key is broken :(

I am a dev of ClearSky. We kind of gave up ClearSky.

Elywing seems to be a stable running core, without messing up plugins in 1.0 etc.

**Comment by Landy005** [comment]
I'd be very smart to accept him :) !

**Comment by SuperMaXAleX** [comment]
:D !

**Comment by thebigsmileXD** [comment]
Lol was that a yes or a no

**Comment by SuperMaXAleX** [comment]
I'm talking

**Comment by SuperMaXAleX** [comment]
I just closed for other members don't be confused. You are going to have a reponse in some hours :)

**Comment by SuperMaXAleX** [comment]
Do you Twitter ?

**Comment by thebigsmileXD** [comment]
I do, but during christmas i am quite inactive there, because i don't have my windows pc here.

**Comment by erkam2002** [comment]
I have twitter xD
