### ISSUE TITLE
crafting is not working

### ISSUE THREAD

**Issue by shecter** [H4PM/Elywing#154]
Hi -- Hope you can help me. When we try crafting in survival or creative, we briefly see the newly craftable items, but then they disappear. and the think i was trying to craft, (e.g. Planks into Sticks) are not added to my inventory. Here's a video showing you what i mean. https://goo.gl/photos/gjC5kLr9SEXYBaKE6

I'm running:

23.12 16:04:19 [Server] | Elywing thread:INFO  Target client: Minecraft PE v1.0.0 alpha (protocol version 100)
23.12 16:04:19 [Server] | Elywing thread:INFO  API: 3.0.0-ALPHA1 (iTX API version 1.9.3)
23.12 16:04:19 [Server] | Elywing thread:INFO  PHP version: 7.0.10
23.12 16:04:19 [Server] | Elywing thread:INFO  This server is running Elywing-1.0 (codename "Birpen")

**Comment by SuperDude36** [comment]
This is confirmed

**Comment by SuperMaXAleX** [comment]
Confirmed too. I need to replace 'null' to '-1'.
Thanks Mojang.

**Comment by TDMidkwhatisxd** [comment]
Did u fix it?

**Comment by shecter** [comment]
a little more detail on the bug. it looks like if we go to crafting and press the crafting button slowly, we can press it all day with no new block added to the inventory. but if we press the craft button very quickly, it will add the newly crafted blocks to the inventory. but, of course, this is a waste of resources because you don't know how many newly crafted blocks you are going to get when clicking very fast.

**Comment by Pab450** [comment]
yes @shecter !

**Comment by shecter** [comment]
@Pab450, what is your "yes" referring to?

**Comment by shecter** [comment]
Virtual Gladiators just uploaded the version of Elywing below, but this issue is not fixed. I can't tell from the thread above if this has been fixed or not. 

Elywing thread:INFO  Target client: Minecraft PE v1.0.0 alpha (protocol version 100)
Elywing thread:INFO  API: 3.0.0-ALPHA1 (iTX API version 1.9.3)
Elywing thread:INFO  PHP version: 7.0.10
Elywing thread:INFO  This server is running Elywing-1.0 (codename "Birpen #1330f4e-20161227")

**Comment by SuperMaXAleX** [comment]
I just closed it because there is an another issue with the same reporting.

**Comment by shecter** [comment]
got it. thanks @SuperMaXAleX 

here's the link to the other ticket: https://github.com/H4PM/Elywing/issues/160
