### ISSUE TITLE
Level bug

### ISSUE THREAD

**Issue by gigantessbeta** [H4PM/Elywing#155]
When loading the flat world,
The terrain becomes strange

**Comment by thebigsmileXD** [comment]
I confirm

**Comment by thebigsmileXD** [comment]
Duplicate of #152

**Comment by SuperMaXAleX** [comment]
I have this issue to. Maybe it's coming from MCRegion.

**Comment by thebigsmileXD** [comment]
This should be solved when i pr the changes over.
