### ISSUE TITLE
Worlds are corrupted

### ISSUE THREAD

**Issue by Infernus102** [H4PM/Elywing#156]
![bb83ae2a-c97c-11e6-845a-46c794eedc76](https://cloud.githubusercontent.com/assets/22660649/21465779/e76ecd76-c9d6-11e6-8df5-2d1732cf1652.png)
Worlds getting corrupted when loaded in elywing v1.0, this should stay open until it's fixed.

**Comment by SuperMaXAleX** [comment]
Your world isn't converted to Anvil format. That's why it's getting corrupted. I'll fix.

**Comment by Infernus102** [comment]
is it done bro? @SuperMaXAleX

**Comment by DeathRaven359** [comment]
How exactly do you convert a world to Anvil format?

**Comment by EnderKenji** [comment]
You can convert your world by using Map Converter from ImagicalCorp. :) @DeathRaven359 
But still hope this issue can be fixed ASAP. 👍

**Comment by DeathRaven359** [comment]
Thanks, but that one doesn't work for me. I ran the start command on the MCregion to Anvil converter and when I tell it my folders and run the commands, it does nothing. So any hope on making it read region correctly? I spent a long time on my hub.

**Comment by EnderKenji** [comment]
You may need to get retired ImagicalCorp staff/developer to help you.

**Comment by Infernus102** [comment]
Please @SuperMaXAleX fix thissss

**Comment by SuperMaXAleX** [comment]
https://github.com/H4PM/Elywing/wiki/How-to-convert-a-MCRegion-world-to-an-Anvil-world-%3F

**Comment by SuperMaXAleX** [comment]
And you are using a default world of Elywing 0.16, so it get corrupted

**Comment by Infernus102** [comment]
Do i need to convert all worlds?

**Comment by Infernus102** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22660649/21479081/a1fa3616-cb77-11e6-97e3-ec9f676073af.png)
Is this an error? @SuperMaXAleX

**Comment by Infernus102** [comment]
@SuperMaXAleX Loaded the converted world, and it wasn't the same as before.

**Comment by SuperMaXAleX** [comment]
What folded did you selected exactly ?

**Comment by Infernus102** [comment]
the world folder @SuperMaXAleX

**Comment by Infernus102** [comment]
why has only my worlds corrupted?

**Comment by erkam2002** [comment]
Shit server xD

**Comment by Infernus102** [comment]
@erkam2002 Care to elaborate? http://minecraftpocket-servers.com/server/46320/

**Comment by erkam2002** [comment]
What my english is not so good xD

**Comment by Infernus102** [comment]
@erkam2002 Then you should think before you call someone's server shit, bro! Now, chill.

**Comment by erkam2002** [comment]
It was a pank xD have you the newest php binarys?

**Comment by Infernus102** [comment]
Yes i guess, 7.0.10

**Comment by erkam2002** [comment]
Newest is 7.0.14 ......

**Comment by erkam2002** [comment]
Do you have a VServer or Root?

**Comment by Infernus102** [comment]
Dedicated, Multicraft

**Comment by erkam2002** [comment]
ok...

**Comment by erkam2002** [comment]
https://github.com/iTXTech/php-build-scripts 
:D

**Comment by erkam2002** [comment]
Use this

**Comment by Infernus102** [comment]
I dont have access to the dedi!

**Comment by erkam2002** [comment]
Oh.

**Comment by Infernus102** [comment]
Did u fix? @SuperMaXAleX

**Comment by Infernus102** [comment]
BTW @SuperMaXAleX do you know this (YZX -> XZY) happened?

**Comment by SuperMaXAleX** [comment]
I know why the converter didn't convert this world. It's simple: it can't. This world is dead by new chunks.

**Comment by SuperMaXAleX** [comment]
And I'm not working on this part.

**Comment by Infernus102** [comment]
No, the dead world perfectly loads again when rolled back to 0.16

**Comment by Infernus102** [comment]
WEIRD, i just used PocketMine-MP phar and worlds don't get corrupted, maybe it's elywing, but i don't wanna use PocketMine so can you do something!!

**Comment by Infernus102** [comment]
Weird, my mcr world loads perfectly in Tesseract and PocketMine :/
