### ISSUE TITLE
[POLL] Mob AI

### ISSUE THREAD

**Issue by Muqsit** [H4PM/Elywing#158]
Should we add Mob AI (PureEntities)?
👍 => Yes
👎 => No

**Comment by erkam2002** [comment]
Yes but with on off function ;)

**Comment by EnderKenji** [comment]
Yeah, with on/off option. And hopefully will have more features like push texture pack to players, something like that. That would be great.

Hopefully MobAI will better than Genisys' , make the movement smoothly and cause less lag for server :)

**Comment by TDMidkwhatisxd** [comment]
Sure, mobs will be great!

**Comment by SuperMaXAleX** [comment]
@Misteboss Pourquoi tu dislikes ptdr ?

**Comment by shecter** [comment]
Yes.

**Comment by Driesboy** [comment]
no

**Comment by IgniteWhite** [comment]
Yes!!!

**Comment by SuperDude36** [comment]
Add it but make an option to toggle it on and off.

**Comment by erkam2002** [comment]
I have it said already -.-

**Comment by SuperDude36** [comment]
Great minds think alike. Im just to lazy to read... Good idea xD

**Comment by sero583** [comment]
@EnderKenji You are already able to. Send packages to the player!

**Comment by Qimie** [comment]
Make Hostiles Can Attack Players. Or Make Mobs Has Sounds.

**Comment by Frago9876543210** [comment]
Yes, good idea
