### ISSUE TITLE
[POLL] Stained glasses

### ISSUE THREAD

**Issue by SuperMaXAleX** [H4PM/Elywing#159]
Do you want Stained Glasses on Creative Mode directly or an option, example : creative-stained-glasses: off, and when we are turning this into 'on', it add Stained Glasses ! (They are implanted on MC:PE, but Mojang didn't added their textures so you/we need to download and install it on your game.)
###    For 👎 => No.

Don't forget to reacts and comments ! ;)

**Comment by TDMidkwhatisxd** [comment]
Why not? Maybe in new updates texture will be added! 👍

**Comment by SuperMaXAleX** [comment]
We are to give a .mcpack download link to get their textures :)

**Comment by Driesboy** [comment]
can the server automatic install a tecture pack?
in the betas if i join my server there stay: "loading the resourcepack"

**Comment by SuperMaXAleX** [comment]
Nop. :/

**Comment by Infernus102** [comment]
Can you first do the world converter thing? That should be priority.

**Comment by sero583** [comment]
@SuperMaXAleX It can

**Comment by sero583** [comment]
@Infernus102 Thats not that hard to DIY tbh

**Comment by thebigsmileXD** [comment]
I coded a plugin to add Stained Glass. (MCPE doen't have them because of color blending - they don't have working renderers/shaders for that yet.)
Instead of adding non-fully-implememnted stuff i request to let a plugin do this.
