### ISSUE TITLE
craft problems!

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [H4PM/Elywing#160]
My players complain because craft is not working!
Any fix?

**Comment by SuperMaXAleX** [comment]
A know bug

**Comment by TDMidkwhatisxd** [comment]
Just saw that there is already an issue, sorry :D ! 
Forgot to check closed issues too :D

**Comment by TDMidkwhatisxd** [comment]
Max can u fix craft pls? :D !

**Comment by erkam2002** [comment]
Was ne work crafting..

**Comment by TDMidkwhatisxd** [comment]
Craft no work for pe menu! But work in classic!

**Comment by SalmonGER** [comment]
Fixed this issue by using pmmp's code.

**Comment by shecter** [comment]
@SalmonGER are you saying this is fixed? or does more work need to be done?

**Comment by SalmonGER** [comment]
@shecter I fixed it locally. Instructions are up there, but I don't think it's a nice solution. It's only for desperated people, and I won't pr it.

**Comment by TDMidkwhatisxd** [comment]
I dont see instruction xd! But imma check!

**Comment by TDMidkwhatisxd** [comment]
Wen i click that link i see this line of code at line 3251
case ProtocolInfo::CRAFTING_EVENT_PACKET:

**Comment by shecter** [comment]
@salmonger thanks for clarification. I saw your message and got all hopeful that elywing had working crafting.

**Comment by andris155** [comment]
Fixed this bug.
https://github.com/H4PM/Elywing/commit/6bcf775c611742964113b0862eee89609c678a12

**Comment by thebigsmileXD** [comment]
So, retry after https://github.com/H4PM/Elywing/commit/291a66eb0d0acb8ea4dfe1dfefb86684ff24d332

**Comment by TDMidkwhatisxd** [comment]
Is crafting fixed?
@andris155  you code only allow planks, armour , to be crafted, sticks and other stuff wont work!

**Comment by eddir** [comment]
Classic interface work, but pocket doesnot work.

**Comment by andris155** [comment]
https://github.com/H4PM/Elywing/commit/291a66eb0d0acb8ea4dfe1dfefb86684ff24d332
removed my fixs :(

**Comment by andris155** [comment]
https://github.com/H4PM/Elywing/pull/302

**Comment by thebigsmileXD** [comment]
@andris155 they were really messy - re-clone them from genisys or PMMP.

**Comment by andris155** [comment]
re-clone killed crafting, and fixed code not working. :(
