### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by WreckagePE** [H4PM/Elywing#163]
I currently use netherbox as my server host which allows me to select my Server JAR. I have options such as Genisys, PocketMine, Imagicalmine and Default.
I used to run on genisys, however they are not updating to MCPE 1.0.0, so I decided to use ElyWing. I have installed it within ftp on the main directory and restarted my server, which still shows as outdated.
(I also still have the genisys.yml and stuff in there...)
What shall I do?

**Comment by Driesboy** [comment]
netherbox dont accept elywings

i think you need to search a better host :(

**Comment by WreckagePE** [comment]
Do you know a server host that DOES accept it? :(

**Comment by SuperMaXAleX** [comment]
MinerPlanets ;)

**Comment by Infernus102** [comment]
Virtual Gladiators are the best

**Comment by shecter** [comment]
Virtual Gladiators does, but I can't figure out how to change the source code here into a phar file that I can upload to VG. Sorry, noob question. Any pointers?

**Comment by AP3X3ROS** [comment]
Dev tools /makesever
