### ISSUE TITLE
Bug List

### ISSUE THREAD

**Issue by erkam2002** [H4PM/Elywing#166]
1. Enchantment work's only in Creative mode.
![ench](https://cloud.githubusercontent.com/assets/16340573/21470557/acefdd08-ca8e-11e6-93e8-8f2b30860958.png)
2. Gamemode Usage message.....
Description: Write /gm
![gm](https://cloud.githubusercontent.com/assets/16340573/21470570/221b8230-ca8f-11e6-9b6c-6eb2fac1b15f.png)

**Comment by SuperMaXAleX** [comment]
Wtf.
@Muqsit, did you touch something about lang.ini .-. ?

**Comment by erkam2002** [comment]
No i use deu language .. (German)

**Comment by Muqsit** [comment]
I had only modified TeleportCommand. I changed 128 to 256.
