### ISSUE TITLE
Nouveau Bug !

### ISSUE THREAD

**Issue by ItsXirano** [H4PM/Elywing#17]
Pour linstant le LocalHost Fonctionne tres clerement (SAUF W10)

Voici la lisite des bugs que je listerais au fur est a mesure 📦 

- MCW10 Crash 
- Block Placing Laggs
- Block destroying lag
- Chat is broken
- /Help Only Works if you are OPPED

**Comment by Muqsit** [comment]
Branch.. master or Genisys?

**Comment by ItsXirano** [comment]
Master

**Comment by SuperMaXAleX** [comment]
Re-download it now !
