### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by kamata4649** [H4PM/Elywing#170]
1.Going back and forth to the world  . Server freeze
2. Message to the sign Not saved.

**Comment by Pab450** [comment]
Hum okay, can you verify your server.properties file at line 24, if "auto-save=off" change this "auto-save=on" ! but "auto-save=on" verify your plugin.

**Comment by SuperMaXAleX** [comment]
On my server, ever message on a signs are saved. It's very strange.

**Comment by Pab450** [comment]
me too

**Comment by Pab450** [comment]
Fixed Sign with this version ! download : https://www.dropbox.com/sh/tnrmetqvxrob2kz/AADJAuz6dlHx7uLeKarykflva?dl=0

**Comment by SuperMaXAleX** [comment]
Mec, ENVOYE SUR ELWYING, TAIN
