### ISSUE TITLE
..? Only my server bug?

### ISSUE THREAD

**Issue by jdongel2004** [H4PM/Elywing#174]
(I'm korean. English is poor.)I want to put the.. InfiniteBlock plugin. But I was put plugin, pmmp doesn't load plugin. Only InfiniteBlock plugin.. If this problem is only my bug, you will closed this issues quickly plz ^^

**Comment by Pab450** [comment]
Error in the console ?

**Comment by jdongel2004** [comment]
No, console doesn't load InfiniteBlock plugin (only!)

**Comment by Pab450** [comment]
Link/url github ?

**Comment by jdongel2004** [comment]
https://github.com/HmHmmHm/InfiniteBlock/raw/master/InfiniteBlock-release.phar

**Comment by Pab450** [comment]
lel x)))

**Comment by Pab450** [comment]
okay just this plugin is just no finish it is missing the plugin.yml !

**Comment by jdongel2004** [comment]
I should be created? Or must be corrected?

**Comment by Pab450** [comment]
created the plugin.yml for fix it, but it is old, it must contain other bug.

**Comment by Pab450** [comment]
ho okay just wait please

**Comment by Pab450** [comment]
hum i test this for fix

**Comment by jdongel2004** [comment]
Thanks!♡

**Comment by Pab450** [comment]
this plugin is okay for me just wait

**Comment by Pab450** [comment]
i upload for you instruction

**Comment by Pab450** [comment]
https://www.dropbox.com/sh/lkijmh9n1sba7xv/AADI-rXQyxvrmUR9-Lq0mQmza?dl=0

**Comment by Pab450** [comment]
use this

**Comment by Pab450** [comment]
Place devtools and InfiniteBlock-master in your plugins folder for use

**Comment by Pab450** [comment]
it's okay ?

**Comment by SuperMaXAleX** [comment]
(keur les spams)

**Comment by jdongel2004** [comment]
Thanks @pab450   / I'm sorry SuperMaX

**Comment by Pab450** [comment]
okay ! i close this issue good luck for your server !
