### ISSUE TITLE
wont work with SynapsePM Plugin

### ISSUE THREAD

**Issue by LordTheFeak** [H4PM/Elywing#178]

**Comment by erkam2002** [comment]
Es ist nicht Genisys -.- Oh man und SynapsePM funkt noch nicht in der 1.0.0 -.-

**Comment by SuperMaXAleX** [comment]
Synapse has'nt be implanted --

**Comment by erkam2002** [comment]
I have said it in german i know him xD

**Comment by LordTheFeak** [comment]
XD
