### ISSUE TITLE
Ender Chest?

### ISSUE THREAD

**Issue by NycuRO** [H4PM/Elywing#179]
You can implement Ender Chest?

**Comment by Driesboy** [comment]
storage in player.data

**Comment by NycuRO** [comment]
What ? @Driesboy

**Comment by Driesboy** [comment]
idea!

**Comment by SuperMaXAleX** [comment]
@Muqsit

**Comment by Monkeyboy2805** [comment]
How about you actually figure out how to write PHP properly and then you can rewrite things so your servers don't crash every two seconds?

**Comment by Muqsit** [comment]
@Monkeyboy2805 not exactly what your mom said laat night.
Please stop complaining -.-
