### ISSUE TITLE
Pvp not work

### ISSUE THREAD

**Issue by NycuRO** [H4PM/Elywing#182]
PVP not work.

**Comment by Driesboy** [comment]
SAME LIKE DAMAGE!

**Comment by NycuRO** [comment]
HOW FIX?

**Comment by Pab450** [comment]
you can use other worlds ... (exemple in file worlds : "world", "worldpvp" ) damage is active in "worldpvp",  wait for fix it in "world"

**Comment by NycuRO** [comment]
Ok...

**Comment by NycuRO** [comment]
@Pab450 I changed name in "worldpvp" and not work pvp...

**Comment by NycuRO** [comment]
#Properties Config file
#Sun Dec 25 19:22:12 UTC 2016
motd=NycuRO SkyPvP
server-port=3006
white-list=off
announce-player-achievements=off
spawn-protection=200
max-players=100
allow-flight=off
spawn-animals=off
spawn-mobs=off
gamemode=0
force-gamemode=off
hardcore=off
pvp=on
difficulty=3
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon.password=CcS6OV9+jC
auto-save=on
online-mode=0

**Comment by NycuRO** [comment]
worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 world:
  generator: DEFAULT
 worldpvp:
  generator: FLAT

**Comment by Pab450** [comment]
--" goooooooodddd

**Comment by Pab450** [comment]
I did not say to do it!

**Comment by Pab450** [comment]
oups

**Comment by Pab450** [comment]
in folder worlds create a new world with plugin or other systeme  and load this world with plugin and teleport with plugin. name this world like you want exemple : "worldpvp"

**Comment by NycuRO** [comment]
@Pab450 Ok ,what plugin?

**Comment by Pab450** [comment]
I don't know, search by yourself ! or use map MCPC :)

**Comment by NycuRO** [comment]
@Pab450 I'm using Anvil world , PC. And not work.

**Comment by Pab450** [comment]
you have a two world ? in your worlds folder

**Comment by erkam2002** [comment]
PvP is not work was me too

**Comment by NycuRO** [comment]
Not work.

**Comment by NycuRO** [comment]
All software pvp works , but in this not.

**Comment by erkam2002** [comment]
I thing the problem is in old worlds i used a new generated world and it works but old not -.-

**Comment by NycuRO** [comment]
Why closed?
