### ISSUE TITLE
lava not damage, hmm.

### ISSUE THREAD

**Issue by oxxydev** [H4PM/Elywing#184]
![lava](https://pp.vk.me/c638031/v638031894/245d3/9jDKBHC2Msc.jpg)

**Comment by Pab450** [comment]
Principal world ? plugins ? difficulty ? spawn protection ? More details please !

**Comment by oxxydev** [comment]
server in first start, default elywing world generate.

**Comment by Pab450** [comment]
join this : https://github.com/H4PM/Elywing/issues/182
