### ISSUE TITLE
Chunks don't save builds above 128th block.

### ISSUE THREAD

**Issue by Muqsit** [H4PM/Elywing#187]
Chunks do not save y= 128+ edits.
Appreciate if anyone has a fix for it. Blu*****t has it on theirs.

**Comment by SuperMaXAleX** [comment]
nop ;-;

**Comment by SuperMaXAleX** [comment]
We don't have one...

**Comment by SuperMaXAleX** [comment]
And who is Blu*****t  ??

**Comment by Skull3x** [comment]
There is still allot that must be changed actually
https://github.com/H4PM/Elywing/search?p=2&q=128&utf8=%E2%9C%93

**Comment by Skull3x** [comment]
I'll download this and play around with it, see what I can come up with

**Comment by thebigsmileXD** [comment]
Check if still occurring now.
