### ISSUE TITLE
New blocks.

### ISSUE THREAD

**Issue by SergeyIvanov14** [H4PM/Elywing#188]
Can you add the working EnderChest and other end blocks and items, and when I spawn the EnderDragon he fall in blocks.

**Comment by erkam2002** [comment]
It will be added soon

**Comment by SergeyIvanov14** [comment]
Can you give me as date?

**Comment by erkam2002** [comment]
Idk but you can test it here -> UniFreesNet.de

**Comment by erkam2002** [comment]
If you want can i give you  this version

**Comment by SergeyIvanov14** [comment]
How to test?

**Comment by erkam2002** [comment]
wait

**Comment by erkam2002** [comment]
Come on UniFreesNet.de Port 5050
