### ISSUE TITLE
Use Void generator

### ISSUE THREAD

**Issue by erkam2002** [H4PM/Elywing#190]
Asynchronous Worker #4 thread:CRITICAL > Error: "Call to undefined method pocketmine\level\format\generic\GenericChunk::setBiomeColor()" (EXCEPTION) in "/src/pocketmine/level/generator/Void" at line 74
07:50:56 | Elywing thread:CRITICAL > Could not execute asynchronous task PopulationTask: Task crashed

**Comment by SuperMaXAleX** [comment]
An other player got this error before we added PMMP's code.

**Comment by SuperMaXAleX** [comment]
My bad.

**Comment by erkam2002** [comment]
xD

**Comment by erkam2002** [comment]
Fixed?

**Comment by AppleDevelops** [comment]
yep
