### ISSUE TITLE
friendly civilized conversation about christmas <3

### ISSUE THREAD

**Issue by Aericio** [H4PM/Elywing#191]
Merry christmas faggot @Pab450 <3

**Comment by SuperMaXAleX** [comment]
Man

**Comment by SuperMaXAleX** [comment]
Seriously ?

**Comment by SuperMaXAleX** [comment]
Lol "copy / paste". Yea. I love copy / paste. I don't have life. It's the best thing I do everytime. Oh yea. It's awesome.

**Comment by TDMidkwhatisxd** [comment]
Just close theyr issue and ban them from repo!

**Comment by SuperMaXAleX** [comment]
@TDMidkwhatisxd Why lol ? They are so funny. I out Elywing 1.0 before they out PMMP 1.0. I didn't copy their Chunks codes. But they don't want to understand and this guy is coming in the mode "U R GOIN TO STOP OR ILL KILL U".

**Comment by oxxydev** [comment]
wow, elywing is very good core.

**Comment by daniktheboss** [comment]
TDM... why are u acting like your one of the devs?

**Comment by TDMidkwhatisxd** [comment]
That dktapps noob and his minions are angry that we dont use genisys or that pmmp! 
He and his staff ban all ppl + insult  and expect to support them! Wtf!

**Comment by SuperMaXAleX** [comment]
Correct immediately your words. Dylan isn't stupid but I don't understand his reaction

**Comment by Aericio** [comment]
@oxxydev It was good at the beginning, now its just bugfest

**Comment by TDMidkwhatisxd** [comment]
U can be smart but stupid in some areas ;)

**Comment by daniktheboss** [comment]
NOOB? WTF LMAO U FUCKING COPIED ALL HIS SHIT AND U CALL HIM A NOOB?

**Comment by TDMidkwhatisxd** [comment]
Thanks max, i just wanted to dellete noob, and saw edited!

**Comment by SuperMaXAleX** [comment]
I'm working (I said it on Twitter). We didn't copied/paste every codes. So stop to create stupid issue with stupid arguments. It's unless.

**Comment by thebigsmileXD** [comment]
Shh keep calm its christmas.

**Comment by daniktheboss** [comment]
Hey Dan

**Comment by Aericio** [comment]
Then make it "currently unstable due to 0.17" instead. I never said that copy and pasting was bad, just don't blindly copy and paste.

**Comment by daniktheboss** [comment]
👍

**Comment by daniktheboss** [comment]
hmm.... why did it get so calm here? we still have a flame going on!

**Comment by TDMidkwhatisxd** [comment]
Merry Christmas ! ⛄❄❄❄❄❄🌲🌌

**Comment by daniktheboss** [comment]
Fine, i went a little harsh. Marry Christmas 😄

**Comment by Aericio** [comment]
@Pab450 Please learn your manners. It is not nice to edit someone's comment to change the whole point of the issue.

**Comment by Pab450** [comment]
okay but your comment is unpleasant for team elewing

**Comment by daniktheboss** [comment]
"unpleasant"

**Comment by Aericio** [comment]
It was not unpleasant, it was simply a message to not blindly copy and paste. I was also suggesting that you change your repo description to "currently unstable" instead.

**Comment by SuperMaXAleX** [comment]
Pab, t'es sérieux .-.

**Comment by Pab450** [comment]
no copy paste

**Comment by daniktheboss** [comment]
Its not the most stable thing on earth

**Comment by Pab450** [comment]
ouep je suis sérieux la

**Comment by daniktheboss** [comment]
Um

**Comment by daniktheboss** [comment]
So you coded this fully on your own?

**Comment by SuperMaXAleX** [comment]
J'allais tenir une conversation stable et la tu viens en mode "G V VS TUER"

**Comment by Pab450** [comment]
ouep mais le mec c'est un f d p selon moi

**Comment by Aericio** [comment]
![image](https://cloud.githubusercontent.com/assets/16523741/21486167/2c203e76-cb64-11e6-976f-d4e992c34742.png)
> no copy paste

Good joke @Pab450 !

**Comment by Pab450** [comment]
man....

**Comment by TDMidkwhatisxd** [comment]
Just block issue and ban the ones who was rude!

**Comment by Pab450** [comment]
You must surely be stronger than us!

**Comment by daniktheboss** [comment]
@Pab450 Why do you just randomly come here, and start cussing and being rude

**Comment by Aericio** [comment]
@TDMidkwhatisxd What are you, Kim Jun Un?

**Comment by daniktheboss** [comment]
@Pab450 Please leave, were talking to @SuperMaXAleX

**Comment by SuperMaXAleX** [comment]
.-.

**Comment by TDMidkwhatisxd** [comment]
Merry Christmas 🎄🎁👏👏👏👏👏👏

**Comment by Pab450** [comment]
@daniktheboss okay !

**Comment by Pab450** [comment]
good bye bro i like you !

**Comment by daniktheboss** [comment]
Christmas!

**Comment by Pab450** [comment]
What you are in life @Aericio ?

**Comment by Aericio** [comment]
i host leet.cc on my rack of a million rasberry pi's.

**Comment by daniktheboss** [comment]
And i help him.

**Comment by daniktheboss** [comment]
https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.wired.com%2Fwp-content%2Fuploads%2Fimages_blogs%2Fwiredenterprise%2F2012%2F09%2Frasberry-redux-three.jpg&imgrefurl=https%3A%2F%2Fwww.wired.com%2F2012%2F09%2Flego-super-gallery%2F&docid=rVy27cfgJK75_M&tbnid=oekW46SXMCoitM%3A&vet=1&w=660&h=288&bih=944&biw=1680&q=raspberry%20pi%20stack&ved=0ahUKEwi94aPB15LRAhUEyGMKHVCkDToQMwhIKAQwBA&iact=mrc&uact=8

**Comment by Pab450** [comment]
ho god... x) leet.cc

**Comment by daniktheboss** [comment]
![image](https://cloud.githubusercontent.com/assets/19934671/21486245/cb6e08a4-cb65-11e6-945c-274cf0460142.png)

**Comment by Aericio** [comment]
it's christmas themed. white is the snow, green is the grass, black is coal for bad kids, red is blood (?)

**Comment by Pab450** [comment]
Leet.cc is a scam

**Comment by Aericio** [comment]
Excuse me? Your insulting me, as the great home-hosted hoster of the leet.cc network.

**Comment by Pab450** [comment]
but you make a lot of money

**Comment by Pab450** [comment]
very lot of money

**Comment by Pab450** [comment]
very very very..

**Comment by Aericio** [comment]
Yeah. I make money from little kids using their parent's itunes and google play accounts :)

**Comment by Pab450** [comment]
bad...You make me ashamed

**Comment by TDMidkwhatisxd** [comment]
So leet host servers on rspi? Oh my gosh 😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😨

**Comment by AP3X3ROS** [comment]
Rip😂😂

**Comment by Nickleog** [comment]
Does H4PM means Horny for PocketMine?

**Comment by Driesboy** [comment]
@daniktheboss what do you host on raspberry?

**Comment by Aericio** [comment]
Nailed it.
