### ISSUE TITLE
Ctrl+c Ctrl+v

### ISSUE THREAD

**Issue by JackNoordhuis** [H4PM/Elywing#192]
Noticed you like to use the copy and paste shortcuts on your keyboard. Have you ever thought about actually giving credit to the people that spend their spare time writing the code? You probably wouldn't understand what it's like to have your code blindly copied because you've never written any code worth copying but you could at least give credit where it is due.

**Comment by JackNoordhuis** [comment]
@Aericio seems they have something against people exposing their copying and pasting methods 🤔

**Comment by Pab450** [comment]
yes.. @JackNoordhuis

**Comment by Pab450** [comment]
Why come to criticize us instead of ignoring us @JackNoordhuis ?

**Comment by JackNoordhuis** [comment]
Because it's wrong to take something that belongs to someone else without asking. @Pab450

**Comment by TDMidkwhatisxd** [comment]
#OpenSource  ;)

**Comment by Aericio** [comment]
That doesn't mean you can copy code without giving proper credit.

**Comment by Pab450** [comment]
Ho okay @JackNoordhuis so you delete your creatives that are open source on github and you can destruct Github x) hoodoo GODDD x)

**Comment by corytortoise** [comment]
It shouldn"t matter whether something is open-sourced or not. Just do the right thing and give credit where credit is due. 
 :)

**Comment by Muqsit** [comment]
@corytortoise Read README.md

**Comment by SuperMaXAleX** [comment]
We have given credits. So stop create stupid arguements :). It's unless to search something you can't found. :)

**Comment by Infernus102** [comment]
Fix the world converter @SuperMaXAleX

**Comment by Muqsit** [comment]
@Infernus102 intyre is working on a converter (Anvil => PMAnvil)

**Comment by SuperMaXAleX** [comment]
@Infernus102 Stop to spam me with this

**Comment by Infernus102** [comment]
Okay thanks @muqsit and thanks for nothing @supermaxalex

**Comment by SuperMaXAleX** [comment]
@Infernus102 No problem, and I'm not a magician. AND, I'm not working on this part.

**Comment by Infernus102** [comment]
Should have replied that then, bro @supermaxalex

**Comment by corytortoise** [comment]
Sorry if I just missed it, but where are credits given to iTXTech or Genisys?
