### ISSUE TITLE
Keep getting this issues

### ISSUE THREAD

**Issue by AP3X3ROS** [H4PM/Elywing#193]
![screenshot_2016-12-26-16-47-11](https://cloud.githubusercontent.com/assets/24553998/21487274/08018500-cb8b-11e6-8de6-460d944605bb.png)

Keep getting that error n boats are messed up 
![screenshot_2016-12-26-16-00-10](https://cloud.githubusercontent.com/assets/24553998/21487279/23a1f2f4-cb8b-11e6-85a2-01139fcc08cc.png) when players use them u get that error on console.

**Comment by SuperMaXAleX** [comment]
The method getXp/getExpLevel of Player.php is deprecated. You need to use Human.php to get xp level of a player

**Comment by MrReskill** [comment]
If you want to use this and delete this message, go in elywings code and delete the line with this error message.
