### ISSUE TITLE
World issue

### ISSUE THREAD

**Issue by VoliPlays** [H4PM/Elywing#194]
Everytime i put one of my worlds made in 0.16 or the server create me a new one I get this error: 
Fatal error: Declaration of pocketmine\level\format\generic\BaseLevelProvider::__construct(pocketmine\level\Level $level, $path) must be compatible with pocketmine\level\format\LevelProvider::__construct(pocketmine\level\Level $level, string $path) in /home/kitpvp/src/pocketmine/level/format/generic/BaseLevelProvider.php on line 16
05:03:57 | Elywing thread:EMERGENCY > An unrecoverable error has occurred and the server has crashed

Os and version:
-Running on ubuntu 16.04
-Latest version of elywing

**Comment by TDMidkwhatisxd** [comment]
https://files.fm/u/44w78w49
Use this phar!

**Comment by VoliPlays** [comment]
![screenshot_2016-12-28-22-06-46]

**Comment by VoliPlays** [comment]
![screenshot_2016-12-28-22-06-46](https://cloud.githubusercontent.com/assets/23141416/21530565/53a6c3f6-cd4a-11e6-89e3-72d41d0c27da.png)

**Comment by VoliPlays** [comment]
I still geting this

**Comment by Driesboy** [comment]
same

**Comment by VoliPlays** [comment]
I think is something with world generator or idk i'm not a scripter:)

**Comment by TDMidkwhatisxd** [comment]
I got exactly same error after i replaced some level files with pmmp files ^^ ! 
I never got this problem, so idk what to do :D !

**Comment by TDMidkwhatisxd** [comment]
Tested on local server! Delleted the world and let it generating!
I think is biome problem! 1.0 changed biome !

**Comment by Driesboy** [comment]
but its with a plugin

**Comment by TDMidkwhatisxd** [comment]
I opened my server again and works, no errors! I think the error happens wen world start generating,  becouse after this no error!

**Comment by Henning-Klatt** [comment]
Try to convert your world 
https://github.com/H4PM/Elywing/wiki/How-to-convert-a-MCRegion-world-to-an-Anvil-world-%3F

**Comment by TDMidkwhatisxd** [comment]
![screenshot_2016-12-28-22-22-59](https://cloud.githubusercontent.com/assets/18122629/21530842/3ecf25b6-cd4c-11e6-8a8d-da10ff016fd5.png)

If your default world generate in background, it crash! If u open server again all fine!

**Comment by Driesboy** [comment]
but it is with a plugin like MyPlot

**Comment by Driesboy** [comment]
after a biome change

**Comment by TDMidkwhatisxd** [comment]
Ohhhh 0-0

**Comment by TDMidkwhatisxd** [comment]
Nope! It give u console warning but not a crash :D ! But u can block biome subcommand!

**Comment by VoliPlays** [comment]
Can anyone give a map generated?

**Comment by TDMidkwhatisxd** [comment]
Search a small PC map! They work now!

**Comment by VoliPlays** [comment]
Still not work and i don't have a PC to convert my maps in anvil

**Comment by Monkeyboy2805** [comment]
Idea: DON'T DO SOMETHING YOU HAVE NO IDEA HOW TO DO!
This thing only exists because their PRs would never get accepted at Genisys or PM even if the "devs" did know what they were doing.

**Comment by thebigsmileXD** [comment]
May be fixed on latest commit.
