### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by erkam2002** [H4PM/Elywing#195]
Elywing thread:CRITICAL > ParseError: "syntax error, unexpected 'DATA_FLAG_FALL_FLYING' (T_STRING), expecting function (T_FUNCTION)" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 155
05:55:41 | Elywing thread:EMERGENCY > An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by SuperMaXAleX** [comment]
Already fixed.
