### ISSUE TITLE
Bug /hub

### ISSUE THREAD

**Issue by Simplygamer** [H4PM/Elywing#2]
J'ai tt simplement rejoint un serveur sur lequel est installer ton pm(en l'occurence ici GloriousFight) et j'ai pu me /login facilement mais quand j'ai fait /hub ça m'a fait un bug de tp,impossible de bouger.

**Comment by SuperMaXAleX** [comment]
Possible de montrer la partie du code du /hub ?

**Comment by Simplygamer** [comment]
Faut demander à Misteboss

**Comment by MrReskill** [comment]
Bonjour,
Je ne suis pas sur mais il me semble que nous n'avons pas mis à jours les commandes.
Il est donc je croit impossible de faire des commandes personnalisé êtes vous sur que /login fonctionne ?

Reskill, H4PE Team.

**Comment by SuperMaXAleX** [comment]
Il est possible qu'en fait, le problème vient de la map.

**Comment by MrReskill** [comment]
D'après @LCraftPE, le but pourrait être du au monde non load.
Le monde est bien load ? 

Sinon vous pouvez ajouté ce code dans onEnable:
$monde = "NOM";
$this->getServer()->loadLevel($monde);

Res.

**Comment by LCraftPE** [comment]
Bonjour, @Simplygamer, il semblerait que le bug soit dû à la génération du monde. 
Pour le corriger, il suffit de rajouter à votre code (juste avant la téléportation au monde):
$this->getServer()->loadLevel("nomdumonde");

**Comment by Simplygamer** [comment]
Ouep tkt mais c'est pas pour moi x)

**Comment by Misteboss** [comment]
@LCraftPE j'ai ajouter le load est mtn quand un joueur rejoint Raklib crash :/
[36m[06:04:54] [m[31m[Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to RakLib Thread crashed[m
