### ISSUE TITLE
My opinion about Elywing

### ISSUE THREAD

**Issue by SergeyIvanov14** [H4PM/Elywing#204]
I thought that you are serious developers but you have a lot of errors with rcon, one boy hacked rcon password and broken my server. Sorry but I thought that you are serious developers.

**Comment by TDMidkwhatisxd** [comment]
Im top3 server and still not hacked! I even get ddosed!  Another #dktappsminion !

**Comment by SergeyIvanov14** [comment]
Give me your IP and PORT.

**Comment by Aericio** [comment]
#192 #191 :)

**Comment by IrishPacks** [comment]
I have to agree about Elywing being broken. They lack professionalism and organization as well as take a lot from PMMP to fix their own issues. Again these are problems, only you guys can turn it into a solution.

**Comment by Aericio** [comment]
My solution: delete the repository.

**Comment by SuperMaXAleX** [comment]
lol. "Delete repository". I have maaaanyyyyy reasons (and many of them is about Dylan) to not delete it. 
About your problem @SergeyIvanov14, I'm using Elywing 3 months and nothing happened and the RCON code is same as Genisys.

**Comment by SuperMaXAleX** [comment]
@IrishPacks This is what we want to do. But soooooome peoples is discouraging us and others is saying sh** about Elywing. (cc Dylan)

**Comment by SuperMaXAleX** [comment]
And when I saw this: [http://image.noelshack.com/fichiers/2016/52/1482911322-img-2416.jpg](url)
I said to myself "wow, always more stupid excuses".
This page got deleted some minutes later.
So at now, don't say me anything about : Delete Elywing
Credit files who we don't need to credit because we did them to ourself
Modify stupid things for stupid results 
I have my reasons.

**Comment by badp1g** [comment]
Yobanij sergey... Kinul me... On 4k ! How not stidno ?!

**Comment by Monkeyboy2805** [comment]
@SuperMaXAleX Yes, and everything Dylan is true you f*cking scam artists. The only reason Elywing "supported" 1.0 earlier was just because you copied all of Genisys developments made by Dylan and merged it into PM. IDIOTS!

**Comment by Monkeyboy2805** [comment]
@TDMidkwhatisxd AND YES YOU DID HACK IT TO GET IT WORKING COS YOU DIDN'T KNOW HOW TO DO IT PROPERLY!!! Don't copy-paste other people's work and then display it as your own.
