### ISSUE TITLE
duplication glitch (critical)

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [H4PM/Elywing#205]
By abusing floating inventory , player can duplicate all stuff!

I suggest that all items stuck in floating inventory should be delleted instead of drop! Chests/craft/etc, in any situation!

Imma do that tomorow! 

How i know? A player showed me how is done! I didnt actually get it, but by stressing floating inventory, i duplicated some stacks of redstones!

The duplication glitch work only on android and ios!

**Comment by Muqsit** [comment]
I think this needs to be removed...
https://github.com/H4PM/Elywing/blob/master/src/pocketmine/Player.php#L3246

**Comment by TDMidkwhatisxd** [comment]
I think so too!

**Comment by TDMidkwhatisxd** [comment]
But what about the items that get stuck inside floating inventory? Need erased!

**Comment by Muqsit** [comment]
Try @Infernus102's PR and tell us if you encounter any errors.

**Comment by TDMidkwhatisxd** [comment]
Im really sick right now, sorry for didnt test i sleep too much!
I will test it soon :D

**Comment by Infernus102** [comment]
@TDMidkwhatisxd how did you convert your worlds to anvil?

**Comment by TDMidkwhatisxd** [comment]
I didnt ;) ! I had 1 world mcr wich i delleted and all players raged at me! It was a plots map xd

**Comment by TDMidkwhatisxd** [comment]
I get this error on close/open inventory!
I use gensys app, but i use elywing server xd, dont be confused!

![screenshot_2016-12-28-11-29-55](https://cloud.githubusercontent.com/assets/18122629/21518739/274c7340-ccf1-11e6-9a6b-6f25faf1c976.png)

**Comment by TDMidkwhatisxd** [comment]
This is how i edited!
![screenshot_2016-12-28-11-42-11](https://cloud.githubusercontent.com/assets/18122629/21518988/b87f9878-ccf2-11e6-93c3-bfc0db67c021.png)

**Comment by Infernus102** [comment]
the glitch happens when you open a chest tile?

**Comment by TDMidkwhatisxd** [comment]
Normal inventory and i found out what u need to dellete!

**Comment by Infernus102** [comment]
Okay then make a pr

**Comment by TDMidkwhatisxd** [comment]
Nope, it will make problems with chests! 
If i remove that line of code to stop error, chest cant be closed, if u open/close, u cant open chest again!

**Comment by TDMidkwhatisxd** [comment]
I will try to test some stuff!

**Comment by TDMidkwhatisxd** [comment]
Failed! It seems if u dellete the line were drop stuff from floating inventory, will trigger console errors!
Can someone modify it to dellete item instead of drop?

**Comment by TDMidkwhatisxd** [comment]
Did a pull request, now i will update my server too!

**Comment by ZacharySims** [comment]
Actually the part about it working for only Android and iOS is untrue. It also works for Win10, you just have to switch to the Pocket UI in settings. (To replicate, switch to pocket UI, open a hopper feeding into a chest or dropper, put an entire stack into the hopper, rapidly click the stack and you'll have more then what you started with when you check the chest)
