### ISSUE TITLE
signs dont save

### ISSUE THREAD

**Issue by Driesboy** [H4PM/Elywing#208]
type in a sign, close your sign, leave and come back

there is no text

**Comment by SuperMaXAleX** [comment]
It's a problem of MCPE.
This problem exists very long time. It affecting MCPE version after 0.11.

**Comment by Driesboy** [comment]
but its after the elytra update

**Comment by SuperMaXAleX** [comment]
What are exactly the conditions ?

**Comment by SuperMaXAleX** [comment]
Says them on #212
