### ISSUE TITLE
Signs aren't saving.

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [H4PM/Elywing#212]
Didnt expect that but signs do not save!

They worked wen elwing added first commits to elytra! But latest dont work!

Cant be becouse of my commit ^^

**Comment by TDMidkwhatisxd** [comment]
Is weird! I cant even create new sign shop ;-; ! If will check tomorow, im really very sick :( !

**Comment by TDMidkwhatisxd** [comment]
Reproduce steps, to see !
1. Write a signs!
2. Relogin.
3.Sign empty!

**Comment by SergeyIvanov14** [comment]
Yeeeeees, please fix.

**Comment by LuciaPE** [comment]
I think it's because of SignChangeEvent, which never called in anywhere.
https://github.com/H4PM/Elywing/issues/218

**Comment by Driesboy** [comment]
but its a bug since the elytra commits

**Comment by thebigsmileXD** [comment]
May be fixed, please check
