### ISSUE TITLE
Item frames Dupe

### ISSUE THREAD

**Issue by AP3X3ROS** [H4PM/Elywing#219]
You can mass dupe using item frames now.

**Comment by TDMidkwhatisxd** [comment]
Wtf ;-; ! Imma check

**Comment by TDMidkwhatisxd** [comment]
Nope! You lose items using frame !
Example ! Get a stack of dirt, put in frame, bye stack of dirt , and if u take back u get 1 dirt!

So, how u use frames to duplicate stuff?!
