### ISSUE TITLE
PR ClearSky/Elywing to H4PM/Elywing

### ISSUE THREAD

**Issue by thebigsmileXD** [H4PM/Elywing#226]
Hello. I fixed several stuff on http://github.com/ClearSkyTeam/Elywing
should i create a PR? This will temporarily disable weather and dimensions, the code needs rewrite anyways, because its really unclean. Also, @pmmp is about to implement a new way for dimensions anyways.
Fixed stuff: all regions load + send to the player
working tiles + noteblocks
windows 10 inventory fully fixed + working on 1.0
new nbtSerialize/deserialize functions used
fixed ioining the server (no crash)

**Comment by Muqsit** [comment]
Yes please. And thanks <3

**Comment by Monkeyboy2805** [comment]
@thebigsmileXD What's the point? You may as well work on ClearSky or PM for all this is worth.

**Comment by thebigsmileXD** [comment]
@Monkeyboy2805 i would work on pm, if they would let me
CS is inactive for now
And i didnt talk about the mess, i talked about the fact that i fixed mess of wrong pr's etc, and incorrect commit cloning

**Comment by SuperMaXAleX** [comment]
Dan, welcome to H4PM. :)
You have the possibility to merge it yourself :D!

**Comment by SuperMaXAleX** [comment]
And thanks you very much ! (And if you can fix crafts, it's going to be amazing, and it's going to attack me on Twitter lol)

**Comment by thebigsmileXD** [comment]
Done and dusted.
