### ISSUE TITLE
Crash plugin latest update issue

### ISSUE THREAD

**Issue by erkam2002** [H4PM/Elywing#228]
Elywing thread:CRITICAL &gt; Could not execute task ****\RefreshSigns: Call to undefined method pocketmine\tile\Sign::onChanged()
15:23:09 | Elywing thread:CRITICAL &gt; Error: "Call to undefined method pocketmine\tile\Sign::onChanged()" (EXCEPTION) in "/src/pocketmine/tile/Sign" at line 61

**Comment by Henning-Klatt** [comment]
I have the same problem, here is my code:
![bildschirmfoto 2016-12-29 um 20 37 44](https://cloud.githubusercontent.com/assets/12398950/21567584/8e5c14ce-cead-11e6-8576-66bd87d5169b.png)

Hope you can fix it guys!

**Comment by Muqsit** [comment]
https://github.com/H4PM/Elywing/tree/sign-onChanged()
Try that branch!

**Comment by Henning-Klatt** [comment]
Perfect, all works fine!
