### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by KingDeadKnight** [H4PM/Elywing#23]
When breaking blocks, i pick up drops
Nothing in inventory's cases and when I quit inventory, all the stuff i picked up, drop

**Comment by SuperMaXAleX** [comment]
It's a bug we already know. It's going to be fixed.

**Comment by Pogogo007** [comment]
#25

**Comment by KingDeadKnight** [comment]
Don't look at closed issue.. For me closed issues is fixed so..

**Comment by Pogogo007** [comment]
I mean #26 xd

**Comment by KingDeadKnight** [comment]
oh Ok x)

**Comment by TheAppleGamer** [comment]
Fixed

**Comment by Pogogo007** [comment]
This was fixed close?
