### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by StijnSimons** [H4PM/Elywing#234]
Once i startup my server, this is what i get:
`dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/stijnsimons/Desktop/testserver/Pocketmine/bin/php7/bin/../lib/libcurl.4.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/stijnsimons/Desktop/testserver/Pocketmine/bin/php7/bin/../lib/libcurl.4.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5`
What does this mean?

**Comment by Pab450** [comment]
you are on mac ?

**Comment by StijnSimons** [comment]
Yes i am

**Comment by StijnSimons** [comment]
If i use a diffirent PHP bin, it gives me this error;
./start.sh: line 54: /Users/stijnsimons/Desktop/testserver/Pocketmine/bin/php7/bin/php: cannot execute binary file
./start.sh: line 54: /Users/stijnsimons/Desktop/testserver/Pocketmine/bin/php7/bin/php: Undefined error: 0

**Comment by AppleDevelops** [comment]
No permission in the bin folder, I believe.

**Comment by Muqsit** [comment]
Your PHP binaries are corrupted. Use the php-build-scripts from iTXTech.
