### ISSUE TITLE
Spawners

### ISSUE THREAD

**Issue by Infernus102** [H4PM/Elywing#236]
16:48:12 | Elywing thread:CRITICAL > Could not tick level "lobby": Argument 1 passed to pocketmine\event\entity\EntityGenerateEvent::__construct() must be an instance of pocketmine\level\Position, instance of pocketmine\math\Vector3 given, called in E:\PocketMine-MP\src\pocketmine\tile\MobSpawner.php on line 137

**Comment by Infernus102** [comment]
@erkam2002 @SuperMaXAleX @Muqsit

**Comment by erkam2002** [comment]
Have you putted any entity in spawner?

**Comment by Infernus102** [comment]
yep

**Comment by Infernus102** [comment]
i directly put it by this 
$tile = $this->block->getLevel()->getTile(new Vector3($this->block->getX(), $this->block->getY(), $this->block->getZ()));
$tile->setEntityId(32);

**Comment by erkam2002** [comment]
Work it without?

**Comment by erkam2002** [comment]
**Use this:**

$tile = $this->block->getLevel()->getTile($this->block->getX(), $this->block->getY(), $this->block->getZ()));
$tile->setEntityId(32);

**Comment by Infernus102** [comment]
no it throws back the egg

**Comment by Infernus102** [comment]
ok lemme check

**Comment by erkam2002** [comment]
Error code?

**Comment by erkam2002** [comment]
Have you teamspeak xD

**Comment by Infernus102** [comment]
Could not execute task PTask: Argument 1 passed to pocketmine\level\Level::getTile() must be an instance of pocketmine\math\Vector3, integer given, called in Main.php on line 5669
 TypeError: "Argument 1 passed to pocketmine\level\Level::getTile() must be an instance of pocketmine\math\Vector3, integer given, called in Main.php on line 5669" (EXCEPTION) in "/src/pocketmine/level/Level" at line 1864

**Comment by erkam2002** [comment]
PTask?

**Comment by Infernus102** [comment]
its a plugin task

**Comment by erkam2002** [comment]
xd

**Comment by erkam2002** [comment]
Wait i test it self

**Comment by Infernus102** [comment]
you got discord?

**Comment by erkam2002** [comment]
yes

**Comment by StijnSimons** [comment]
Maybe make a Elywing discord?^ It's better for support

**Comment by erkam2002** [comment]
Or TeamSpeak :)

**Comment by Infernus102** [comment]
discord is better

**Comment by erkam2002** [comment]
:(

**Comment by StijnSimons** [comment]
Yea with text :D

**Comment by StijnSimons** [comment]
Shouldn't H4PM make a discord?

**Comment by erkam2002** [comment]
https://discord.gg/7wTvg

**Comment by StijnSimons** [comment]
It's german :$

**Comment by Infernus102** [comment]
which one are you erkam?

**Comment by erkam2002** [comment]
mcpe_exert
