### ISSUE TITLE
Can i get some help using iTXTech's php-build-script for Elywing?

### ISSUE THREAD

**Issue by StijnSimons** [H4PM/Elywing#238]
_title says it all_
Tried a couple things, still don't get how to end up with a php7 bin

**Comment by erkam2002** [comment]
Linux or Windows`?

**Comment by StijnSimons** [comment]
Mac - Linux

**Comment by erkam2002** [comment]
Download it unzip and then chmod +x linux*
apt-get install libssl-dev autoconf pkg-config curl libedit-dev libsqlite3-dev libxml2-dev libcurl4-openssl-dev libyaml-dev
apt-get install build-essential
./linux*

**Comment by StijnSimons** [comment]
Since i'm on a mac, i'll download Fink to use apt-get. Be right back.

**Comment by StijnSimons** [comment]
Installing Fink takes ages, hopes its done soon

**Comment by StijnSimons** [comment]
Fink doesnt, work, any other options?

**Comment by StijnSimons** [comment]
It does work, but gives me this error: 
E: Could not open lock file /sw/var/lib/dpkg/lock - open (13 Permission denied)
E: Unable to lock the administration directory (/sw/var/lib/dpkg/), are you root?
MacBook-Pro-van-Stijn:php-build-scripts-master 4 stijnsimons$ apt-get install build-essential
E: Could not open lock file /sw/var/lib/dpkg/lock - open (13 Permission denied)
E: Unable to lock the administration directory (/sw/var/lib/dpkg/), are you root?
MacBook-Pro-van-Stijn:php-build-scripts-master 4 stijnsimons$ ./linux*
tar (grandchild): xz: Functie exec() is mislukt: No such file or directory
tar (grandchild): Error is not recoverable: exiting now
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
curl: (23) Failed writing body (0 != 1436)

**Comment by erkam2002** [comment]
You are not using this script with root..

**Comment by daniktheboss** [comment]
Not a elywing issue please close
