### ISSUE TITLE
Entity nametags doesn't working ? (Slapper exemple)

### ISSUE THREAD

**Issue by Misteboss** [H4PM/Elywing#24]
When i spawn a slapper the title doesn't appear and i am "lied" with him (screenshots)
![img_2336](https://cloud.githubusercontent.com/assets/17687222/19787428/f3ef96b8-9ca2-11e6-9a96-f517a1c1b39e.PNG)

**Comment by TheAppleGamer** [comment]
That's because Slapper needs to be updated to 0.16

**Comment by Pogogo007** [comment]
Reopen this

**Comment by Pogogo007** [comment]
This might actually be a server software bug

**Comment by TheAppleGamer** [comment]
Actually Pogo, they changed how nametags work in PE, and slapper does not use the new nametags.

**Comment by Muqsit** [comment]
This isn't a server bug. Use setNameTagVisible() and setNameTagAlwaysVisible()
Or
Use the new data flags.
