### ISSUE TITLE
I can't listen to music of noteblock 

### ISSUE THREAD

**Issue by Takesikaityo** [H4PM/Elywing#241]
I can't listen to music of noteblock.

**Comment by Driesboy** [comment]
with a plugin???

**Comment by Takesikaityo** [comment]
yes,I used plugin. It's song plugin.
https://youtu.be/aSsrDAG4his
↑I watched this movie.

**Comment by Driesboy** [comment]
source?

**Comment by Takesikaityo** [comment]
No, i didn't.
I used Phar plugin.

**Comment by Infernus102** [comment]
Start music from your music player, why you need minecraft for that?

**Comment by Driesboy** [comment]
yeah

**Comment by Driesboy** [comment]
like youtube or something like that

**Comment by Takesikaityo** [comment]
Because, I want to use this.
https://youtu.be/JM1rhepgBRM

**Comment by Takesikaityo** [comment]
Yes

**Comment by thebigsmileXD** [comment]
Fixed.
