### ISSUE TITLE
Can't craft item from crafting table!

### ISSUE THREAD

**Issue by ParkChanSol** [H4PM/Elywing#247]
When craft item at crafting table, It cancelled.
Reference under movie
* Link(DropBox) : https://www.dropbox.com/s/nixuon1rnxb8ngn/mobizen_20170101_101201.mp4?dl=0

**Comment by Mintos74** [comment]
Some servers never produce combined results.

**Comment by Infernus102** [comment]
This is known and in fix.

**Comment by ParkChanSol** [comment]
@Infernus102 Thank you :)

**Comment by shecter** [comment]
In the fix? Do you mean it's been merged with Master?

**Comment by Infernus102** [comment]
No, it's not merged.

**Comment by Infernus102** [comment]
Fixed, check my PR

**Comment by SuperMaXAleX** [comment]
Know issue. There is already one about this.
