### ISSUE TITLE
Warning: zlib_decode(): data error

### ISSUE THREAD

**Issue by andris155** [H4PM/Elywing#255]
`Warning: zlib_decode(): data error in phar:///Elywing.phar/src/pocketmine/network/Network.php on line 235`

**Comment by SuperMaXAleX** [comment]
You did something wrong when you compiled Elywing in .phar.

**Comment by Infernus102** [comment]
No @SuperMaXAleX, check this https://github.com/iTXTech/Genisys/issues/2280

**Comment by Infernus102** [comment]
You can close this
