### ISSUE TITLE
Level::spawnXPOrb()

### ISSUE THREAD

**Issue by andris155** [H4PM/Elywing#262]
`02.01 13:33:06 [Server] CRITICAL Could not tick level "skypvp": Call to undefined method pocketmine\level\Level::spawnXPOrb()`

**Comment by erkam2002** [comment]
Do you use Elywing ClearSky?

**Comment by andris155** [comment]
Elywing

**Comment by erkam2002** [comment]
How to reproduce it?

**Comment by SuperMaXAleX** [comment]
Again, no informations or precious and how did you reproduced it'
