### ISSUE TITLE
Animate Packet is broadcasted

### ISSUE THREAD

**Issue by Iktaniyalol** [H4PM/Elywing#272]
Hi again.
When somebody player put or break block, all players' hand start moving. Its very strange.

**Comment by thebigsmileXD** [comment]
everyones? LOL

**Comment by Iktaniyalol** [comment]
Yes xd

**Comment by thebigsmileXD** [comment]
WTF

**Comment by Iktaniyalol** [comment]
Sometimes hand mooing itself, but i am alone...
And load sometimes reaches 100%..
On Genisys load was small.So sometimes there is a large number of particles piped player.

**Comment by SuperMaXAleX** [comment]
True. This is very strange. I have it on very software lol

**Comment by thebigsmileXD** [comment]
@Iktaniyalol confirmed by some other guy in a group

**Comment by Iktaniyalol** [comment]
I understand I have to confirm? Or already confirmed? I have a problem with English

**Comment by thebigsmileXD** [comment]
Someone else said it happened 
![image](https://cloud.githubusercontent.com/assets/8733998/21648489/79cf5288-d29e-11e6-92c5-8e2a9d076194.png)

**Comment by Iktaniyalol** [comment]
Can it fix?players my server (russia) is very angry by this and not having fun)

**Comment by AppleMinerHD** [comment]
Yea thats true...

**Comment by AppleMinerHD** [comment]
Is it fixed know?

**Comment by KennFatt** [comment]
Please check it again, i think it was fixed on latest build.

**Comment by thebigsmileXD** [comment]
I had something similar happening on pmmp yesterday. I switched the world, and suddenly my arm moved every second.
