### ISSUE TITLE
i have a problem with a map!

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [H4PM/Elywing#274]
I have a problem with a map! 

If i go in that map and then leave, i cant go back to map!
I mean, it say , i got teleported,but blocks dont update! And is just one map, whyy?

**Comment by Infernus102** [comment]
@TDMidkwhatisxd how did you fix crafting?

**Comment by TDMidkwhatisxd** [comment]
https://github.com/H4PM/Elywing/pull/267

**Comment by Infernus102** [comment]
Yea that doesn't work, nvm i fixed it on my server FallenTech

**Comment by TDMidkwhatisxd** [comment]
Ummm! There was a pull request that changed player.php and craftitemevent
I copyed just player.php changes

**Comment by TDMidkwhatisxd** [comment]
Naaah, craft not fixed, i can only craft planks lol

**Comment by Infernus102** [comment]
Yep ik

**Comment by thebigsmileXD** [comment]
Test with new code.
