### ISSUE TITLE
CRASH SERVER ChunkException

### ISSUE THREAD

**Issue by LamKietCrack** [H4PM/Elywing#277]
Error: Class pocketmine\level\format\generic\ChunkException not found
File: /src/spl/BaseClassLoader
Line: 144
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[135] 
[136] 	        if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[137] 		        $name::onClassLoaded();
[138] 	        }
[139] 	        
[140] 	        $this->classes[] = $name;
[141] 
[142]             return true;
[143]         }elseif($this->getParent() === null){
[144] 	        throw new ClassNotFoundException("Class $name not found");
[145]         }
[146] 
[147]         return false;
[148]     }
[149] 
[150]     /**
[151]      * Returns the path for the class, if any
[152]      *
[153]      * @param string $name
[154]      *

Backtrace:
#0 /src/pocketmine/level/format/generic/GenericChunk(103): spl_autoload_call(string pocketmine\level\format\generic\ChunkException)
#1 /src/pocketmine/level/format/generic/GenericChunk(691): pocketmine\level\format\generic\GenericChunk->__construct(pocketmine\level\format\region\McRegion object, integer 9, integer 23, array Array(), array Array(), array Array(), string ................................................................................................................................................................................................................................................................, array Array())
#2 /src/pocketmine/level/generator/PopulationTask(173): pocketmine\level\format\generic\GenericChunk::fastDeserialize(NULL , pocketmine\level\format\region\McRegion object)
#3 /src/pocketmine/scheduler/AsyncPool(151): pocketmine\level\generator\PopulationTask->onCompletion(pocketmine\Server object)
#4 /src/pocketmine/scheduler/ServerScheduler(268): pocketmine\scheduler\AsyncPool->collectTasks(boolean)
#5 /src/pocketmine/Server(2832): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 621375)
#6 /src/pocketmine/Server(2523): pocketmine\Server->tick(boolean)
#7 /src/pocketmine/Server(2401): pocketmine\Server->tickProcessor(boolean)
#8 /src/pocketmine/Server(1991): pocketmine\Server->start(boolean)
#9 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Administrator\Desktop\SkyBlock\, string C:\Users\Administrator\Desktop\SkyBlock\, string C:\Users\Administrator\Desktop\SkyBlock\plugins\, string unknown)

**Comment by KingDeadKnight** [comment]
It's caused by a plugin, it's write in that crashdump

**Comment by thebigsmileXD** [comment]
Chunkexception got removed btw..

**Comment by thebigsmileXD** [comment]
@KingDeadKnight Learn reading and inspection crashdumps. 
GenericChunk::fastDeserialize(NULL ,

**Comment by thebigsmileXD** [comment]
Please check if this still occurs

**Comment by LamKietCrack** [comment]
I Have Deleted All The Plugin But Still Error

**Comment by thebigsmileXD** [comment]
No not plugin as i said, server fault.
