### ISSUE TITLE
Nbt issues

### ISSUE THREAD

**Issue by Misteboss** [H4PM/Elywing#281]
12:23:01 | Elywing thread:ERROR > Error while unloading a chunk: Argument 1 passed to pocketmine\item\Item::nbtDeserialize() must be an instance of pocketmine\nbt\tag\CompoundTag, instance of pocketmine\item\ItemBlock given, called in /home/test/src/pocketmine/tile/Chest.php on line 129
12:23:01 | Elywing thread:CRITICAL > TypeError: "Argument 1 passed to pocketmine\item\Item::nbtDeserialize() must be an instance of pocketmine\nbt\tag\CompoundTag, instance of pocketmine\item\ItemBlock given, called in /home/test/src/pocketmine/tile/Chest.php on line 129" (EXCEPTION) in "/src/pocketmine/item/Item" at line 1038

**Comment by SuperMaXAleX** [comment]
-> @Infernus102

**Comment by Infernus102** [comment]
how to reproduce?

**Comment by Misteboss** [comment]
just use your code and spawn in a level where there is a tile -__- @Infernus102

**Comment by Infernus102** [comment]
Doesn't happen to me! idc revert it then

**Comment by thebigsmileXD** [comment]
Fix maybe with new chunk formats

**Comment by thebigsmileXD** [comment]
Seems fixed.

**Comment by Misteboss** [comment]
Isn't fixed. @SuperMaXAleX @thebigsmileXD

**Comment by thebigsmileXD** [comment]
Now? https://github.com/H4PM/Elywing/commit/291a66eb0d0acb8ea4dfe1dfefb86684ff24d332
