### ISSUE TITLE
EntityMoveEvent on Ghast's doesn't work

### ISSUE THREAD

**Issue by sero583** [H4PM/Elywing#284]
Spawn a Ghast let it move, the EntityMoveEvent will do nothing.

**Comment by Driesboy** [comment]
there is no mob AI

**Comment by sero583** [comment]
@Driesboy There actually is for ghasts an undone one, it keeps flying around. Test it yourself, anyways I closed that issue because I didn't noticed the deprecated message at the load and wondered why it isn't working.

**Comment by thebigsmileXD** [comment]
The mob ai replaces the Ghast with example: mobghast/EntityGhast
