### ISSUE TITLE
[POLL] Merge Tesseract Team and Elywing

### ISSUE THREAD

**Issue by remotevase** [H4PM/Elywing#285]
I propose that the TesseractTeam who are working on Tesseract join together with the H4PM team who are working on Elywing and create one amazing software. Since I am a member of the Tesseract Team, I think that members of both teams should talk [here](https://github.com/TesseractTeam/Tesseract/issues/100), as I am the one who is creating this proposal.

**Comment by LamKietCrack** [comment]
;)

**Comment by RateekMCPE** [comment]
Yes :)

**Comment by thebigsmileXD** [comment]
I know tesseract a bit. Its almost same proceeing like this core..

**Comment by remotevase** [comment]
Okay, like I said before, lets talk in the tesseract issue [here](https://github.com/TesseractTeam/Tesseract/issues/100)
