### ISSUE TITLE
DevTools

### ISSUE THREAD

**Issue by AndreySK4** [H4PM/Elywing#286]
The plugin DevTools from [github.com/H4PM/DevTools](url) doesn't load
![_20170104_103854](https://cloud.githubusercontent.com/assets/17062704/21636485/9527504a-d26b-11e6-96a4-5079b50bd66a.JPG)

**Comment by thebigsmileXD** [comment]
https://github.com/H4PM/Elywing-DevTools/blob/master/plugin.yml#L4

**Comment by Infernus102** [comment]
Nice cat @thebigsmileXD

**Comment by thebigsmileXD** [comment]
The one of my stepbrother. The other cat loves me more though:
![image](https://cloud.githubusercontent.com/assets/8733998/21637196/2ae8bb74-d266-11e6-83e2-122755ff5bab.png)

**Comment by Infernus102** [comment]
Lol

**Comment by thebigsmileXD** [comment]
wolvesfortress.de/DevTools3_v1.11.0.zip
