### ISSUE TITLE
Gamemode doesn't update upon login

### ISSUE THREAD

**Issue by TheAppleGamer** [H4PM/Elywing#29]
Pretty much if you relog in Gamemode 1, it will respawn you back in gamemode 1, but it acts like survival, and doesnt put you back in gamemode 1 unless you do /gamemode 0 and then /gamemode 1.

**Comment by Muqsit** [comment]
Is force gamemode off?

**Comment by TheAppleGamer** [comment]
Yes

**Comment by SuperMaXAleX** [comment]
It's maybe a problème with Gamemode detection on the packet AdventureSetting or GameStartPacket @Muqsit

**Comment by flaxues** [comment]
https://github.com/pmmp/PocketMine-MP/commit/d6fcc59a496267eb643bdd4e1a062beab94ce20d ?

**Comment by MCPEGamerJPatGitHub** [comment]
That is an issue on Genysis and PMMP for quite a while

**Comment by ImagicalGamer** [comment]
Possible an issue with SetPlayerGameTypePacket?

**Comment by Enzoomet** [comment]
Hey,

To fix this, you must have force-gamemode set to "on", otherwise, your builders/players would have to set their gamemode to survival (even if they already are in survival) and then set their gamemode to creative.

**Comment by TheAppleGamer** [comment]
UPDATE @SuperMaXAleX and all others, I've got a fix for it.
