### ISSUE TITLE
[Offer] Do you want to make new web?

### ISSUE THREAD

**Issue by ondraczsk** [H4PM/Elywing#292]
I create web for you, like nukkit.io. You can choose design from html5up.net and i make the web.You have to say what is in there has to be

Hosting: On my vps: Web ( elywing.tk )
              Or free hosting-hostinger.cz Web ( elywing.esy.es )

My work: clearskybeta.esy.es
                atgames.tk

Sorry for my english

Of course, all is free :D

**Comment by Driesboy** [comment]
can you host my server?

**Comment by ondraczsk** [comment]
Yes, i can send you files of web and you can upload it on your server

**Comment by ondraczsk** [comment]
so what

**Comment by ondraczsk** [comment]
@Driesboy and you can choose template from this https://pixelarity.com

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/21646938/92d87b8e-d298-11e6-8b2e-60e5bedc2334.png)

GG xD

**Comment by ondraczsk** [comment]
thats not my web
 try atgames.tk thats is my web

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/21647166/6e72e2b0-d299-11e6-8bc2-b97842dcf30a.png)

You just said its yours.

**Comment by ondraczsk** [comment]
yes

**Comment by thebigsmileXD** [comment]
So, lying?

**Comment by ondraczsk** [comment]
no, the windows said bad protocol, on chrome browser working good

**Comment by ondraczsk** [comment]
my english is horrible :D

**Comment by thebigsmileXD** [comment]
@ondraczsk no you just didnt do http:// for that link on the cs site

**Comment by ondraczsk** [comment]
@Driesboy sorry, so do you want the website or no

**Comment by ondraczsk** [comment]
hm?

**Comment by thebigsmileXD** [comment]
I think this fork of pm is pretty unknows, a web may work good

**Comment by thebigsmileXD** [comment]
Yes

**Comment by ondraczsk** [comment]
ok im going to make website but choose the template

**Comment by thebigsmileXD** [comment]
Solid State and https://html5up.net/helios are cool

**Comment by ondraczsk** [comment]
so solid state or helios :D?

**Comment by ondraczsk** [comment]
and tell me website content

**Comment by ondraczsk** [comment]
tell

**Comment by ondraczsk** [comment]
are you there @thebigsmileXD

**Comment by thebigsmileXD** [comment]
Stop spamming or i'll report you to GitHub.

**Comment by ondraczsk** [comment]
ok, just tell the template and the site content

**Comment by isoz** [comment]
Free webhost? Free domain? Free templates? Sorry for my english?
What can go wrong...

**Comment by ondraczsk** [comment]
if you want paid domain, buy it
i have bad english teacher, what can i do with her?
Free templates is good, if you want paid template, buy it.

Look on my work: atgames.tk
Good?

**Comment by thebigsmileXD** [comment]
Rape her

**Comment by ondraczsk** [comment]
-_- so, Pls tell... do you want the website? yes, i make it no, i close this offer
because you dont saying anything about it
you say

> rape her

**Comment by ondraczsk** [comment]
ok so you don't want website, ok ok
