### ISSUE TITLE
Cannot die.

### ISSUE THREAD

**Issue by Xelcronia** [H4PM/Elywing#293]
After the b9fc0c6 commit, when someone dies their game freezes instead of dying forcing them to relog.

And when I do /kill I get this error too

```
09:33:57 | Elywing thread:CRITICAL > Unhandled exception executing command 'kill' in kill: Call to undefined method pocketmine\level\Level::spawnXPOrb()
09:33:57 | Elywing thread:CRITICAL > Error: "Call to undefined method pocketmine\level\Level::spawnXPOrb()" (EXCEPTION) in "/src/pocketmine/Player" at line 4044
```

**Comment by thebigsmileXD** [comment]
Yes. i need to revert more shit committed before

**Comment by thebigsmileXD** [comment]
Try now.

**Comment by Xelcronia** [comment]
Nope, still the same.

**Comment by thebigsmileXD** [comment]
weird i dont have that

**Comment by Xelcronia** [comment]
![image](https://cloud.githubusercontent.com/assets/18191745/21653331/90dd3390-d2d6-11e6-97bb-56d9dd118c41.png)

**Comment by Driesboy** [comment]
Only on windows?

**Comment by Xelcronia** [comment]
On my other server running Ubuntu too

**Comment by Xelcronia** [comment]
Another bug, If I write and place a sign, other players see that sign as an empty sign. And if I relog, those signs disappear

**Comment by Driesboy** [comment]
thats a bug thats reported my me

**Comment by Xelcronia** [comment]
Oh Cool

**Comment by Driesboy** [comment]
#208

**Comment by Xelcronia** [comment]
Weird, signs used to work before CLElywing update.

**Comment by thebigsmileXD** [comment]
@Driesboy the question 'Only on Windows' is stupid. as long as its no binary error, its core independ software.

**Comment by Xelcronia** [comment]
@thebigsmileXD Thanks for fixing the death bug! Can you please have a look into the sign bug please?

`Xelcronia commented 20 hours ago
Another bug, If I write and place a sign, other players see that sign as an empty sign. And if I relog, those signs disappear`

**Comment by thebigsmileXD** [comment]
@Xelcronia Learn to seperate issues from each other.

**Comment by thebigsmileXD** [comment]
@Xelcronia use the already existing sign issue. Thanks.

**Comment by Xelcronia** [comment]
Alright.
