### ISSUE TITLE
Since the last update, Nemisys is no longer working

### ISSUE THREAD

**Issue by Henning-Klatt** [H4PM/Elywing#295]
If a player is teleported from Synapse Client to Synapse Client, the following error occurs and the teleport process is aborted:

`15:17:17 | Elywing thread:CRITICAL > "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'SlaveServer v1': Undefined class constant 'DIMENSION_NORMAL' on SlaveServer\Main
15:17:17 | Elywing thread:CRITICAL > Error: "Undefined class constant 'DIMENSION_NORMAL'" (EXCEPTION) in "/plugins/SynapsePM/src/synapse/Player" at line 285`

When I look at the error message, it looks like a SynapsePM error, but the SynapsePM plugin has not changed since the last Elywing update.

Hope you can fix it guys!

**Comment by Henning-Klatt** [comment]
Here is the exactly error, Maybe it helps:

`15:17:17 | Elywing thread:DEBUG > #0 /plugins/SlaveServer/src/SlaveServer/Main(665): SlaveServer\Main->teleportToServer(synapse\Player Player(1), string SW-Prison)
15:17:17 | Elywing thread:DEBUG > #1 /src/pocketmine/plugin/MethodEventExecutor(36): SlaveServer\Main->onInteract(pocketmine\event\player\PlayerInteractEvent object)
15:17:17 | Elywing thread:DEBUG > #2 /src/pocketmine/plugin/RegisteredListener(96): pocketmine\plugin\MethodEventExecutor->execute(SlaveServer\Main object, pocketmine\event\player\PlayerInteractEvent object)
15:17:17 | Elywing thread:DEBUG > #3 /src/pocketmine/plugin/PluginManager(704): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerInteractEvent object)
15:17:17 | Elywing thread:DEBUG > #4 /src/pocketmine/level/Level(1637): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerInteractEvent object)
15:17:17 | Elywing thread:DEBUG > #5 /src/pocketmine/Player(2433): pocketmine\level\Level->useItemOn(pocketmine\math\Vector3 Vector3(x=193,y=12,z=25), pocketmine\item\ItemBlock Item Air (0:0)x0, integer 3, double 0.58120727539062, double 0.46784782409668, double 0.125, synapse\Player Player(1))
15:17:17 | Elywing thread:DEBUG > #6 /plugins/SynapsePM/src/synapse/Player(319): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\UseItemPacket object)
15:17:17 | Elywing thread:DEBUG > #7 /src/pocketmine/network/Network(250): synapse\Player->handleDataPacket(pocketmine\network\protocol\UseItemPacket object)
15:17:17 | Elywing thread:DEBUG > #8 /src/pocketmine/Player(2203): pocketmine\network\Network->processBatch(pocketmine\network\protocol\BatchPacket object, synapse\Player Player(1))
15:17:17 | Elywing thread:DEBUG > #9 /plugins/SynapsePM/src/synapse/Player(319): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\BatchPacket object)
15:17:17 | Elywing thread:DEBUG > #10 /plugins/SynapsePM/src/synapse/Synapse(260): synapse\Player->handleDataPacket(pocketmine\network\protocol\BatchPacket object)
15:17:17 | Elywing thread:DEBUG > #11 /plugins/SynapsePM/src/synapse/network/SynapseInterface(111): synapse\Synapse->handleDataPacket(pocketmine\network\protocol\BatchPacket object)
15:17:17 | Elywing thread:DEBUG > #12 /plugins/SynapsePM/src/synapse/network/SynapseInterface(82): synapse\network\SynapseInterface->handlePacket(string ..."U..<g.$Dr;.|^.2../x.c.abPTnb.1rac8%b...........'......W.:r0.....G)
`

**Comment by thebigsmileXD** [comment]
Re-try

**Comment by thebigsmileXD** [comment]
Ah note: dimension removed
