### ISSUE TITLE
TODO since @291a66eb0d0acb8ea4dfe1dfefb86684ff24d332

### ISSUE THREAD

**Issue by erkam2002** [H4PM/Elywing#296]
Destroyblock particle will not shown

Nemisys dont work

**Comment by thebigsmileXD** [comment]
So back. I reverted some more stuff. Sure, i am sorry about that. but right now its a WORKING, no messed up pull over.

**Comment by thebigsmileXD** [comment]
So, todo: re-add bossbar packet etc..

**Comment by Henning-Klatt** [comment]
Todo: Nemisys/SynapsePM support, It is exactly the same error as in this Issue:
https://github.com/H4PM/Elywing/issues/295

**Comment by thebigsmileXD** [comment]
@Henning-Klatt stop spamming it its a duplicate

**Comment by Henning-Klatt** [comment]
I fixed the SynapsePM Dimension issue myself, but after the teleport the player can not move, but he can look around. Besides, his hand is like crazy. This should be a new Elywing bug too?

**Comment by AppleDevelops** [comment]
fixed most of it
