### ISSUE TITLE
How can I use this Elywing? Anyone can help me use this software

### ISSUE THREAD

**Issue by CentOsDogE** [H4PM/Elywing#297]

**Comment by Driesboy** [comment]
same like pocketmine

**Comment by CentOsDogE** [comment]
I mean download and .phars ?

**Comment by thebigsmileXD** [comment]
theres only /src

**Comment by CentOsDogE** [comment]
nope im noobs. Pls teach me :P

**Comment by thebigsmileXD** [comment]
in general you set up pocketmine/pmmp and then replace the .phar with a scr

**Comment by thebigsmileXD** [comment]
https://github.com/pmmp/PocketMine-MP
have you set up this once?

**Comment by CentOsDogE** [comment]
yes ?

**Comment by thebigsmileXD** [comment]
do you have a working server with https://github.com/pmmp/PocketMine-MP?

**Comment by CentOsDogE** [comment]
nope :)

**Comment by thebigsmileXD** [comment]
If so just delete the pmmp .phar file

**Comment by CentOsDogE** [comment]
Okay Thanks for help me 🗡

**Comment by thebigsmileXD** [comment]
say and then you download this software and in the same folder where the server.properties is you put the src folder

**Comment by CentOsDogE** [comment]
Thanks 👍

**Comment by thebigsmileXD** [comment]
Welcome! Have fun!
