### ISSUE TITLE
Button click sound dont work

### ISSUE THREAD

**Issue by Driesboy** [H4PM/Elywing#299]
undefinded class contstant 'event_sound_button_click'" (expection) in "/src/pocketmine/level/sound/ButtonClick sound"
or is the api changed

**Comment by thebigsmileXD** [comment]
Yes changed

**Comment by Driesboy** [comment]
Whats new?

**Comment by thebigsmileXD** [comment]
by read code xD

**Comment by Driesboy** [comment]
Lel but Explain how

**Comment by thebigsmileXD** [comment]
Well you open you favourite browser, type in https://github.com/H4PM/Elywing, then you go to /src then /pocketmine/level  then look in the sounds and events

**Comment by Driesboy** [comment]
are you kidding me?

**Comment by thebigsmileXD** [comment]
> And how i can fix it

>Lel but Explain how

are YOU kidding ME?

**Comment by thebigsmileXD** [comment]
Fixed
