### ISSUE TITLE
Installation du software.

### ISSUE THREAD

**Issue by GamingPilot2** [H4PM/Elywing#3]
Bonjour !
Je souhaite installer votre software sur mon serveur mais je ne trouve pas comment faire, pouvez-vous me donner le .phar de votre software ?

Merci d'avance,
GamingPilot2.

> Owner of @LifeCubePE_ & CM of @LifeCubePE_

**Comment by Pab450** [comment]
Etape à suivre pour launch le software Elewing : 
1- télécharger le dossier Elewing.
2- ouvrir le dossier SRC du dosser Elewing.
3- prendre les dossiers nommés "spl" et "pocketmine".
4- déplacer ses deux dossier dans votre software.
5- placer les deux dossiers à la place des dossiers "pocketmine" et "spl" qui se trouve dans SRC.

**Comment by GamingPilot2** [comment]
vas y c'est'bien trop compliqué

**Comment by Pab450** [comment]
vous avez eux les réponses à vos questions, close !

**Comment by GamingPilot2** [comment]
peux avoir explication plus clair ?
