### ISSUE TITLE
Not die fall to void

### ISSUE THREAD

**Issue by andris155** [H4PM/Elywing#300]
`04.01 21:28:20 [Server] CRITICAL Could not tick level "kitpvp2": Call to undefined method pocketmine\level\Level::spawnXPOrb()`
Elywing killed skypvp servers. :(

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=czdix7eiu4U

**Comment by Xelcronia** [comment]
#293

**Comment by thebigsmileXD** [comment]
Confirmed.

**Comment by Infernus102** [comment]
Could not tick level "lobby": Class pocketmine\level\ExperienceOrb not found

**Comment by thebigsmileXD** [comment]
Fixed.
