### ISSUE TITLE
Remove Anti-Fly and Movement Checks?

### ISSUE THREAD

**Issue by AppleDevelops** [H4PM/Elywing#310]
Anticheat should be handled by plugins not the server. Removing Anti-Fly and the movement checks should fix some of the issues. I could always remove those but I want to see if it is necessary first.

**Comment by TDMidkwhatisxd** [comment]
No! Ppl use other server software becouse da new devs on PmmP plan to remove them ;-;

**Comment by TDMidkwhatisxd** [comment]
If u ever do that i quit elywing! And will try to make a copy/paste spoon! Just the effort of copy/paste is too big for me so dont do that ;-;

**Comment by TDMidkwhatisxd** [comment]
Btw, u can remove anti-fly!

**Comment by EpicSteve33** [comment]
I think Movement Checks should not be removed but I agree anti-fly should be removed and handled but plugins

**Comment by thebigsmileXD** [comment]
I think it should atleast + only be removed for elytra.

**Comment by AppleDevelops** [comment]
I only hose to remove it because of elytra and besides this is the worst anti fly I've seen

**Comment by EpicSteve33** [comment]
well the elytra in my opinion is not that important but I agree the antifly is pretty bad it should be removed
