### ISSUE TITLE
This needs any File hosting site

### ISSUE THREAD

**Issue by starterdragon** [H4PM/Elywing#312]
This software needs any file hosting / cloud server...
Even Dropbox, MediaFire, ZippyShare, Mega .. etc..

for .phars because not everyone can phar..

just a suggestion, because as you can see. Some server owners might choose to use this instead of other Softwares, because @thebigsmileXD is on the project XD

**Comment by Seshpenguin** [comment]
I don't mind providing hosting services

**Comment by thebigsmileXD** [comment]
You can run from SRC and use tutorials from pmmp. Devtools 3 is linked in another issue.
