### ISSUE TITLE
Dragon egg crash my server.

### ISSUE THREAD

**Issue by Iktaniyalol** [H4PM/Elywing#316]
Elywing Crash Dump Wed Jan 4 19:32:18 MSK 2017

Error: syntax error, unexpected '<<' (T_SL), expecting function (T_FUNCTION)
File: /src/pocketmine/block/DragonEgg
Line: 36
Type: notice

Code:
[27] use pocketmine\item\Item;
[28] 
[29] class DragonEgg extends Fallable {
[30] 
[31] 	protected $id = self::DRAGON_EGG;
[32] 
[33] 	public function __construct(){
[34] 
[35] 	}
[36] <<<<<<< HEAD
[37] 
[38] 	public function getName() : string{
[39] =======
[40] 	public function getName(){
[41] >>>>>>> 291a66eb0d0acb8ea4dfe1dfefb86684ff24d332
[42] 		return "Dragon Egg";
[43] 	}
[44] 
[45] 	public function getHardness() {
[46] 		return 3;

Backtrace:
#0 /src/pocketmine/block/Block(263): spl_autoload_call(string pocketmine\block\DragonEgg)
#1 /src/pocketmine/Server(1873): pocketmine\block\Block::init(boolean)
#2 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/sftpmine/mine/ram1024/, string /home/sftpmine/mine/ram1024/, string /home/sftpmine/mine/ram1024/plugins/, string unknown)

Genisys version: 8f465763c590293e2003ce616832b6507edf5b1c [Protocol 100; API 3.0.0-ALPHA1]
uname -a: Linux wrewolf.com 2.6.32-042stab117.14 #1 SMP Tue Aug 30 17:12:57 MSK 2016 x86_64
PHP version: 7.0.9
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 0 seconds
Number of loaded worlds: 0
Players online: 0/100

Loaded plugins:

...
Crashdump is very strange.

**Comment by TDMidkwhatisxd** [comment]
Btw! Is a syntax error, you can fix it yourself 😊

**Comment by Iktaniyalol** [comment]
I will have to wait for the server maker. Thank you

**Comment by starterdragon** [comment]
I have the latest elywing... don't got any problem on dragon egg.. which in fact I have some Dragon Egg as design on my spawn/lobby

**Comment by Iktaniyalol** [comment]
I dont know, what is happened

**Comment by thebigsmileXD** [comment]
@TDMidkwhatisxd The DragonEgg mess was 100% reverted. Check commits before talking _stupidity_.

**Comment by thebigsmileXD** [comment]
https://github.com/H4PM/Elywing/blob/master/src/pocketmine/block/DragonEgg.php

You have to update your server.

**Comment by TDMidkwhatisxd** [comment]
Elywing will fail 100%! You are destroying everything! Im out ! 😑

**Comment by TDMidkwhatisxd** [comment]
Ignore!
