### ISSUE TITLE
A Theoretically block completely crash and force close Clients on chunk load

### ISSUE THREAD

**Issue by starterdragon** [H4PM/Elywing#317]
I have my world since 0.16 and got builds until pmmp 1.0... during that time, the area (where client crash) on my server is fine.. but when I changed to Elywing.. that's the only and first problem I noticed and got... I think it is cactus in a pot.. since:

- Elywing is fork from Genisys (which during 0.16.0 I got the same issue)
- The area is the only place where we can find cactus on pot which Builders used as design..

temporary solution (removed the pot)...

**Comment by thebigsmileXD** [comment]
Place pot somewhere else and check if it still happens.

**Comment by starterdragon** [comment]
@thebigsmileXD can't place cactus on pot with Elywing..

**Comment by starterdragon** [comment]
plus bonus issue XD ... Sealanterns don't produce light after chunk unload

**Comment by thebigsmileXD** [comment]
Yes, sea lanterns are'nt coded as light source. open a seperate issue.

**Comment by starterdragon** [comment]
I'll try to make a new world, then copy the region of that world to the new one just to see if it is caused by/affected by pmmp's customanvil/customregion/chunk loader since I first used pmmp.

**Comment by thebigsmileXD** [comment]
try again

**Comment by starterdragon** [comment]
![image](https://cloud.githubusercontent.com/assets/16812043/21719145/134d8826-d457-11e6-8405-754ccb2566a5.png)
Please check these nbt tags and/or byte... even MCEdit got a problem

**Comment by thebigsmileXD** [comment]
MCEdit isnt compatible with pm worlds. the code just changed
