### ISSUE TITLE
Sign dont save and lost when reconnecting

### ISSUE THREAD

**Issue by Iktaniyalol** [H4PM/Elywing#318]
I wanted to put a sign with  shop but it does not work.I decided to check whether the sign work.when i rejoin to server, sign is not visible. Who has the same? Maybe it's me that something is wrong.

**Comment by starterdragon** [comment]
This also happen on my end

**Comment by thebigsmileXD** [comment]
Duplicate. Learn to search issues before you create new ones. https://github.com/H4PM/Elywing/issues/212
