### ISSUE TITLE
The problem with spoons

### ISSUE THREAD

**Issue by JackNoordhuis** [H4PM/Elywing#32]
I see this time and time again; people are uploading someone else's projects, giving them a new name and not giving proper credit. You should've at least given them credit and [imported the commit history from Genisys, it really isn't that hard.](https://help.github.com/articles/duplicating-a-repository/) I fail to see why it is so hard to give someone credit for something they've spent many hours contributing to. I'm pretty sure anyone who has contributed to this fork/spoon would be up in arms if someone else did the same thing to this repo.

However this is just my two cents on the matter, feel free to close the issue or ban me from your org, I'm just trying to get a point across that you'll hopefully understand one day.

**Comment by Muqsit** [comment]
https://github.com/H4PM/Elywing/commit/ec189e0953461f097cbb0231573595fbed8464bc
