### ISSUE TITLE
setExecutor() on null

### ISSUE THREAD

**Issue by Driesboy** [H4PM/Elywing#320]
what is changed?

**Comment by Driesboy** [comment]
all the plugins that use that dont work enymore

**Comment by Driesboy** [comment]
plugins like Mspawns, CunstomAlert & broadcaster

**Comment by thebigsmileXD** [comment]
Confirmed.. i am searching since 15 minutes

**Comment by andris155** [comment]
same problem
`2017-01-07 12:56:10 | Elywing thread:CRITICAL > Error: "Call to a member function setExecutor() on null" (EXCEPTION) in "/plugins/NoAdvertisingPE-master/src/Vaivez66/NoAdvertisingPE/NoAdvertising" at line 21`
`2017-01-07 12:56:10 | Elywing thread:CRITICAL > Error: "Call to a member function setExecutor() on null" (EXCEPTION) in "/plugins/SA/src/ServerAuth/ServerAuth" at line 299`

**Comment by thebigsmileXD** [comment]
Fixed 👍 🗡 💃
