### ISSUE TITLE
Error [Spam in console]

### ISSUE THREAD

**Issue by AndreySK4** [H4PM/Elywing#321]
My console is spammed with this error:
![_20170106_154121](https://cloud.githubusercontent.com/assets/17062704/21719508/e63f2d4c-d426-11e6-85c9-e31df65b83ff.JPG)

**Comment by thebigsmileXD** [comment]
I'll recheck but i think its sth else

**Comment by caspervanneck** [comment]
@AndreySK4 @thebigsmileXD #323

**Comment by thebigsmileXD** [comment]
I see who now messed up -.-

**Comment by thebigsmileXD** [comment]
Well its a duplicate now.
