### ISSUE TITLE
you cannot eat

### ISSUE THREAD

**Issue by Driesboy** [H4PM/Elywing#322]

**Comment by thebigsmileXD** [comment]
Todo

**Comment by Chris-Prime** [comment]
ATTENTION PLEASE

**Comment by thebigsmileXD** [comment]
@Driesboy any errors? Provide errors if given.

**Comment by thebigsmileXD** [comment]
Next time please Error codes. Thanks

**Comment by Driesboy** [comment]
No errors

**Comment by Chris-Prime** [comment]
Approved. Same happens with current code.

**Comment by thebigsmileXD** [comment]
@Driesboy I got 'unknown function item/Effect'

**Comment by Driesboy** [comment]
im wil test it
wait

**Comment by thebigsmileXD** [comment]
Its already fixed, no need to test.

**Comment by Driesboy** [comment]
k
