### ISSUE TITLE
Weather bug > undefined method

### ISSUE THREAD

**Issue by FerroDump** [H4PM/Elywing#326]
> Error: "Call to undefined method pocketmine\level\Level::getWeather()" (EXCEPTION) in "/src/pocketmine/command/defaults/WeatherCommand" at line 90

**Comment by thebigsmileXD** [comment]
Confirmed, weather is gone for now because of need for rewrite

**Comment by thebigsmileXD** [comment]
I just check if i can re-add the functions for now

**Comment by thebigsmileXD** [comment]
Re-added.
