### ISSUE TITLE
the server does not start

### ISSUE THREAD

**Issue by ProCOmpTEAM** [H4PM/Elywing#327]
**Elywing thread:CRITICAL > ParseError: "syntax error, unexpected 'const' (T_CONST), expecting ',' or ';'" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 106**

![default](https://cloud.githubusercontent.com/assets/24737193/21732485/c4f113e6-d46a-11e6-9ec1-09e5548357e8.PNG)

**Comment by ProCOmpTEAM** [comment]
I'm fixed this: they forgot ;
https://github.com/H4PM/Elywing/commit/5f2a8378416efe955b98aa81876396ca2481a222

**Comment by Aericio** [comment]
#328

**Comment by thebigsmileXD** [comment]
@Aericio correct.
