### ISSUE TITLE
Elytra in Survival Mode

### ISSUE THREAD

**Issue by AnkitM252** [H4PM/Elywing#331]
Elytra only works in creative mode but doesn't work in survival mode. It shows animation but fall straight down.

**Comment by Driesboy** [comment]
anticheat?

**Comment by ankitmaharjan252** [comment]
nope!

**Comment by thebigsmileXD** [comment]
i think yes. Its the anti-fly. Weird. i didnt have the issue. i only died on touching ground xD

**Comment by ankitmaharjan252** [comment]
Ohh so anti cheat is blocking it? Can you glide without anticheat? I straight fall down and died..

**Comment by ankitmaharjan252** [comment]
I got it, how to fix it... Peoples having the same problem will get solution so i'll post here how i fix it

Simply Change anti-fly in genisys.yml to false and boom you are done.

**Comment by thebigsmileXD** [comment]
I'll add a proper thing

**Comment by ankitmaharjan252** [comment]
okay!
