### ISSUE TITLE
DroppedItem probably registered incorrectly

### ISSUE THREAD

**Issue by LordJoshie** [H4PM/Elywing#332]
Drop Entities / Throwables not showing. They're invisible. 

Break a block, or drop a block... nothing shows.

**Comment by thebigsmileXD** [comment]
check back please.. i am not sure if fixed and cant test now

**Comment by ZacharySims** [comment]
Fixed for Win10 however it will occasionally bug and then you'll be left with just the shadow. Still nonworking for Pocket Edition (Phones and Tablets) however.

**Comment by thebigsmileXD** [comment]
Weird. Because PE and Win10 call the same code.

**Comment by ZacharySims** [comment]
Quite. I can provide photos of both if that helps?

**Comment by thebigsmileXD** [comment]
yes, maybe even a video

**Comment by AppleDevelops** [comment]
@LordJoshie Not sure if it's that though. I got it working on my stuff. @thebigsmileXD Try removing the : array on getDrops() in Player.php it fixed it for me.

**Comment by AppleDevelops** [comment]
fixed
