### ISSUE TITLE
SimpleAuth v 1.7.2 no longer works

### ISSUE THREAD

**Issue by HiggsInc** [H4PM/Elywing#342]
Hi,

Tried to update my server with the latest release 
https://github.com/H4PM/Elywing/commit/b5d374f19240baf52bfe4aed1514c4d4c0552cc8

Ive discovered 2 plugins that no longer work. Broadcaster and SimpleAuth v1.7.2
Please advise?

i've rolled back to a previous server version where these plugins now function.

**Comment by Chris-Prime** [comment]
Approved. ServerAuth as well. But I fixed that by calling ServerCommandMap::getCommand() instead of PluginBase::getCommand()

**Comment by thebigsmileXD** [comment]
Duplicate of #320

**Comment by thebigsmileXD** [comment]
Learn searching issues. Thanks
