### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by skrafty** [H4PM/Elywing#344]
Sorry to post here I wasn't sure where to gain more information.  I'm interested in using Elywing but I'm not sure if there is a proxy like bungee I could use to switch to other servers.  Any help would be greatly appreciated.  If there is a better place for this question please advise.

Thanks!

**Comment by VoliPlays** [comment]
Hi you can use nemisys for more help contact me on serbanvalentin2003@gmail.com

**Comment by skrafty** [comment]
Thank you.  I emailed you.

**Comment by skrafty** [comment]
Hi VoliPlays,
I sent you a few emails but haven't heard back.  If you have a moment I would really appreciate your assistance on getting Elywing and Nemisys to work together.  Thanks!
