### ISSUE TITLE
Blocks that need tiles but got none go invisible

### ISSUE THREAD

**Issue by thebigsmileXD** [H4PM/Elywing#345]

**Comment by daniktheboss** [comment]
Lol

**Comment by Driesboy** [comment]
Some chest or all?

**Comment by thebigsmileXD** [comment]
hm, not sure. it could be caused by chests without tiles.

**Comment by KennFatt** [comment]
Sign are not working now, please revert @Muqsit  update about him commit related to sign. :(

**Comment by AppleMinerHD** [comment]
Yea thats a huge Bug ....
