### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by HittmanA** [H4PM/Elywing#346]
Everytime I do `./start.sh` it says 
```
php is /usr/bin/php
[CRITICAL] You must use PHP >= 7.0
[CRITICAL] Please use the installer provided on the homepage.
```
What do I need to do to install it via the start.sh file?

**Comment by Driesboy** [comment]
update your bin

**Comment by Chris-Prime** [comment]
Try doing
```
git clone https://github.com/PrimusLV/PM-Installer
./PM-Installer/pmInstall.sh -t "Elywing Server" -g https://github.com/H4PM/Elywing.git
```

**Comment by HittmanA** [comment]
If possible I would like to do it through the start.sh

**Comment by HittmanA** [comment]
also @Driesboy I did just update my php to to php7

**Comment by thebigsmileXD** [comment]
https://github.com/H4PM/Elywing/issues/297
https://github.com/H4PM/Elywing/issues/163
https://github.com/H4PM/Elywing/issues/232

**Comment by HittmanA** [comment]
thx

**Comment by thebigsmileXD** [comment]
Welcome
