### ISSUE TITLE
USELESS

### ISSUE THREAD

**Issue by Chris-Prime** [H4PM/Elywing#347]
This spoon is useless for survival! I had to fix many things myself.
+ Crafting is buggy as fuck
+ Language messages are messed up
+ When enchanting items get thrown out not enchanted
+ Mobs lag on knockback
+ No limit for how much mobs can spawn around spawner
+ Item frames dont update instantly only on chunk load
And many other stuff, so, don't create spoons which are more horrible than original. Thank you

**Comment by thebigsmileXD** [comment]
Create one yourself, good luck :)
