### ISSUE TITLE
Add/Fix EndRod placement

### ISSUE THREAD

**Issue by starterdragon** [H4PM/Elywing#348]
Vanilla like behaviour of End Rod (for parkour and design usage) @thebigsmileXD @XenialDan

**Comment by thebigsmileXD** [comment]
Attach on wall etc? Oh shit.. i remember MC being like.. place end rod on end rod and its blue end is the other side

**Comment by starterdragon** [comment]
and place on ceiling :rofl:

**Comment by thebigsmileXD** [comment]
Were done ages ago
