### ISSUE TITLE
Re-add Boss Packet

### ISSUE THREAD

**Issue by ItzWalla** [H4PM/Elywing#349]
The wither hud does not load in and it creates this error.

IMAGE :  ![img_3399](https://cloud.githubusercontent.com/assets/20291307/21745612/87f7a426-d4e4-11e6-9cee-9b116a2ec3c0.PNG)

**Comment by thebigsmileXD** [comment]
Use https://github.com/thebigsmileXD/BossBarAPI for example. Well, thats the problems when plugin coders dont think about the core might not having the file

**Comment by ItzWalla** [comment]
Ok, thank you! @thebigsmileXD
