### ISSUE TITLE
YouAre1ame's View on Elywing:

### ISSUE THREAD

**Issue by youare1ame** [H4PM/Elywing#35]
YOU ARE LAME FOR STEALING PROJECTS.

**Comment by youare1ame** [comment]
YOU JUST WANT THE FAME

**Comment by youare1ame** [comment]
YOU JUST WANT TO THINK YOU ARE BIG

**Comment by youare1ame** [comment]
YOU ARE ONLY DOING IT SO YOU CAN BE THE NEXT "IMAGICALMINE"

**Comment by youare1ame** [comment]
YOU ARE TO LAZY TO START FROM SCRATCH, WITH A LANGUAGE OTHER THAN PHP AND C# AND JAVA.

**Comment by youare1ame** [comment]
YOU DONT KNOW MUCH CODING, SO YOU STEAL OTHER'S

**Comment by SuperMaXAleX** [comment]
So why we created this ? :)
