### ISSUE TITLE
Signs gets invisible after leaving and going back to the world where they are

### ISSUE THREAD

**Issue by KillerXtream** [H4PM/Elywing#351]
Title is very descriptive..

Elywing 1.0
RHEL 7
MCWIN10 / MCPE on iOS 9.3.5
PHP 7.0.0

**Comment by EpicSteve33** [comment]
Signs are kinda broken I can't get signs to update for my games

**Comment by Infernus102** [comment]
@muqsit fixed this in the old elywing. Needs to be added again @thebigsmileXD

**Comment by thebigsmileXD** [comment]
#345
