### ISSUE TITLE
Break block particle not is work...

### ISSUE THREAD

**Issue by DKQoo2** [H4PM/Elywing#352]
that's all on the title

**Comment by xinghao2003** [comment]
hai，dk i am XingHao😂

**Comment by ankitmaharjan252** [comment]
What happen? You break a block and it doesn't break/replaces back with the same block?

Try this:
Remove all the plugins and restart or start the server

**Comment by DKQoo2** [comment]
@ankitmaharjan252 
Isn't that
I said its particle is disappear

**Comment by Infernus102** [comment]
reproduced and confirmed.

**Comment by ankitmaharjan252** [comment]
#296 Duplicate

**Comment by thebigsmileXD** [comment]
Weird though, i readded placing & breaking in a recent commit.

**Comment by AppleDevelops** [comment]
fixed
