### ISSUE TITLE
Hum sign, its me or.. ?

### ISSUE THREAD

**Issue by Pab450** [H4PM/Elywing#358]
>
#nofonctional1
public function onRun($tick){
if($this->plugin->getServer()->isLevelLoaded(language::pocketmine_level_name_plugin)){
$arg = "0";
$this->plugin->getLogger()->info("detect 1");
$count = count($this->plugin->getServer()->getLevelByName(language::pocketmine_level_name_plugin)->getPlayers());
$level = $this->plugin->getServer()->getLevelByName(language::pocketmine_level_name_default);
$tiles = $level->getTiles();
foreach($tiles as $t){
if($t instanceof Sign){ 
$text = $t->getText();
if($text[0]=="UHCRun"){
$this->plugin->getLogger()->info("detect 2");

detect 1 is okay ! but detect 2 is not functional (no error in console !)

#nofonctional2

"Call to a member function getText() on null" (EXCEPTION) in "/plugins/UHCRun/src/UHCRun/UHCRun" at line 777

777 = if($event->getPlayer()->getLevel()->getTile($event->getBlock())->getText()[0] == "UHCRun"){

hum getText() is not fonctional or im a noob dev x) ?

**Comment by thebigsmileXD** [comment]
> hum getText() is not fonctional or im a noob dev x) ?

I aint understood ANYTHING.
#14 #142 #208 #212 #218

**Comment by Pab450** [comment]
wtfff men x)
