### ISSUE TITLE
Chill on the commits

### ISSUE THREAD

**Issue by isoz** [H4PM/Elywing#359]
Dan is a very cool guy, I love him and hate him, but you guys need to chill on the commits, this is a production branch and many server owners with big servers came over to Elywing recently, you can't just push whatever you want and ruin the servers of other less experienced owners, for that you might want to make a developer branch or test branch.

So Dan preferred to push all the pmmp commits and whatever not and requests people to open issues as they show up, it should be the other way around, manually go one by one to make sure it doesn't break anything and then you fix the bugs. Joining the server and being able to connect does *not* mean it's not broken, have all the aspects in consideration, including breaking major plugins like SimpleAuth, like it did a few days ago.

Unfortunately all the commits after Dan joined bring in new problems and for the time being I can no longer use the latest versions.

Before you, yes you, the faggot that's typing right now say "The problems you have are all plugin related", yes, that might be true, but prior to this commits everything was working in harmony, you can't just pass the blame. 
"Blame PMMP", no, I'm going to blame you because I'm not using the official PMMP branch.
"If you don't like it then you can leave", that's great but I ain't going anywhere, learn to take criticism, the moment you accept taking on such project you should make sure you do it right.

**Comment by thebigsmileXD** [comment]
Remember: Elywinmg wasnt even joinable when i joined the project. You told me all this in private yesterday. Also not a real issue. I'll mark it as invalid for now but leave it unlocked for conversation, or you head over to #296

**Comment by isoz** [comment]
What are you talking about? Elywing was the only working spoon out of the bunch, are you insane?

**Comment by thebigsmileXD** [comment]
How weird

I was not able to join the server at all due to infinite client crashes

**Comment by isoz** [comment]
I never crashed, my server has been steadily handling 250+ clients online every day without any reports of crashes, until those commits happened.

**Comment by TDMidkwhatisxd** [comment]
Same, @thebigsmileXD  ruined elywing! I have some spare old elywing builds, who wanna a piece of cake? Xd

**Comment by thebigsmileXD** [comment]
Should i leave and you learn git finally?

**Comment by TDMidkwhatisxd** [comment]
No!
