### ISSUE TITLE
/give dont work correctly

### ISSUE THREAD

**Issue by Driesboy** [H4PM/Elywing#360]
give yourself a egg or snowball or enderpearl 
a item that is max stackable on 16
he give you 64 of the items
then trow 1 egg and the count will be set to 15

**Comment by KillerXtream** [comment]
Reproduced

**Comment by thebigsmileXD** [comment]
How is it: are they x64 stacks in the hotbar or 4 times ×16?

**Comment by Driesboy** [comment]
no 1 time x64

**Comment by thebigsmileXD** [comment]
Please provide image right after command and right after using egg

**Comment by AppleDevelops** [comment]
fixed
