### ISSUE TITLE
some worlds crash the client 

### ISSUE THREAD

**Issue by mote166** [H4PM/Elywing#362]
I've noticed that some worlds with builds higher than 128 crash the client once the client tries to load them . im using the last elywing build (downloaded a few days ago) and heres the map so u can try to reproduce the issue :

http://www.mediafire.com/?8hsjdwuadh84dd4

**Comment by mote166** [comment]
also theres a heavy lag when breaking/placing blocks . ( i have a good network connection and a good ram ) .

**Comment by mote166** [comment]
also theres a glitch sometimes when u teleport to a world (skywars world) from the spawn some chunks from the spawn load in the skywars world .

**Comment by TDMidkwhatisxd** [comment]
If u crash in some worlds, this is becouse ppl build too much!
A part of my factions map crash android clients, but windows10 seems fine but if u stay there too long w10 crash too, weird! This happens wen you have too many chunks, from what i saw long ago in a issue tracker!

**Comment by mote166** [comment]
but the map i gave is a skypvp map and has no much builds in it . every map i download never crash except skypvp maps , weird
