### ISSUE TITLE
Elywing (Sign Bug Doesn't save)

### ISSUE THREAD

**Issue by SirOptic** [H4PM/Elywing#363]
Hello, I been having an issue where signs won't save. For example, if I place a sign write a text editor out the server the sign will disappear.Theres another issue, I have tested on other forks, version 0.16.0 economy by onebone seem to work, but on Elywing 1.0 version it doesn't can you please fix economy or tell me how I can fix this?

**Comment by SirOptic** [comment]
Sorry I forgot to say the only thing, that isn't working for economy is shop signs and sell signs, and anything with economy (signs)

**Comment by SirOptic** [comment]
Sorry I forgot to say the only thing, that isn't working for economy is shop signs and sell signs, and anything with economy (signs)

**Comment by starterdragon** [comment]
spam

**Comment by thebigsmileXD** [comment]
Duplicate 9000+. Learn to search. Spamer
