### ISSUE TITLE
itemframe bug

### ISSUE THREAD

**Issue by oxxydev** [H4PM/Elywing#364]
wtf?!? 

21:03:13 | Elywing thread:CRITICAL > Error: "Call to undefined method pocketmine\tile\ItemFrame::onChanged()" (EXCEPTION) in "/src/pocketmine/tile/ItemFrame" at line 73

**Comment by thebigsmileXD** [comment]
This was fixed in a pretty recent commit. Invalid

**Comment by xpyctum** [comment]
No. That not fixed. Reproduced.

**Comment by xpyctum** [comment]
No defined 
"""php
ItemFrame::onChanged():
"""

**Comment by AppleDevelops** [comment]
fixed
