### ISSUE TITLE
MobSpawner bug

### ISSUE THREAD

**Issue by starterdragon** [H4PM/Elywing#367]
04:55:02 | Elywing thread:CRITICAL > Could not tick level "lobby": Argument 1 passed to pocketmine\event\entity\EntityGenerateEvent::__construct() must be an instance of pocketmine\level\Position, instance of pocketmine\math\Vector3 given, called in phar://C:/Users/Administrator/Desktop/Frozen Lave Network/Elywing_1.0.phar/src/pocketmine/tile/MobSpawner.php on line 160

**Comment by TDMidkwhatisxd** [comment]
Elywing was destroyed by @thebigsmileXD ! And abandoned! This is why i dont accept help!

**Comment by thebigsmileXD** [comment]
@TDMidkwhatisxd do it better, without fucking up the git history on git cherry pick and without client crashes.. OH! i forgot, sorry. You noobs don't know how to use Git.

Also i already talked to @starterdragon about the issue in private and explicitely asked him to open an issue so i can fix, but somehow i don't want to because of your insult.

**Comment by TDMidkwhatisxd** [comment]
Why i care? You Ended elywing ! Congratulations!

**Comment by thebigsmileXD** [comment]
Go along and fix it instead to complain, kid. xD

**Comment by TDMidkwhatisxd** [comment]
How i know what you did? You just merged blindly some codes and now wanna help?

**Comment by thebigsmileXD** [comment]
Blindly, or with knowledge?

**Comment by thebigsmileXD** [comment]
You know what Elywing did? Corrupting my chunks and constantly crashing my client + Server. Well done 👍

**Comment by TDMidkwhatisxd** [comment]
What?! Elywing was stable before, just craft didnt work on Pe GUI !
Elywing dont support .mcr

**Comment by thebigsmileXD** [comment]
Wow.. I use mcr, anvil and pmanvil. All work.

**Comment by TDMidkwhatisxd** [comment]
So u did all this mess just for mcregion?!

**Comment by TDMidkwhatisxd** [comment]
Well, anyway, i will wait and see!

**Comment by thebigsmileXD** [comment]
*facepalm* yes, mcreqion only. Totally. To write in your grammar: You even READ?! Oh! U mess up elywing it my life

**Comment by TDMidkwhatisxd** [comment]
I dont know Git and im proud of it 😃

**Comment by Infernus102** [comment]
@starterdragon are you using the latest commit?

**Comment by AppleDevelops** [comment]
fixed
