### ISSUE TITLE
/enchant dont work

### ISSUE THREAD

**Issue by KnightOfEnder** [H4PM/Elywing#372]
/enchant won't work plus I need a anti cheat that won't block players flying but will block the use of spawning in items from toolbox and using drop button to dupes lots of that one item

**Comment by TDMidkwhatisxd** [comment]
http://s000.tinyupload.com/?file_id=00658674783989954536

Try this elywing and tell me if is fixed! Codename: Cookie. Xd

**Comment by TDMidkwhatisxd** [comment]
As for items hack! Check in genysis.yml if allow-cheats if false!

**Comment by KnightOfEnder** [comment]
The files say a unknowing error has occurred when using this command

**Comment by TDMidkwhatisxd** [comment]
Yes! 

Did you use this build?! It works really good for me!

**Comment by KnightOfEnder** [comment]
I will try it when server comes back online as still got the other problem I reported. I can show u the scripe that show when it happens 
![screenshot_2017-01-10-21-56-22](https://cloud.githubusercontent.com/assets/24853541/21850354/19273374-d802-11e6-8018-68b11d06f3d7.png)

**Comment by KnightOfEnder** [comment]
Where do I place the file from that link in plugins ? And.my cookies file call cookies.txt

**Comment by KnightOfEnder** [comment]
![screenshot_2017-01-11-16-20-55](https://cloud.githubusercontent.com/assets/24853541/21856469/0a4b438c-d81a-11e6-8525-b041cdc9e7a0.png)
This is what happens atm. When I try /enchant Night_Of_Ender sharpness 5 while holding a diamond sword

**Comment by KnightOfEnder** [comment]
![screenshot_2017-01-11-16-22-28](https://cloud.githubusercontent.com/assets/24853541/21856532/42d16fc4-d81a-11e6-9c11-49874f463527.png)

**Comment by TDMidkwhatisxd** [comment]
You place in server files! Not in plugins! Same folder were your pocketmine.yml is!

**Comment by AppleDevelops** [comment]
fixed
