### ISSUE TITLE
Server.properties 

### ISSUE THREAD

**Issue by Tolo0** [H4PM/Elywing#374]
Not sure exactly how this happens but twice now my server.properties has reset. is this a Elywing glitch? iv never had this problem in the passed.

**Comment by TDMidkwhatisxd** [comment]
Ummmm... 0-0 ! Steps you did?
If you edit server.etcccc and the server run, it will go back to normal wen server restart!
Close server, edit your config and then tell me if it reset!

NOTE
--------------
If you use a host, they may reset your config files!

**Comment by Tolo0** [comment]
I use a dedi so no host. I have no idea how it reset. my server has a auto restart plugin on it so every 30 min it reboots.

**Comment by TDMidkwhatisxd** [comment]
I understand! Did u follow my steps? Reboot dedicated, ssh command reboot, edit your config then start again!

**Comment by Tolo0** [comment]
Yea i tried that. it didn't reset it.

**Comment by TDMidkwhatisxd** [comment]
😊

**Comment by Tolo0** [comment]
It's just randomly reset again 😣 the server been running for hours np. I go to bed wake up to find its been reset.

**Comment by KennFatt** [comment]
Try to shutdown your server, edit your server.properties. then run / start again your server. I think it got re

**Comment by Lazerplayz** [comment]
KennFatt is correct if you stop your server and edit the server.properties and save and then turn on your server it will save.
