### ISSUE TITLE
Monthly Request Limit reached

### ISSUE THREAD

**Issue by TacosYum** [H4PM/Elywing#375]
API Server Returned
 Error Message: Monthly Request Limit Reached when 
TacosYum tried to connect
[Elywing] [19:31:43] CRITICAL> Shutting down serv
er to prevent blacklisting on API Database

**Comment by mote166** [comment]
stop using vpnguard . ur limit access has ended . delete the plugin and everything will come back normal

**Comment by AppleDevelops** [comment]
Plugin issue
