### ISSUE TITLE
No one can join server

### ISSUE THREAD

**Issue by WreckagePE** [H4PM/Elywing#376]
This was not happening before, however as of yesterday, when players try to connect the screen shows blank rather than 'unable to connect to world' My host rolledback the server and the same issue is occurring... This is critical!

**Comment by mote166** [comment]
i didn't understand the issue but the blank screen is a mcpe 1.0 issue , not elywing's

**Comment by TDMidkwhatisxd** [comment]
Server ip?

**Comment by Tolo0** [comment]
I had this problem when using a old version of EssentialsPE. maybe it's one of ur plugins.

**Comment by WreckagePE** [comment]
I have installed essentailspe, a modified version (without kits) but my server console says
Raklib thread: cannot bind to *ip*
Maybe this port is already been used?

**Comment by Tolo0** [comment]
reboot ur vps or dedi

**Comment by Tolo0** [comment]
then create a new screen -S name

**Comment by WreckagePE** [comment]
What do you mean by new screen? I have contacted my host about this... Maybe they can fix?

**Comment by Tolo0** [comment]
I think only your host can. Screen is for a vps or dedi server. ignore that.
