### ISSUE TITLE
[QUESTION] About signs

### ISSUE THREAD

**Issue by Adam1609** [H4PM/Elywing#377]
When upgrading to 1.0, i realized that creating signshop or any essentialsPE didn't work anymore?
I check the file, and it was true, couldn't create any sign.
Does it affect to 1.0 software? And if possible, please fix it?

**Comment by TDMidkwhatisxd** [comment]
http://s000.tinyupload.com/?file_id=00658674783989954536
Download this!

**Comment by TDMidkwhatisxd** [comment]
Codename cake, becouse is like a piece of cake 😆

**Comment by Adam1609** [comment]
Can you tell me exactly where to fix it? Because I had my software as my plugin Core and I can't replace it

**Comment by TDMidkwhatisxd** [comment]
Then why you post on elywing issue?
You can always look into the source code + idk, i forgot!

You can always port your core in this software!


Anyway good look and sorry for not helping 0-0

**Comment by TDMidkwhatisxd** [comment]
Anyway this build have an issue! Signs does not auto update u need exit/enter world to see others sign, or even shop(wen u write it)!

**Comment by Adam1609** [comment]
Ok, I will see if any members of this repo could fix this error here :(

**Comment by AppleDevelops** [comment]
fixed
