### ISSUE TITLE
Server rebooting on it own

### ISSUE THREAD

**Issue by KnightOfEnder** [H4PM/Elywing#378]
Hi since Yersterday when some of the files updated. The server now reboot and closes down on it own every 3mins and I can't find a way to stop it I've check all the files and none of the code look off or different to cause it . But please help

**Comment by TDMidkwhatisxd** [comment]
Do you have restartme?

**Comment by KnightOfEnder** [comment]
I did but remove it and the problem remain. Now my server is totally offline.

**Comment by KnightOfEnder** [comment]
![screenshot_2017-01-10-22-06-30](https://cloud.githubusercontent.com/assets/24853541/21850453/9007434e-d802-11e6-88ba-b6f352bc32a8.png)

**Comment by KnightOfEnder** [comment]
![screenshot_2017-01-10-21-56-22](https://cloud.githubusercontent.com/assets/24853541/21850475/a72300e0-d802-11e6-8574-a3ef33ccf56d.png)

**Comment by TDMidkwhatisxd** [comment]
U should show last action before the shut down process come! 
Scroll up a little, this dont tell me anything!

**Comment by KnightOfEnder** [comment]
Turns out it due to VPNGUARD

**Comment by TDMidkwhatisxd** [comment]
Lololol xd! That thing cost money or it close your server!

**Comment by KnightOfEnder** [comment]
Lmao oh well XD

**Comment by TDMidkwhatisxd** [comment]
Do u use build i gave you? I use it on my server!

**Comment by KnightOfEnder** [comment]
What build that for enchantment ?

**Comment by TDMidkwhatisxd** [comment]
Yep, but have more bugs fixed,like dupe bug

**Comment by KnightOfEnder** [comment]
Oh I don't know where I place the file lol but u can see the current scripe that show when I try the current file  for enchantment
![screenshot_2017-01-11-16-22-28](https://cloud.githubusercontent.com/assets/24853541/21856800/29a3497c-d81b-11e6-9131-d7e9ec53863e.png)

**Comment by TDMidkwhatisxd** [comment]
Just copy/paste. To server files!  And replace old pocketmine-mp.phar

**Comment by KnightOfEnder** [comment]
![screenshot_2017-01-10-21-57-43](https://cloud.githubusercontent.com/assets/24853541/21857115/47091cc0-d81c-11e6-9ca8-7e724e6e3d89.png)
Bro what is this it spam my console -.-

**Comment by TDMidkwhatisxd** [comment]
A plugin call spawntoall() to null!

**Comment by TDMidkwhatisxd** [comment]
Maybe a spawner block? Idk i dont have the problem!

**Comment by ZacharySims** [comment]
@TDMidkwhatisxd What build do you have? Are you saying that it fixes the dupe glitch and enchanting? If so that'd be super useful for the server @LordJoshie and I run if you wanted to pass it along :)

**Comment by KnightOfEnder** [comment]
The Toolbox Dupe glitch will not be fix as long as there no Anti cheat the Made for toolbox to stop the spawning and duping of it items. Apart from the main one that blocks them all

**Comment by TDMidkwhatisxd** [comment]
@ZacharySims https://github.com/H4PM/Elywing/issues/372
There i post the link!
Make sure you have in genisys.yml allow-cheat false, to block inventory cheats!

And ya, all fixed! Just .mcr regions wont work just anvil!
Craft: in pocket UI you can craft armour,planks, but cant craft other stuff!
