### ISSUE TITLE
Why just whu

### ISSUE THREAD

**Issue by KnightOfEnder** [H4PM/Elywing#380]
Whay ever you added now make the console disconnect the server and close every time I loss wifi. It never did that until ur updated something please remove what ever u did to cause this my server wont stay on a dam hour now cause of it

**Comment by TDMidkwhatisxd** [comment]
How you run the server? What ssh command you use?

**Comment by KnightOfEnder** [comment]
Shh client off google play

**Comment by TDMidkwhatisxd** [comment]
What command dude!
./start.sh?!
