### ISSUE TITLE
New problem 

### ISSUE THREAD

**Issue by KnightOfEnder** [H4PM/Elywing#381]
We remove VPNGUARD to remove the ramdom reboot problem. But Now we being hit by a New problem The server Ramdom Shut down and don't say why or what causing but after it does it we cant connect to the ssh client for a few minutes.

**Comment by TDMidkwhatisxd** [comment]
Its clear! If so, you run on  a 65mb ram vps! 

SSH problem is by vps, not server! If ssh inactive = vps problem!

**Comment by KnightOfEnder** [comment]
I've sent ticket to Blueleafhosting got to be on there end..

**Comment by TDMidkwhatisxd** [comment]
![screenshot_2017-01-12-23-59-24](https://cloud.githubusercontent.com/assets/18122629/21910065/266f8a6e-d923-11e6-9068-e02724f206ee.png)

Kill me 😐
