### ISSUE TITLE
i spam issue now

### ISSUE THREAD

**Issue by thebigsmileXD** [H4PM/Elywing#384]
![image](https://cloud.githubusercontent.com/assets/8733998/21882941/006d5c2c-d8ad-11e6-817e-2b744cccffcc.png)
bye

**Comment by Aericio** [comment]
<3

**Comment by TDMidkwhatisxd** [comment]
Do u leave? Or ...?

**Comment by thebigsmileXD** [comment]
@TDMidkwhatisxd what does the word 'bye' mean in your country?
And mostly because of you.

**Comment by Infernus102** [comment]
lol

**Comment by TDMidkwhatisxd** [comment]
Im not a member of the project! You can always close my issues , block them or ban me!
+ most of the spammy issues are from dktapps minions, who try to bully elywing devs!

Im not a dev to feel insulted by me 😂 ! So, why you leave now? I always check for new commits!

But you should add my phar in project files as the last semy-stable build , until you finish the project 😃, and warn ppl that for now elywing is a work in progress! 😉

**Comment by thebigsmileXD** [comment]
> most of the spammy issues are from dktapps minions, who try to bully elywing devs!
lol xd

**Comment by TDMidkwhatisxd** [comment]
I dont mean you 0-0

**Comment by Aericio** [comment]
We do not 'bully' elywing devs, and we are not his 'minions'. That's quite rude, to call us minions.

**Comment by thebigsmileXD** [comment]
Yea.
