### ISSUE TITLE
Floating Text

### ISSUE THREAD

**Issue by ItzWalla** [H4PM/Elywing#392]
Pretty sure this is your guy's issue.
![img_3436](https://cloud.githubusercontent.com/assets/20291307/21959334/7ec15ae8-da78-11e6-85f3-e8757f351a2a.PNG)

**Comment by AppleDevelops** [comment]
It looks like an LiveTexts issue but I'll investigate

**Comment by AppleDevelops** [comment]
https://github.com/EmreTr1/LiveTexts/pull/23
