### ISSUE TITLE
Purechat problem

### ISSUE THREAD

**Issue by KnightOfEnder** [H4PM/Elywing#397]
Hi I'm getting this for Purechat and it not working on the server 
![screenshot_2017-01-15-13-31-43](https://cloud.githubusercontent.com/assets/24853541/21962911/ad36e294-db27-11e6-854c-7d6573bb15f6.png)

**Comment by oxxydev** [comment]
You using PurePerms?

**Comment by KnightOfEnder** [comment]
Yes

**Comment by Adam1609** [comment]
Where are your PurePerms?
Without that, PurePerms can't run yah!

**Comment by KnightOfEnder** [comment]
By it if PurePerms are not showing in Console means the file broken down then

**Comment by AppleDevelops** [comment]
Plugin issue
