### ISSUE TITLE
Problems with Synapse...

### ISSUE THREAD

**Issue by erkam2002** [H4PM/Elywing#398]
Elywing thread:CRITICAL > Unhandled exception executing command 'transfer 2' in transfer: Class ChangeDimensionPacket not found
08:54:40 | Elywing thread:CRITICAL > ClassNotFoundException: "Class ChangeDimensionPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by Misteboss** [comment]
Just add the changedimensionpacket

**Comment by erkam2002** [comment]
How?
