### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by KnightOfEnder** [H4PM/Elywing#400]
![screenshot_2017-01-15-16-09-57](https://cloud.githubusercontent.com/assets/24853541/21964076/4b1e32f4-db3d-11e6-91e5-95f11d818e15.png)

**Comment by AppleDevelops** [comment]
Are you sure you are using the latest commit?

**Comment by KnightOfEnder** [comment]
Don't know how to tell if I am

**Comment by AppleDevelops** [comment]
Download the latest version on here lol
