### ISSUE TITLE
Logged out due to Timeout. 

### ISSUE THREAD

**Issue by Enrick3344** [H4PM/Elywing#403]
I'm getting alot of Logged out due to Timeout! Its happend randomly And I don't Know Why. Is there something to fix in the software or is it in my plugins.

**Comment by KennFatt** [comment]
Slapper is active?

**Comment by Enrick3344** [comment]
The plugin is on my server but there is no slapper on my server

**Comment by Enrick3344** [comment]
And please fix some Enchanting issues please

**Comment by Lazerplayz** [comment]
You need to update to the latest slapper version on the 1.0 development page. 

And if the server crashes when you make a slapper change FullChunk to Chunk.

**Comment by AppleDevelops** [comment]
plugin issue
