### ISSUE TITLE
Enchanting is Broken.

### ISSUE THREAD

**Issue by PragaKart67z** [H4PM/Elywing#404]
Enchanting is Broken, try adding any tool or piece of armor into the etable and it will throw it back out. This has been happening since 0.16.0.

OS: Any
PHP: 7.0.6
Version: 1.0.X Elywing

**Comment by andris155** [comment]
set allow-cheats: false true

**Comment by BegForMercyMCPE** [comment]
By allowing that, players with toolbox could change theirselves to creative and spawn things illegally.
