### ISSUE TITLE
Does Elywing impact with this Error?

### ISSUE THREAD

**Issue by Adam1609** [H4PM/Elywing#405]
06:42:42 | Elywing thread:CRITICAL > "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EssentialsPE v2.0.0': Invalid entity coordinates on EssentialsPE\EventHandlers\SignEvents
06:42:42 | Elywing thread:CRITICAL > InvalidStateException: "Invalid entity coordinates" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 329
06:42:42 | Elywing thread:CRITICAL > Could not tick level "sky": Invalid entity coordinates
.
It happened! Thus it never happened before. There is no response at EssentialsPE's repo, so I guess I have to wait responses to 2 repos

**Comment by Aericio** [comment]
elywing makes everything broken
