### ISSUE TITLE
Server freezes and then kicks everyone for flying

### ISSUE THREAD

**Issue by Lazerplayz** [H4PM/Elywing#407]
Okay so it all started off by seeing this message:
17.01 19:30:55 [Server] INFO 19:30:55 | Elywing thread:WARNING > Lazerplayz moved wrongly!

Solution: FIXED
And I don't hack so how did I move wrongly then after I saw that the server froze then everyone on my server was kicked for flying:
17.01 19:30:55 [Server] INFO 19:30:55 | Elywing thread:INFO > BabyAlyssa_xox[/107.204.218.83:19132] logged out due to Kicked by admin. Reason: Flying is not enabled on this server

Solution: in server.properties set allow-flight to true to fix that

Then this happend
17.01 19:22:58 [Server] INFO Warning: Invalid argument supplied for foreach() in phar:///custom-phar.phar/src/pocketmine/plugin/PluginDescription.php on line 116

Solution: PLUGIN ISSUE

And then this happend:

17.01 19:30:57 [Server] INFO Warning: assert(): Unhandled player action 17 from WoodyKestrel03 failed in phar:///custom-phar.phar/src/pocketmine/Player.php on line 2949

Solution: Might be fixed in latest commit
And that line is:

break 2;

Please fix it happens every 10-5 minutes.

**Comment by AppleDevelops** [comment]
everything in your issue has an answer below it

**Comment by keithkfng** [comment]
@AppleDevelops great ignorant answer.

**Comment by Lazerplayz** [comment]
Can you fix it's not the custom phar :P

**Comment by AppleDevelops** [comment]
What?

**Comment by Lazerplayz** [comment]
The issue is it fixed?

**Comment by Lazerplayz** [comment]
O ll

**Comment by keithkfng** [comment]
And now @AppleDevelops deletes people's comments. There is no democracy in this world

**Comment by AppleDevelops** [comment]
@keithkfng You don't get a say here

**Comment by Lazerplayz** [comment]
The server freezes and then resumes again after 2-3 min but it's because of 19.01 19:31:41 [Server] INFO 19:31:41 | Elywing thread:WARNING > Extermerockstar9 moved too fast, reverting movement
It's spamming the server
