### ISSUE TITLE
How to get Elywing conf?I want to use it on multicraft

### ISSUE THREAD

**Issue by bzdnd** [H4PM/Elywing#408]
Elywing is really a very nice core!Now I have Core,But I don't know how to get conf

**Comment by bzdnd** [comment]
19.01 08:23:39 [Multicraft] Server stopped
19.01 08:23:39 [Multicraft] Received stop command
19.01 08:23:35 [Multicraft] Server stopped
19.01 08:23:35 [Multicraft] Looks like a crash, check the server console. Return value: 255
19.01 08:23:35 [Multicraft] Restarting crashed server in 5 seconds
19.01 08:23:35 [Multicraft] Server shut down (starting)
19.01 08:23:35 [Server] INFO Failed to run command '/home/meteor/pocketmine/bin/php7/bin/php': No such file or directory
19.01 08:23:35 [Multicraft] Updating eula.txt file
19.01 08:23:35 [Multicraft] Server executable "/home/meteor/pocketmine/bin/php7/bin/php" not found, server startup might fail!
19.01 08:23:35 [Multicraft] Loaded config for "H4PM1.0版本核心"

but I can use PocketMine 1.0.0, Why?

**Comment by MCPEPluginer16** [comment]
If you have a conf for Genisys or pmmp You can run it !

**Comment by bzdnd** [comment]
All right,My conf can run pmmp and Genisys,But So why is it wrong

**Comment by MCPEPluginer16** [comment]
I run elywing on multicraft and I don't see issue what your issue ?

**Comment by MCPEPluginer16** [comment]
You don't Setup php ?!!!!

**Comment by Wshape1** [comment]
He needs a conf to run Elywing.

**Comment by bzdnd** [comment]
I have php7,and I can run Genisys and PocketMine-MP....
So I need Elywing Setup?

**Comment by Wshape1** [comment]
- -你好

**Comment by bzdnd** [comment]
Yah,I am come from China,But I want to still say English.
My PHP version is 7.0.7,So I need Update to 7.0.13?

**Comment by Wshape1** [comment]
我也是这样的问题，不能加载可能是conf的问题.我们需要一个能配合Elywing核心的conf

**Comment by bzdnd** [comment]
那么你有吗?

**Comment by Qimie** [comment]
If u could speak English,please be sure to do that. So we can help.

**Comment by bzdnd** [comment]
All right,I can do that,So wherecan get Elywing cobf

**Comment by Qimie** [comment]
What do you mean by cobf? Or Conf?

**Comment by bzdnd** [comment]
I need conf to use on multicraft , And then I cannot use Elywing core on PHP7 conf。my php version is 7.0.7,A people said maybe my conf cannot support Elywing conf

**Comment by Qimie** [comment]
Oh yeah. You need to wait because they are upgrading the core for it to
fully support PHP 7.X.X. So,you just need to wait. Ill try to see what I
can do.

**Comment by xinghao2003** [comment]
I think maybe is the config problem

**Comment by Qimie** [comment]
What config? Filename?

**Comment by xinghao2003** [comment]
Multicraft Config

**Comment by Qimie** [comment]
Idk about multicraft but they know. Maybe.

**Comment by bzdnd** [comment]
LBK?

**Comment by Qimie** [comment]
What is lbk?

**Comment by bzdnd** [comment]
all right(๑• . •๑)。I am Using Elywing-Genisys.But somebody said me:I cannot join the server when I use Genisys Core on Minectaft ·
I know Minecraft1.0 Version cannot support mca map.finally I am change my core to Minectaft0.16 core,But I am still cannot join the server either. I often say Engilsh with some errors.....

**Comment by bzdnd** [comment]
This is a interesting question

**Comment by bzdnd** [comment]
This is an interesting problem
