### ISSUE TITLE
Farm

### ISSUE THREAD

**Issue by daniktheboss** [H4PM/Elywing#417]
Crops grow veeeeeeeeeerry slow. Please fix?

**Comment by Qimie** [comment]
Ill try to look at the code tommorrow probably.  :)

**Comment by Qimie** [comment]
Hey. I made some research and a crop takes 37 mins to grow to the last stage. The question is do you really want me to update grow time?

**Comment by daniktheboss** [comment]
um.. should take 3 min to 10
