### ISSUE TITLE
Servers freezing again -_-

### ISSUE THREAD

**Issue by Lazerplayz** [H4PM/Elywing#419]
The server freezes and then resumes again after 2-3 min but it's because of 19.01 19:31:41 [Server] INFO 19:31:41 | Elywing thread:WARNING > Extermerockstar9 moved too fast, reverting movement
It's spamming the server

**Comment by Lazerplayz** [comment]
getname in level on null Might also be with this issue can I disable the moved too fast thing?

**Comment by TDMidkwhatisxd** [comment]
Potato Pc 👏

**Comment by Lazerplayz** [comment]
... I'm pretty sure a dedicated machine using a host isn't a friken potato pc..

**Comment by TDMidkwhatisxd** [comment]
I host my sv on a 10$ vps 👏 And can run 80 players at once 👏

**Comment by Lazerplayz** [comment]
Well at lest my server has a meaning.

**Comment by andris155** [comment]
Same problem E3 dedicated server.

**Comment by remotevase** [comment]
This problem is due to a chunk issue. Fixed in tesseract a while ago

**Comment by andris155** [comment]
Grnisys, Tesseract, Pocketmine, steadfast2. Which is the stable?

**Comment by remotevase** [comment]
Tesseract, it has the least bugs

**Comment by RompeCraneos** [comment]
This bug is present in my new server too, with genisys the server is good, but elywing was better and less lag. The Freeze is frustrating

**Comment by remotevase** [comment]
Try Tesseract, like I said, or have an Elywing dev update. It is a major commit, so I cannot do it for them

**Comment by NemanjaMAX** [comment]
@remotevase is developer (owner) of TESSERACT,and I free can say to TESSERACT is ONE LOVE <3 The bedt <3 And #blamemojang

**Comment by Lazerplayz** [comment]
Just can @AppleDevelops or @SuperMaXAleX fix this issue ._. It's killing my server.

**Comment by AppleDevelops** [comment]
@NemanjaMAX He isn't technically owner of the repo, he has owner perms but I am the actual owner of the repo.

**Comment by AppleDevelops** [comment]
@Lazerplayz I'll possibly take a look, it's been a while.

**Comment by Lazerplayz** [comment]
@AppleDevelops how long will it take to fix its a top priority.

**Comment by AppleDevelops** [comment]
@Lazerplayz I have no idea, I'm working on a lot of plugins and my software, so maybe soon.
