### ISSUE TITLE
Invalid entity coordinate

### ISSUE THREAD

**Issue by Adam1609** [H4PM/Elywing#420]
This time, I actually hate this error. I never have that issue before in 1 month and now!
Elywing Crash Dump Sat Jan 21 08:32:58 UTC 2017

Error: Invalid entity coordinates
File: /src/pocketmine/entity/Entity
Line: 373
Type: notice

Code:
[364] 				$this->namedtag["Pos"][1],
[365] 				$this->namedtag["Pos"][2]
[366] 			),
[367] 			$this->namedtag->Rotation[0],
[368] 			$this->namedtag->Rotation[1]
[369] 		);
[370] 		$this->setMotion($this->temporalVector->setComponents($this->namedtag["Motion"][0], $this->namedtag["Motion"][1], $this->namedtag["Motion"][2]));
[371] 
[372] 		if(is_nan($this->x) or is_infinite($this->x) or is_nan($this->y) or is_infinite($this->y) or is_nan($this->z) or is_infinite($this->z)){
[373] 			throw new \InvalidStateException("Invalid entity coordinates");
[374] 		}
[375] 
[376] 		if(!isset($this->namedtag->FallDistance)){
[377] 			$this->namedtag->FallDistance = new FloatTag("FallDistance", 0);
[378] 		}
[379] 		$this->fallDistance = $this->namedtag["FallDistance"];
[380] 
[381] 		if(!isset($this->namedtag->Fire)){
[382] 			$this->namedtag->Fire = new ShortTag("Fire", 0);
[383] 		}

Backtrace:
#0 /src/pocketmine/level/format/Chunk(718): pocketmine\entity\Entity::createEntity(string Spider, pocketmine\level\format\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\DoubleTag:NAN.pocketmine\nbt\tag\DoubleTag:-23.52.pocketmine\nbt\tag\DoubleTag:NAN.}.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\DoubleTag:NAN.pocketmine\nbt\tag\DoubleTag:-4.07.pocketmine\nbt\tag\DoubleTag:NAN.}.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\FloatTag:NAN.pocketmine\nbt\tag\FloatTag:NAN.}.pocketmine\nbt\tag\FloatTag:97.519996643066.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:6.pocketmine\nbt\tag\StringTag:Spider.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ByteTag:1.})
#1 /src/pocketmine/level/Level(2719): pocketmine\level\format\Chunk->initChunk(boolean)
#2 /src/pocketmine/level/Level(679): pocketmine\level\Level->loadChunk(integer 0, integer 0)
#3 /src/pocketmine/Player(836): pocketmine\level\Level->registerChunkLoader(pocketmine\Player Player(6), integer 0, integer 0, boolean 1)
#4 /src/pocketmine/Player(1643): pocketmine\Player->sendNextChunk(boolean)
#5 /src/pocketmine/Server(2772): pocketmine\Player->checkNetwork(boolean)
#6 /src/pocketmine/Server(2464): pocketmine\Server->tick(boolean)
#7 /src/pocketmine/Server(2342): pocketmine\Server->tickProcessor(boolean)
#8 /src/pocketmine/Server(1932): pocketmine\Server->start(boolean)
#9 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Administrator\Desktop\SkyBlock\, string C:\Users\Administrator\Desktop\SkyBlock\, string C:\Users\Administrator\Desktop\SkyBlock\plugins\, string unknown)

Genisys version: 8f465763c590293e2003ce616832b6507edf5b1c [Protocol 100; API 3.0.0-ALPHA1]
uname -a: Windows NT LENGOCTHANG-001 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64
PHP version: 7.0.14
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 6 minutes 49 seconds
Number of loaded worlds: 3
Players online: 5/60

Loaded plugins:
aFloatingText 1.2 by AlexBrin for API(s) 1.10.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
CoreProtect 0.1.5 by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0
HereAuth 1.0-Dev#229 by PEMapModder for API(s) 2.0.0
KillChat 1.0.2.MOD by Array for API(s) 1.9.0, 2.0.0
LaunchPads 1.0.0 by MCPEPIG for API(s) 1.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
TopVoter 1.1.6 by SalmonDE for API(s) 2.0.0
WorldEditPotato 1.5 by HuaYoyu for API(s) 2.0.0
WorldProtect 2.3.0 by aliuly for API(s) 1.10.0, 1.12.0, 2.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
AutoInv 1.9 by Jons-Hung for API(s) 2.0.0
BuyEnchant 1 by  for API(s) 2.0.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
Dial 0.3.1 by Harry for API(s) 2.0.0
SetVip 1.0.0 by Shin for API(s) 1.12.0
VIPcmds 1.0.0 by HimbeersaftLP for API(s) 1.0.0
Information 0.1 by Adam1609/R for API(s) 2.0.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
FactionsPro 1.3.2 by Array for API(s) 1.14.0, 2.0.0
Giftcode 1.2beta1 by  for API(s) 2.0.0
REDFeed 1.0BETA by  for API(s) 1.14.0, 2.0.0
MysUFarms 0.0.1 by GlxTeam for API(s) 2.0.0
MysUSCL 0.1 by Adam1609 credit to Sergey_Dertan for API(s) 2.0.0
NapThe 2 by  for API(s) 2.0.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
REDEC 1 by LostTeam - Vietnamese by Adam1609 for API(s) 2.0.0, 1.13.1
REDNoBreak 0.1 by Adam1609 for API(s) 2.0.0
MysUP 1 by Anonymous for API(s) 2.0.0
SimpleKits 0.5 by  for API(s) 2.1.0, 3.0.0-ALPHA1
SizePLayer 1 by DragonPlayzMC for API(s) 2.0.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
SS 0.1BETA by Adam1609 for API(s) 2.0.0
superBAR 1.6.1 by FaigerSYS for API(s) 2.0.0
SkyBlock 1 by Wies and Exxarion for API(s) 2.0.0

**Comment by Tolo0** [comment]
Getting the same error and this


Notice: Undefined offset: 0 in /home/tolo/mc2/src/pocketmine/level/format/Chunk.php on line 406
22:05:34 | Elywing thread:CRITICAL > Could not tick level "NewWorld": Return value of pocketmine\level\format\Chunk::getHeightMap() must be of the type integer, null returned
