### ISSUE TITLE
What's Wrong?

### ISSUE THREAD

**Issue by xinghao2003** [H4PM/Elywing#422]
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4096 bytes) in C:\Users\UserX\Desktop\PM-MP\src\pocketmine\level\Level.php on line 1340

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65536 bytes) in Unknown on line 0

**Comment by MaryVictoria** [comment]
my server crashed and same with that dump.. when i restart again its make new world with format of r.-3.0.mcapm   .. my old world map can't open it :( with a format of r.8.-2.mca

**Comment by mote166** [comment]
i think u ran out of memory.  it happens when u have low pc ram or u didn't edit the ram limit in pocketmine.yml
