### ISSUE TITLE
[BUG] Les maps avec les regions en .MCa sont bug.

### ISSUE THREAD

**Issue by GamingPilot2** [H4PM/Elywing#424]
Bonsoir. Tout est dit dans le titre donc POUVEZ-Vous faire quelque chose ? CAR C'EST SUPER MEGA CHIANT d'avoir fait ça sachant qu'aucun autre software n'a fait ca.

**Comment by SuperMaXAleX** [comment]
Les .mca fonctionnent justement très bien.
