### ISSUE TITLE
Spawner mobs

### ISSUE THREAD

**Issue by daniktheboss** [H4PM/Elywing#425]
Hello, i set a tile on a mob spawner, and entity id 12 (pig), works flawlessly, so does 12, 14, 15. Any other entity id it will change the id back to 0 or 4. I did this experiment by setting the damage to a certain number and setting the tile entity id reading from the damage id. As i saw, most ids do not work.

**Comment by AppleDevelops** [comment]
I can't reproduce it. It might be a plugin issue
