### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by kek228** [H4PM/Elywing#426]
I have a problem with armor. I wear armor but it drops.

**Comment by daniktheboss** [comment]
much detail

**Comment by Qimie** [comment]
Give us more detail so we could help or fix it..

**Comment by kek228** [comment]
so. I wear the armor. And, when i close the inventory it drops or if leave and join to server armor remove (sorry for bad english)

**Comment by Qimie** [comment]
As long as I can understand what u say,im ok with that. So,I just wanna ask you. What are the situation u in?

Situation 1:-
- You already wear a armor and replace it without take the armor before off first.

Situation 2:-

- You put the armor fast/too quick.

Last Question:-

- Are you having this issue on Local LAN Server Or A WorldWide Server/Multiplayer Server.
