### ISSUE TITLE
error when loading a world

### ISSUE THREAD

**Issue by EpicSteve33** [H4PM/Elywing#43]
when I load a world I get an error

Elywing thread:INFO > Preparing level "PVP"
Elywing thread:CRITICAL > TypeError: "Return value of pocketmine\level\Level::getSeed() must be of the type integer, string returned" (EXCEPTION) in "/src/pocketmine/level/Level" at line 3022

how I loaded the world

```
public function onEnable(){
       $this->getServer()->getPluginManager()->registerEvents($this ,$this);      
       $this->getServer()->loadLevel("PVP"); 
       $this->getServer()->loadLevel("game1"); 
       $this->getServer()->loadLevel("parkour");
       $this->getLogger()->info(C::GREEN ."Everything Loaded!");
  }
```

**Comment by legoboy0215** [comment]
This error happens on every spoon. They haven't patched it yet.

**Comment by EpicSteve33** [comment]
I just wanted to bring it to someones attention so they can fix it :)

**Comment by EpicSteve33** [comment]
I fixed it here https://github.com/H4PM/Elywing/pull/61
