### ISSUE TITLE
Add new pls:)

### ISSUE THREAD

**Issue by Serega4158** [H4PM/Elywing#435]
Hmm, the core of good but it is necessary so to support all plug-ins such as: EconomyShop 2.0.7 API 3.0.0 you will support and add the world types mcregion / mcr that everything was okay, color biome biomes, generator, etc.

**Comment by Qimie** [comment]
Yeah. Thats true. They should be working on Generators. No hates towards the devs. It is hard to take care of the software bc Mojang has been pushing so many updates lately.
