### ISSUE TITLE
Happy new year?

### ISSUE THREAD

**Issue by touchvoid** [H4PM/Elywing#436]
Although very embarrassed，
I want to give you feedback on a bug，
Game player backpack things sometimes themselves thrown out, often occur in death and after Carlton = =
please fix bug。

**Comment by lowingly** [comment]
I think your "Carlton" means: not smooth.（Google translation errors）
I have this problem too.
Sometime...
Player’s backpack things will themselves thrown out when player reenter server（they reenter server because they feel the server is not smooth）.
