### ISSUE TITLE
Cant Pick up items

### ISSUE THREAD

**Issue by YaBoiBalAnce** [H4PM/Elywing#44]
When in survival you cant pick up items they fail to go into inventory sometimes stay there sometimes just disappear.
Using Genisys branch btw.

**Comment by TheAppleGamer** [comment]
Thats a fixed bug on the master branch

**Comment by YaBoiBalAnce** [comment]
so is genysis branch no longer gonna be maintained

**Comment by Misteboss** [comment]
@YaBoiBalAnce Genisys branch is now the master branch
