### ISSUE TITLE
Classic GUI Death Inventory Bug

### ISSUE THREAD

**Issue by Qimie** [H4PM/Elywing#441]
![img_lglhpv](https://cloud.githubusercontent.com/assets/18200541/22579972/667da47c-ea0f-11e6-9862-22ea8d160e33.jpg)

I found this by accidentally on CosmicPE. @Muqsit Server. If U Get Killed With Ur Stuff In The Crafting GUI In Ur Inventory, You Will Still Have Ur Stuff And That Is A OP Bug. I Hope U Guys Will Be  Able To Fix It.

**Comment by Qimie** [comment]
Ill Tag U Guys. So,U Guys Don't Close This Without Take A Look At It. @YaBoiBalAnce @hmy2001 	@edwinyoo44 @andris155 @thebigsmileXD @dktapps

**Comment by edwinyoo44** [comment]
。。。。

**Comment by thebigsmileXD** [comment]
@Qimie how about looking into repositories? Searched it up for you.

https://github.com/iTXTech/Genisys/commit/4cd248be73067023a80fb464ebc39ddb9d3a97c9

**Comment by Muqsit** [comment]
We use clean genisys

**Comment by Qimie** [comment]
Can u update that on Elywing? Bc I dont have perm to write. Sorry. U can close this issue now. @Muqsit Lots Of People Use This On Ice Planet.

**Comment by Qimie** [comment]
I guess I'm gonna try update some blocks... Bc some blocks doesn't work as Singleplayer mcpe world.

**Comment by AppleDevelops** [comment]
I'd update the software, but I'm busy with making plugins.

**Comment by Assblocker** [comment]
LOL, I laughed so bad when @Muqsit said "we use clean genisys" omg like he uses the worst genisys, that server "cosmicpe" has so many glitches like alot, more than half the player there duplicates item there all the time! it's the worst server i have seen so far on mcpe with lag.
