### ISSUE TITLE
Installing on Linux

### ISSUE THREAD

**Issue by Akuroma** [H4PM/Elywing#442]
Hey there. How can I install Elywing on Linux?

**Comment by VoliPlays** [comment]
Do you have instagram if u have give me here I can help you:)

**Comment by TheNoobster14** [comment]
I need help also and my insta is TheNoobster14

**Comment by Herojhjh** [comment]
git clone https://github.com/H4PM/Elywing

**Comment by Herojhjh** [comment]
use src
