### ISSUE TITLE
Respawn Bug

### ISSUE THREAD

**Issue by ManiakMCPE** [H4PM/Elywing#447]
When a player dies and attempts to respawn it just leaves them in the place they died basically like a ghost, no other players can see them and the player has to relog to continue to play.

**Comment by WreckagePE** [comment]
Maniak your version of Elywing is edited for 1.0.3. It only happened after you updated... I think you should see what's going on there

**Comment by ManiakMCPE** [comment]
I'm just using normal ElyWing, It's not fully compatible with 1.0.3 yet though.

**Comment by WreckagePE** [comment]
Ahh right... How are your players connecting with the 1.0.3 Version then? Just wondering lol
