### ISSUE TITLE
Lag Spikes?

### ISSUE THREAD

**Issue by ManiakMCPE** [H4PM/Elywing#453]
Since the recent commit fixed the respawn bug it seems to have caused another bug, server lag has been an issue since I updated my server about an hour ago. This did not happen before, this started after using the new level folder update.

**Comment by SuperMaXAleX** [comment]
We don't have any server lag, it's coming from you.

**Comment by ManiakMCPE** [comment]
Nope, it was ElyWing, switched to Tesseract and now there is no lag.

**Comment by AppleDevelops** [comment]
🤔 I'll have to look into this. If Tesseract doesn't have this issue then something's up for sure.

**Comment by Mrfanman345** [comment]
I've found that world loading is faster on Tesseract but everything else is faster on Elywing.
