### ISSUE TITLE
transfer command has an error

### ISSUE THREAD

**Issue by djdisodo** [H4PM/Elywing#455]
`13:33:26 | Elywing thread:CRITICAL > Unhandled exception executing command 'transfer' in transferserver: Class pocketmine\command\defaults\TranslationContainer not found
13:33:26 | Elywing thread:CRITICAL > ClassNotFoundException: "Class pocketmine\command\defaults\TranslationContainer not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
13:33:26 | Elywing thread:DEBUG > #0 /src/pocketmine/command/defaults/TransferCommand(56): spl_autoload_call(string pocketmine\command\defaults\TranslationContainer)
13:33:26 | Elywing thread:DEBUG > #1 /src/pocketmine/command/SimpleCommandMap(269): pocketmine\command\defaults\TransferCommand->execute(pocketmine\Player Player(2), string transfer, array Array())
13:33:26 | Elywing thread:DEBUG > #2 /src/pocketmine/Server(2171): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player Player(2), string transfer)
13:33:26 | Elywing thread:DEBUG > #3 /src/pocketmine/Player(3175): pocketmine\Server->dispatchCommand(pocketmine\Player Player(2), string transfer)
13:33:26 | Elywing thread:DEBUG > #4 /src/pocketmine/network/Network(256): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\CommandStepPacket object)
13:33:26 | Elywing thread:DEBUG > #5 /src/pocketmine/Player(2194): pocketmine\network\Network->processBatch(pocketmine\network\protocol\BatchPacket object, pocketmine\Player Player(2))
13:33:26 | Elywing thread:DEBUG > #6 /src/pocketmine/network/RakLibInterface(139): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\BatchPacket object)
13:33:26 | Elywing thread:DEBUG > #7 /src/raklib/server/ServerHandler(99): pocketmine\network\RakLibInterface->handleEncapsulated(string 192.168.0.1:19132, raklib\protocol\EncapsulatedPacket `.H.........Fx...a.......e..t.g.......9.0....GIQb^qZj.{JjZbiN......`d.+.....@..v(.', integer 0)
13:33:26 | Elywing thread:DEBUG > #8 /src/pocketmine/network/RakLibInterface(77): raklib\server\ServerHandler->handlePacket(boolean)
13:33:26 | Elywing thread:DEBUG > #9 /src/pocketmine/network/Network(159): pocketmine\network\RakLibInterface->process(boolean)
13:33:26 | Elywing thread:DEBUG > #10 /src/pocketmine/Server(2759): pocketmine\network\Network->processInterfaces(boolean)
13:33:26 | Elywing thread:DEBUG > #11 /src/pocketmine/Server(2466): pocketmine\Server->tick(boolean)
13:33:26 | Elywing thread:DEBUG > #12 /src/pocketmine/Server(2344): pocketmine\Server->tickProcessor(boolean)
13:33:26 | Elywing thread:DEBUG > #13 /src/pocketmine/Server(1934): pocketmine\Server->start(boolean)
13:33:26 | Elywing thread:DEBUG > #14 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Administrator\Desktop\ddd - ......\, string C:\Users\Administrator\Desktop\ddd - ......\, string C:\Users\Administrator\Desktop\ddd - ......\plugins\, string unknown)`

php:7.0.2

**Comment by Takesikaityo** [comment]
Maybe, don't neet :
So, /transfer 192.168.11.11 19132

**Comment by Hunyahemee** [comment]
Lel i found this
