### ISSUE TITLE
I want to add it to jpn.ini

### ISSUE THREAD

**Issue by Takesikaityo** [H4PM/Elywing#457]
langFile Jpn

pocketmine.player.logIn={%0}[/{%1}:{%2}] [クライアントID: {%3}] エンティティId {%4} として{%9}で ({%5}, {%6}, {%7}, {%8}) に入室しました。

**Comment by SuperMaXAleX** [comment]
Do a pull request.

**Comment by Takesikaityo** [comment]
ok!
