### ISSUE TITLE
Teleport on respawnevent don't work

### ISSUE THREAD

**Issue by Misteboss** [H4PM/Elywing#46]
When the player respawn he can't be teleport

**Comment by EpicSteve33** [comment]
@Misteboss I've noticed that a lot of things are broken lol

**Comment by xZeroMCPE** [comment]
Give me push access to this repo, and i"ll help out.

@Misteboss

**Comment by TDMidkwhatisxd** [comment]
u can just pull request if wanna to help!

**Comment by SuperMaXAleX** [comment]
Fixed.

**Comment by TDMidkwhatisxd** [comment]
Hi! Wen a player die, he cant respawn, right?
If so, is not fixed!

**Comment by Muqsit** [comment]
@TDMidkwhatisxd this has been fixed. Try our servers.

**Comment by TDMidkwhatisxd** [comment]
Ya it works! I needed to stop server before i updated src file!
