### ISSUE TITLE
Item bug

### ISSUE THREAD

**Issue by Adam1609** [H4PM/Elywing#460]
Using any pickaxe with enchantment up to level 5 can cause bug. This happened shortly after I had updated to 1.0.3 and a lot of bug showed up!

**Comment by Qimie** [comment]
Bc vanilla mcpe limits enchantment to 5. If u /enchant more it will cause
bug. Idk what i just said

**Comment by Adam1609** [comment]
I use my enchant plugin to increase level enchant. Bug Item Appeared

**Comment by Lazerplayz** [comment]
Then it's a plugin issue...

**Comment by daniktheboss** [comment]
Smh... plugin fault close issue
