### ISSUE TITLE
console warning 

### ISSUE THREAD

**Issue by mote166** [H4PM/Elywing#461]
what does this mean ? i mean whats the cause? 
my players aren't even using hacks 

[Server] WARNING krir1234 moved too fast, reverting movement 13.02 11:25:14 [Server] WARNING lolo198 moved too fast, reverting movement 13.02 11:25:14 [Server] WARNING KJGB moved too fast, reverting movement 13.02 11:25:14 [Server] WARNING waelAEDN moved too fast, reverting movement 13.02 11:25:14 [Server] WARNING yamns moved too fast, reverting movement 13.02 11:25:14 [Server] WARNING Hassnen moved too fast, reverting movement 13.02 11:25:14 [Server] WARNING jsgdsjw moved too fast, reverting movement 13.02 11:25:14 [Server] WARNING ii_petet_0_o moved too fast, reverting movement 13.02 11:25:14 [Server] WARNING asom moved too fast, reverting movement

**Comment by Pezovagew** [comment]
You may have an anticheat plugin with the sensitivity set to full

**Comment by Lazerplayz** [comment]
Your server is lagging or just go into the setting.yml and you should fine all the settings like the reverting movement issue so set that to "false"

**Comment by Qimie** [comment]
Set check-movement to true. Check genisys.yml
If didnt work,it must be a plugin.

On Feb 13, 2017 4:32 PM, "mote166" <notifications@github.com> wrote:
>
> what does this mean ? i mean whats the cause?
> my players aren't even using hacks
>
> [Server] WARNING krir1234 moved too fast, reverting movement 13.02
11:25:14 [Server] WARNING lolo198 moved too fast, reverting movement 13.02
11:25:14 [Server] WARNING KJGB moved too fast, reverting movement 13.02
11:25:14 [Server] WARNING waelAEDN moved too fast, reverting movement 13.02
11:25:14 [Server] WARNING yamns moved too fast, reverting movement 13.02
11:25:14 [Server] WARNING Hassnen moved too fast, reverting movement 13.02
11:25:14 [Server] WARNING jsgdsjw moved too fast, reverting movement 13.02
11:25:14 [Server] WARNING ii_petet_0_o moved too fast, reverting movement
13.02 11:25:14 [Server] WARNING asom moved too fast, reverting movement

**Comment by mote166** [comment]
@pezovagew no i don't have any anticheat plugin .

**Comment by mote166** [comment]
@Qimie i have it already set to true . and heres my current genisys.yml settings :



#Genisys Advanced Configuration File

#Version of this file
config:
 version: 22

level:
 #Set if weather is enabled (rain may cause lag to older devices)
 weather: false
 #Weather random duration
 weather-random-duration-min: 6000
 weather-random-duration-max: 12000
 #Random lightning interval，default as 10s, 0 = disable
 lightning-time: 200
 #Set if lightning strikes have fire afterwards
 lightning-fire: false
 #Set if fire should spread (trees, etc.)
 fire-spread: false

player:
 #Set if hunger is enabled
 hunger: false
 #Choose if experience is enabled
 experience: true
 #Choose if to keep a player's inventory after they die
 keep-inventory: false
 #Clear the inventory of a player upon them changing their gamemode
 auto-clear-inventory : true
 #Choose if to keep a player's experience after they die
 keep-experience: false
 #If players crash when joining, change this to less than 10. disable=-1
 chunk-radius: -1

nether:
 #Choose if the nether is allowed. The level of nether will generate automatically
 allow-nether: false
 #The name of nether's level
 level-name: "nether"

server:
 #Choose if spawning iron golem is allowed
 allow-iron-golem: false
 #Choose if spawning snow golem is allowed
 allow-snow-golem: false
 #Choose if server.log is disabled
 disable-log: true
 #Choose if to enable anti-fly
 anti-fly: true
 #Choose if async chunks request is enabled
 async-chunk-request: false
 #Choose how to remind players when someone joins the game
 #0 = Message, 1 = Tip, 2 = Popup
 player-msg-type: 0
 login-msg: "§3@player joined the game"
 logout-msg: "§3@player left the game"
 #Choose if movement check is enabled (no more pull backs when moving fast)
 check-movement: true
 #Set if limited creative is enabled (cannot drop items from hotbar, cannot open chests, and so on)
 limited-creative: false
 #Set if add DestroyBlockParticle
 destroy-block-particle: false
 #Set if splash potions are enabled
 allow-splash-potion: true
 #Set if Advanced Command Selector is enabled
 advanced-command-selector: false

enchantment:
 #Choose if anvils are enabled
 enable-anvil: false
 #Choose if enchantment tables are enabled
 enable-enchanting-table: false
 #Choose if to count bookshelves (may cause server lag)
 #If this option is false, the server will use a random count (0~15)
 count-bookshelf: false

redstone:
 ################################################
 ####Choose if the redstone system is enabled####
 ################################################
 #If it is false, the redstone system won't work#
 ################################################
 enable: true
 #Choose if frequency pulses are enabled
 frequency-pulse: false
 #Set the frequency of pulse. Default = 1s
 pulse-frequency: 1

dserver:
 #The count of all multi-server unified
 enable: false
 #Update Query automatically
 query-auto-update: false
 #Update Query periodically
 query-tick-update: true
 #The max players' on the MOTD
 motd-max-players: 0
 #The max players' on the Query. 0=Default
 query-max-players: 0
 #Show the number of all players on MOTD
 motd-all-players: false
 #Show the number of all players on Query
 query-all-players: false
 #Show the number of online players on MOTD
 motd-players: false
 #Show the number of online players on Query
 query-players: false
 #Update Frequency. 20=1s
 time: 40
 #Auto-retry # of times when server fails
 retry-times: 3
 #the server list，Separate by ';'，e.g. 1.example.com:19132;2.example.com:19133
 server-list: ""

inventory:
 #Set this to true if you have problems with anvils. This will process inventory transactions in a vanilla fashion with no anti-cheats or verification.
 allow-cheats: false

**Comment by mote166** [comment]
the problem isn't solved yet and u just closed the issue . wow :/
