### ISSUE TITLE
/transfer command bug

### ISSUE THREAD

**Issue by Pezovagew** [H4PM/Elywing#462]
When I try to teleport to a server I get the message Usage: ocketmine.command.transfer.usage
Please fix it!!!!

**Comment by Lazerplayz** [comment]
Did you do /transfer [ip] [port]?

**Comment by Pezovagew** [comment]
No. I did /transfer (IP):(port)

**Comment by mote166** [comment]
is this command built in ? or a plugin command?

**Comment by mote166** [comment]
cuz when i type /transfer or /connect it says unknown command
