### ISSUE TITLE
Slapper and LiveTexts don't work (Famous Plugins)

### ISSUE THREAD

**Issue by ChickenTheDuck** [H4PM/Elywing#465]
Hi! It always says an error messege if I use the LiveTexts or Slapper plugin. For example: /slapper spawn human test       it says:  An error occured ....          the console says it was because of the php binaries with: mob.php or something like that inside the .phar file... can you help?!

**Comment by Lazerplayz** [comment]
This isnt a elywing issue its your plugin version contact the plugin devs to fix it ir go to their lattest comits in github...
