### ISSUE TITLE
Server Crash when teleporting to worlds

### ISSUE THREAD

**Issue by WreckagePE** [H4PM/Elywing#466]
I use manyworlds. The server crashes when i /mw tp {worldname}. It doesnt crash, though, it just stops everything and lag spike occurs for literally 1 hour, so i just restart. What do i do?

**Comment by Qimie** [comment]
Give more details. The server has how much RAM,Storage,Crashdumps and stuff

**Comment by Lazerplayz** [comment]
It's probably the version of many worlds update to the latest version

**Comment by Qimie** [comment]
But my server with 500MB RAM and 1 GB storage works just fine with latest
manyworlds. It only freezes 10-30 sec bc loading so many chunk.

**Comment by WreckagePE** [comment]
4GB RAM. 100 players. When I generate worlds, it's only me online as its whitelisted. However, when I teleport to the world, this is when the issue occurs

**Comment by AppleDevelops** [comment]
Check-movement isn't being good rght now 🙃

**Comment by Pezovagew** [comment]
Do /mw tp {your name} {world name}
It's a ManyWorlds plugin bug

**Comment by WreckagePE** [comment]
It isn't.. Never used to happen in the Elywing version before MCPE 1.0.3. It doesn't happen when just teleporting to worlds, it happens when you warp to a chunk that you haven't loaded.

**Comment by AppleDevelops** [comment]
I'll update Elywing later, it'll be ported from my stuff again. I'm just a bit busy

**Comment by Pezovagew** [comment]
OK then

**Comment by WreckagePE** [comment]
Thanks :)!! Needed it lol

**Comment by Mrfanman345** [comment]
Are they MCRegion worlds? If so that might be the problem since I don't think they are supported anymore.

**Comment by WreckagePE** [comment]
I think so... They have region.dat in themselves

**Comment by WreckagePE** [comment]
Is this fixed Apple?
