### ISSUE TITLE
raklib warnings

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [H4PM/Elywing#47]
Warning: assert(): Still 5375 bytes unread! failed in /root/src/pocketmine/network/RakLibInterface.php on line 135
Genisys> about
Genisys> 09:59:47 | Elywing thread:INFO > [CommandTracker] <CONSOLE> /about
09:59:47 | Elywing thread:INFO > -----Server information-----
09:59:47 | Elywing thread:INFO > This server is running Elywing (codename "Aliby")
09:59:47 | Elywing thread:INFO > PHP version: 7.0.10
09:59:47 | Elywing thread:INFO > API: 2.0.0 (iTX API version 1.9.1)
09:59:47 | Elywing thread:INFO > Target client: Minecraft PE v0.16.0.5 alpha (protocol version 91)

**Comment by SuperMaXAleX** [comment]
This is strange.

**Comment by TDMidkwhatisxd** [comment]
There are some other things!
getfloat inventory and getinventory , return null!

I was trying to copy the fix of dropitem event from genisys , and i get null errors in console!
I can give screenshoot if needed!+ client lag
Shokd i make new issue?

**Comment by SuperMaXAleX** [comment]
Ya.

**Comment by TDMidkwhatisxd** [comment]
Ok! I will work myself on this issue with dropitem even, if i fix it , i will do a pull

**Comment by TDMidkwhatisxd** [comment]
Hi! Did u download the latest /pmmp/pocketmine-mp  raklib for this fork?
