### ISSUE TITLE
Player Pre-Login event error/bug

### ISSUE THREAD

**Issue by SaccyYLP** [H4PM/Elywing#470]
I am a developer and am just trying to help, I think that this event may not be triggered for some reason due to this error, I haven't tested but here are the errors:

MCPE version for Elywing: 1.0.3;
MCPE version joined with: 1.0.0;

When reloading the server I receive this error:
19:13:29 | Elywing thread:CRITICAL > Error: "Undefined class constant 'DATA_SHOW_NAMETAG'" (EXCEPTION) in "/EssentialsPE.phar/src/EssentialsPE/BaseFiles/BaseAPI" at line 2154

When the players login I receive this error:
19:11:51 | Elywing thread:CRITICAL > "Could not pass event 'pocketmine\event\player\PlayerPreLoginEvent' to 'EssentialsPE v2.0.0': Undefined class constant 'DATA_SHOW_NAMETAG' on EssentialsPE\EventHandlers\PlayerEvents
19:11:51 | Elywing thread:CRITICAL > Error: "Undefined class constant 'DATA_SHOW_NAMETAG'" (EXCEPTION) in "/EssentialsPE.phar/src/EssentialsPE/BaseFiles/BaseAPI" at line 2154

Please reply when you have fixed the issue and I will close it.

**Comment by AppleDevelops** [comment]
Obviously not a good developer

**Comment by SaccyYLP** [comment]
sorry, i see my mistake, I'll report it to the appropriate place :P I really do feel nooby now that I didn't even bother reading it properly.
