### ISSUE TITLE
dropitem event, cant be complety canceled!

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [H4PM/Elywing#48]
$this->getFloatingInventory()->removeItem($item);
 			$this->getInventory()->addItem($item);

Both of them return  null  error!

**Comment by SuperMaXAleX** [comment]
What did write for the "$item" ?

**Comment by TDMidkwhatisxd** [comment]
https://github.com/iTXTech/Genisys/pull/2021/commits/cd6f27efd3d902a91f107c52ed5f1605353cf6ba

**Comment by TDMidkwhatisxd** [comment]
I should add value for $item?

**Comment by TDMidkwhatisxd** [comment]
Sometimes im so stupid , why i put $p-> instead of $this-> ?  XD
