### ISSUE TITLE
installation du software

### ISSUE THREAD

**Issue by GamingPilot2** [H4PM/Elywing#5]
vas-y explique moi plus clairement pour moi ca veux rien dire remplacer les fichiers, je sais pas où aller

**Comment by Misteboss** [comment]
Arrête d'ouvrir des issues pour rien, .., donc :
- Télécharge Elywing
- Décompresser le dossier .zip
- Prend le dossier src et upload le au même niveau que les dossiers plugins et worlds
- supprime ton Genisys.phar ou ton Pocketmine.phar 
- Reboot le serveur
Et c'est bon, si tu vois des bugs hésite pas à les signaler !
@GamingPilot2
