### ISSUE TITLE
Cheats

### ISSUE THREAD

**Issue by ImagicalGamer** [H4PM/Elywing#55]
Players can use the in-game cheat menu to switch gamemodes etc.

**Comment by SuperMaXAleX** [comment]
@Muqsit we found where the "Gamemode Detection" come from xP

**Comment by TDMidkwhatisxd** [comment]
Just do a plugin detector!
It check every 2 seconds if a player is OP or gamemode !== 0, and kick them , deop + gamemode reset!( if they have no perms)!
I dont know how to integrate a plugin in pocketmine xd!

**Comment by Muqsit** [comment]
@SuperMaXAleX could be this.

**Comment by TheAppleGamer** [comment]
I believe they don't have the new permission system like they have in pmmp

**Comment by ImagicalGamer** [comment]
@TDMidkwhatisxd I'm using an anticheat but not everyone knows PHP. Can't always use the quick "fix", this legitimately needs to be fixed.

**Comment by Muqsit** [comment]
I can't produce this. Make sure you're using the master branch. Genisys was merged into the master branch.

**Comment by TDMidkwhatisxd** [comment]
@Muqsit  it work only if u are OP! I tryed with non OP account and failed! But , i did the plugin just in case!
