### ISSUE TITLE
Blocks dont drop!

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [H4PM/Elywing#56]
If u break a block, it wont drop !

Reproduce: break dirt, done :) !

**Comment by Muqsit** [comment]
Cant reproduce.

**Comment by Muqsit** [comment]
This is linked with #29 
When you join the server, do
/gm s
/gm c
/gm s

Then try breaking the blocks.

**Comment by TDMidkwhatisxd** [comment]
Ohh!! Bocks just wont break xd! I tap again on that place, and it show up again :(

**Comment by TDMidkwhatisxd** [comment]
Fixed! Wen u updated, i only copy player.php on my sv, and only restart!
how i fixed: stop the server, dellete src files, and upload latest src files ! Done :)
