### ISSUE TITLE
Problems with config

### ISSUE THREAD

**Issue by Misteboss** [H4PM/Elywing#59]
Error :
Warning: file_put_contents(home/config/players/m/misteboss1.yml): failed to open stream: No such file or directory in /home/srv3/src/pocketmine/utils/Config.php on line 207
@Muqsit @SuperMaXAleX @Pogogo007

**Comment by ImagicalGamer** [comment]
@Misteboss does PocketMine have access to that folder? To create and/or modify files?

**Comment by Misteboss** [comment]
@ImagicalGamer I don't know how i can know ? And @TDMidkwhatisxd the file exist i check..

**Comment by TDMidkwhatisxd** [comment]
Pocketmine cant have any fault with file_put_contents !
1. The file adress is incorrect!
2. Try on other forks to see if it is reproduced!
3. Check again your code!
4. Most of my custom plugins use file_put_contents, so i can confirm that is your code fault!
5. Check tutorials online!
6. http://stackoverflow.com/ 

Sorry for grammar mistakes, i was gotta sleep and phone was making sounds that i got emails xd!(from github)

**Comment by Misteboss** [comment]
Is that correct ? if(!file_exists("home/srv1/plugins/SimpleAuth/players/ @TDMidkwhatisxd @ImagicalGamer

**Comment by Muqsit** [comment]
if(!file_exists($this->getDataFolder() . "something.yml")) {
      @mkdir($this->getDataFolder());
      file_put_contents($this->getDataFolder() . "something.yml",$this->getResource("something.yml"));
    }

**Comment by TDMidkwhatisxd** [comment]
@Muqsit , do we receive here help with plugins and php codes? I will take up on that offer if so XD!
