### ISSUE TITLE
#Bug EntityDamageEvent ?

### ISSUE THREAD

**Issue by Pab450** [H4PM/Elywing#60]
> // if($event->getEntity()->getLevel()->getName() == language::pocketmine_level_name_plugin){ 
>   //if($this->plugin_damage == 1){
>   if($event->getEntity() instanceof Player){
>   if($event->getCause() === EntityDamageEvent::CAUSE_ENTITY_ATTACK or EntityDamageEvent::CAUSE_PROJECTILE){
>   $event->setCancelled(true);  
>   }
>   }
>   //}
>  // }
> Im not takes damage when I mention EntityDamageEvent :: :: gold CAUSE_ENTITY_ATTACK EntityDamageEvent CAUSE_PROJECTILE 

is a bug ?

**Comment by TheAppleGamer** [comment]
You canceled damage

**Comment by Pab450** [comment]
no just ATTACK and PROJECTILE and im not take damage with fall

**Comment by SuperMaXAleX** [comment]
The code changed ;-;
You need to check yourself on Elywing.
