### ISSUE TITLE
Lots of people crash on join 

### ISSUE THREAD

**Issue by Misteboss** [H4PM/Elywing#65]
This is the error in the console when a player crash
`ultimateflame[/173.49.242.230:19132] [ClientID: 8593298502261835683] logged in with entity id 16 at (ZenBuildHub, 197.5, 16, 129.5)
2016-10-27 [20:12:58] [Server thread/INFO]: ultimateflame[/173.49.242.230:19132] logged out due to timeout`

**Comment by SuperMaXAleX** [comment]
D'après dktapps, il faut absolument supprimer Slapper de son serveur

**Comment by Misteboss** [comment]
@SuperMaXAleX prq?

**Comment by SuperMaXAleX** [comment]
Car il surcharge le client du serveur, il faut donc attends une mise à jour

**Comment by TDMidkwhatisxd** [comment]
Pls english :3

**Comment by ItsXirano** [comment]
@TDMidkwhatisxd Slapper is not supported for this reason : Slapper Overload MCPE Client

**Comment by TDMidkwhatisxd** [comment]
Thx :3
