### ISSUE TITLE
Tip bug.

### ISSUE THREAD

**Issue by LCraftPE** [H4PM/Elywing#66]
Sur mon serveur, les Tip ne s'affichent pas... +1 bug

Apres qu'un joueur meurt sur le serveur, les commandes qu'il execute ne seront pas visible dans le tchat, par exemple si je fais /register apres etre mort, ca va rien mettre dans le tchat alors que normalement ca me dit "Utilise...".

Je pense que c'est 2 bugs sont suffisamment majeur pour etre reporté a muqsit pour qu'il puisse faire quelque chose rapidement, merci.

**Comment by SuperMaXAleX** [comment]
Les commandes ont été fix après la mort d'un joueur

**Comment by Enzoomet** [comment]
Salutations,

Beaucoup de choses se sont passées depuis que vous avez posté le problème pour la première fois, assurez-vous de mettre à jour la version Elywing la plus récente car cela n'a pas eu lieu sur mon serveur.

Bonne chance,

Enzoomètre
