### ISSUE TITLE
Bug with furnace

### ISSUE THREAD

**Issue by vzlomka76** [H4PM/Elywing#74]
All ore and cobbles do not appear in the furnace
![1](https://cloud.githubusercontent.com/assets/16573760/19882315/c1194f12-a01d-11e6-8496-ca3e5682bb49.png)
![2](https://cloud.githubusercontent.com/assets/16573760/19882316/c2b6375e-a01d-11e6-93b0-4f0dbf1cb7f0.png)

**Comment by SuperMaXAleX** [comment]
Really. Strange. 
I know maybe where come from the bug

**Comment by vzlomka76** [comment]
@SuperMaXAleX and things, which are displayed on the left - this is configurable in the core? Or is it the client?

**Comment by vzlomka76** [comment]
@SuperMaXAleX in [https://github.com/pmmp/PocketMine-MP]pmmp this bug in not observed
