### ISSUE TITLE
bug avec le 'playerInteractEvent'

### ISSUE THREAD

**Issue by GamingPilot2** [H4PM/Elywing#76]
Bonjour, Bonsoir,

Un des principaux codeurs de mon serveur, m'à fait un plugin de "SignKit", mais il a dit qu'il ne marcherait pas car le 'PlayerInteractEvent' est bug sur Elywing. Pouvez-vous faire quelque chose ?

Merci,
GamingPilot2

> Owner of @LifeCubePE_ & CM of @LifeCubePE_ !

**Comment by SuperMaXAleX** [comment]
Après plusieurs tests, 0 bug, le code n'a pas du tout bouger d'ailleurs, exactement le même que Genisys / ClearSky / Steadfast2 / PocketMine

**Comment by SuperMaXAleX** [comment]
Il l'a donc mal utilisé

**Comment by GamingPilot2** [comment]
Bonjour, Bonsoir,

Je peux vous assurez qu'il ne la pas mal utilisé, car c'est Pokeyval qui me l'a fais.

> Owner of @LifeCubePE_ & CM of @LifeCubePE_ !

**Comment by SuperMaXAleX** [comment]
Et bien, j'ai un plugin Kits aussi et qui utilise PlayerInteractEvent pour des Signs, 0 problème .-.

**Comment by SuperMaXAleX** [comment]
Je peux copier coller les codes des autres software etc, rien ne bougera .-.

**Comment by GamingPilot2** [comment]
vien mp twitter
