### ISSUE TITLE
Bug au démarrage 

### ISSUE THREAD

**Issue by Thecraftdu34** [H4PM/Elywing#78]
Slt les gens mdr, quand je load le serv j'ai ça : 19:16:23 | Elywing thread:ERROR > pocketmine.level.generateError
19:16:23 | Elywing thread:CRITICAL > ClassNotFoundException: "Class pocketmine\nbt\NBT not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
19:16:23 | Elywing thread:EMERGENCY > No default level has been loaded

**Comment by ItsXirano** [comment]
Tu utilise un plugin ?

**Comment by Thecraftdu34** [comment]
Non aucuns.

**Comment by ItsXirano** [comment]
@TheCraftdu34 Essaye alors de supprimer les worlds (fait un backup) et les config si le prob n'est pas resolu installe la derniere version de Elywing .
