### ISSUE TITLE
Memory leak here!!!!

### ISSUE THREAD

**Issue by Adam1609** [H4PM/Elywing#79]
Elywing Crash Dump Wed Nov 2 04:57:05 CET 2016

Error: Out of memory (allocated 1145044992) (tried to allocate 234881024 bytes)
File: /src/pocketmine/level/Level
Line: 1388
Type: E_ERROR

Code:
[1379] 		}
[1380] 
[1381] 		$block = clone $this->blockStates[$fullState & 0xfff];
[1382] 
[1383] 		$block->x = $pos->x;
[1384] 		$block->y = $pos->y;
[1385] 		$block->z = $pos->z;
[1386] 		$block->level = $this;
[1387] 
[1388] 		return $this->blockCache[$index] = $block;
[1389] 	}
[1390] 
[1391] 	public function updateAllLight(Vector3 $pos){
[1392] 		$this->updateBlockSkyLight($pos->x, $pos->y, $pos->z);
[1393] 		$this->updateBlockLight($pos->x, $pos->y, $pos->z);
[1394] 	}
[1395] 
[1396] 	public function updateBlockSkyLight(int $x, int $y, int $z){
[1397] 		//TODO
[1398] 	}

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Elywing version: 0000000000000000000000000000000000000000 [Protocol 91; API 2.0.0]
uname -a: Windows NT WINDOWS2012-64 6.3 build 9600 (Windows Server 2012 R2 Datacenter Edition) i586
PHP version: 7.0.10
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 3 minutes 27 seconds
Number of loaded worlds: 5
Players online: 1/30

Loaded plugins:
AdvancedKits 5.1 by luca28pet for API(s) 2.0.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
CoreProtect 0.0.2 by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0
DevTools 1.1-iTX by PocketMine Team & iTX Technologies LLC for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EconomySell 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EmptyWorld 1.1.0 by aliuly for API(s) 2.0.0
FuckingSpam 0.1 by BalAnce for API(s) 1.12.0
GMChecker 0.2 by  for API(s) 1.12.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
KillChat 1.0.2.MOD by Array for API(s) 1.9.0, 2.0.0
LaunchPads 1.0.0 by MCPEPIG for API(s) 1.0.0
libcommon 2.0.0dev1 by aliuly for API(s) 2.0.0
ManyWorlds 2.2.0dev1 by aliuly for API(s) 2.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
NoDrops 1 by Yupai for API(s) 2.0.0
PlayerSelector 1 by Ad5001 for API(s) 2.0.0, 1.13.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
PVPlevelRPG 6 by ByZikenPE for API(s) 2.0.0
Sell 2 by Muqsit for API(s) 2.0.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
SkinChanger 1.2.3 by SalmonDE, Aericio, KairusDarkSeeker for API(s) 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
WorldEdit 1.0.2 by  for API(s) 1.13.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
Bedwars 2.3 by Bluplayz for API(s) 1.14.0, 2.0.0
BuildBattle FleetHD by FleetHD for API(s) 1.0.0, 2.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
FactionsPro 1.3.2 by Array for API(s) 1.14.0, 2.0.0
REDFeed 1.0BETA by  for API(s) 1.14.0, 2.0.0
REDLagg 0.1 by Adam1609 credit to Sergey_Dertan for API(s) 1.8.0
MysUFarms 0.0.1 by GlxTeam for API(s) 2.0.0
MysUPets 0.1 by Adam1609 with Infernus101 for API(s) 2.0.0
RED 0.1 by Adam1609 for API(s) 2.0.0
REDNoBreak 0.1 by Adam1609 for API(s) 2.0.0
TradeCraft 0.2 by Jarest (translate and fixable by Adam1609) for API(s) 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 2.0.0

**Comment by ItsXirano** [comment]
Try to delete your world ( Make sure to have a Backup) Restart server .
If it not work Download latest version of Elywing .

**Comment by TDMidkwhatisxd** [comment]
[Some Changes](https://github.com/H4PM/Elywing/pull/81/commits/5d070bcf6f5d4085680cbf5ae556d591fc057083)

**Comment by TDMidkwhatisxd** [comment]
It fix memory leak, and make you use less Ram, but increase bandwidth ussage(becouse of compresion lvl 1!).
