### ISSUE TITLE
Notice: Does 0.16 Single Player command affect to 0.16 Elywing Cilent?

### ISSUE THREAD

**Issue by Adam1609** [H4PM/Elywing#83]
After 0.16, I realize that I am doing something missing, players couldn't use 0.16 command in Cilent, because 0.16 have new command almost Server-like

**Comment by TDMidkwhatisxd** [comment]
Nope! If you have no OP acces, your OP command will output : Unknown .... :   
Even settings, if u set cmode, u only change to cmode if you have op/perms to change gamemode!

**Comment by TDMidkwhatisxd** [comment]
If u mean, about plots plugin, there is a fixed one for 0.16

**Comment by Adam1609** [comment]
Oh, I know abut the plots plugin problem
.
On exception, can I make PRs about language system?

**Comment by TDMidkwhatisxd** [comment]
Dont ask me! Hmmmm.. @Muqsit ? XD

**Comment by SuperMaXAleX** [comment]
I'm using MyPlots, and I have 0 problem.

**Comment by TDMidkwhatisxd** [comment]
Old versions of myplot had a bug on 0.16, they just updated it xd !

**Comment by SuperMaXAleX** [comment]
Maybe maybe

**Comment by TDMidkwhatisxd** [comment]
I was thinking, // Unknown Command // glich, is not server side, but why it fix on relogin?
Maybe server need to send some info on player login?
😵 #MindBlow
