### ISSUE TITLE
using commands to freeze server 0.0

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [H4PM/Elywing#85]
My server freeze sometimes, are u using fixed raklib by dktapps?

**Comment by TDMidkwhatisxd** [comment]
https://timings.aikar.co/?url=23424624

**Comment by TDMidkwhatisxd** [comment]
It seems if u can flood commands, u can shut down a server , omg ;-; , or why that happens 0.0

**Comment by SuperMaXAleX** [comment]
I'll fix

**Comment by TDMidkwhatisxd** [comment]
Did u reproduce it?

**Comment by TDMidkwhatisxd** [comment]
Did u reproduce it?

**Comment by TDMidkwhatisxd** [comment]
Did u reproduce it?

**Comment by TDMidkwhatisxd** [comment]
Did u reproduce it?

**Comment by TDMidkwhatisxd** [comment]
Did u reproduce it?

**Comment by TDMidkwhatisxd** [comment]
Did u reproduce it?

**Comment by TDMidkwhatisxd** [comment]
Did u reproduce it?

**Comment by TDMidkwhatisxd** [comment]
Did u reproduce it?

**Comment by TDMidkwhatisxd** [comment]
Happened again! I banned someone, changed his name and used /register and server freeze for 10 seconds or more! Now i monitor server! I will find out what he did o.o !

**Comment by daniktheboss** [comment]
Not reproducable. I have a server over 20 people using /warp, /sell, /buy, /spawn, /f and server doesn't freeze at all

**Comment by TDMidkwhatisxd** [comment]
I think there is something! My server is on Top 1 so ofcourse i will get targeted first!
I did timings to check if some plugins lag the server! And saw someome acting like he is admin, banned him, he used another name and freezed server with /register ! 
(I was warned by him, that he will do something before i warned him that he will get banned)

**Comment by daniktheboss** [comment]
Haha, ur funny.

**Comment by TDMidkwhatisxd** [comment]
No joke, see timings

**Comment by TDMidkwhatisxd** [comment]
Ok, found out the error! Is a plugin error :/  ! Sorry for that! Now i need to fix ServerAuth myself becouse devs sleep ;-;  !

Is not fork fault see ya ^^
