### ISSUE TITLE
This really shouldn't be here

### ISSUE THREAD

**Issue by archie426** [H4PM/Elywing#86]
Hello there,
I know I am speaking like a member of the PMMP team but this is important.
Please do not create anymore spoons of PMMP. All they have done is caused the community conflict and hatred. The current dev team of PMMP are doing a great job, and they havent done it for you to ruin it. Please rethink this.

**Comment by caspervanneck** [comment]
no

**Comment by dterweij** [comment]
open source = open source. Free for everyone....
No clones? make PMMP closed source....

**Comment by dterweij** [comment]
open source = open source. Free for everyone....
No clones? make PMMP closed source....

**Comment by dterweij** [comment]
open source = open source. Free for everyone....
No clones? make PMMP closed source....

**Comment by dterweij** [comment]
open source = open source. Free for everyone....
No clones? make PMMP closed source....

**Comment by dterweij** [comment]
open source = open source. Free for everyone....
No clones? make PMMP closed source....

**Comment by dterweij** [comment]
open source = open source. Free for everyone....
No clones? make PMMP closed source....

**Comment by dterweij** [comment]
open source = open source. Free for everyone....
No clones? make PMMP closed source....

**Comment by dterweij** [comment]
open source = open source. Free for everyone....
No clones? make PMMP closed source....

**Comment by SuperMaXAleX** [comment]
Thanks for useful issue.

**Comment by SuperMaXAleX** [comment]
Thanks for the useful issue.

**Comment by SuperMaXAleX** [comment]
Thanks for the useful issue.

**Comment by TDMidkwhatisxd** [comment]
Why you ruin PmmP, if u make a fork?! 😶 Really Strange 0-0

**Comment by archie426** [comment]
It is useful. I don't see how this is helping anyone. All you have basically done is copied @dkapps's code.....
Any why are you spamming your own repo?

**Comment by SuperMaXAleX** [comment]
Explain me so why I create this fork ? I encouraged him, I'm encouraging him. I never wanted to ruin his work but some people example you, don't understand this and don't want understand.

**Comment by archie426** [comment]
@SuperMaXAleX I am listening. I ask again, why is this here. It is completely unnecessary. All this is is a spoon. Not a fork. You have just copied the code from PMMP and called it Elywing and described it as stable

**Comment by TDMidkwhatisxd** [comment]
Nope! This is legit! Done! You should ban Him from this fork, this mean you are afraid of something or u wanna act like a *Smart Boy* ! All u did with this issue is only messing arround? Do u think that this will destroy dktapps work? Kid are u crazy?  There is genisys too :/  ! And i think is 1000% better than PmmP!

**Comment by archie426** [comment]
There is just no point in this. Stop saying 'OMHGKGNFHDHH THIS IS LEGIT OMG' as an excuse. Why sowuld I be afraid. If it is better then why do you need to do it in a separate one? Genisys is made by @dktapps. And how am I a smart boy?

**Comment by TDMidkwhatisxd** [comment]
Now you are stupid, please quit internet, becouse you have troubles with your head!
Dktapps just joined genisys team lol, wtf these noobs!

**Comment by archie426** [comment]
@TDMidkwhatisxd ..... He is an owner of iTX.......  and co-founded it.

**Comment by TDMidkwhatisxd** [comment]
Nope, they made it co-owner (if he is:/ ) he joined as for 0.15 or 0.14 if im right :/ ! Go ask him and stfu kid!

**Comment by archie426** [comment]
http://forums.pocketmine.net/threads/the-future-of-pocketmine.18386/page-3#post-171986

**Comment by dktapps** [comment]
I agree with everything @archie426 has said, but please do stop pinging me.

**Comment by TDMidkwhatisxd** [comment]
Dktapps wen u joined genisys team? (Forgot organization name)

**Comment by dktapps** [comment]
(except for the bit about founding iTX / Genisys... no, I joined around the time 0.15 was released.)

**Comment by TDMidkwhatisxd** [comment]
See? I knew it, and they made u co owner becouse u too skilled right?

**Comment by dktapps** [comment]
Because I was the most active developer and yes, skilled.

**Comment by archie426** [comment]
Ooops, sorry dktapps.

**Comment by TDMidkwhatisxd** [comment]
So Mr. Dktapps, are u afraid that this fork will be more popular than Genisys/Pmmp ?
If no, such comments are useless! They made this fork to make any changes they wanna, without spamming you with issues/feature request, in fact playing with codes, and whats wrong with a fork name?

**Comment by archie426** [comment]
@TDMidkwhatisxd So they cloned it?

**Comment by TDMidkwhatisxd** [comment]
I dont have time to argue forever, i just belive in freedom! If there were no forks, i would make one and try my best!  Im lazy and love to use others work ! So.. 😛

**Comment by archie426** [comment]
True. But this isn't a fork. They have cloned it. Making it more of a spoon. And it won't be pulled

**Comment by dktapps** [comment]
@TDMidkwhatisxd you are one smart guy. No, I'm not worried, but I wonder why the founder of this spoon spooned it instead of using the handy "fork" button.

@archie426 This isn't a clone. A clone retains all the original commit history. This does not.

Well, you can spam all the issues you like and people still won't learn to do things the right way, so I'm done wasting my breath. Have fun :)

**Comment by archie426** [comment]
dktapps Oh, oops, well I meant that what you said.

**Comment by TDMidkwhatisxd** [comment]
@dktapps What u do if u see an ant on street? Ignore it ! 
Is this spoon/fork, disturbing your plans? I think no!

**Comment by Sandertv** [comment]
Just for your information, plugin developers like me are having trouble keeping compatibility for all the different forks of PocketMine, which is really annoying. Right now lots of people use Elywing because it mixes the features of Genisys and the updates of PocketMine. However because you did not do the same commits as there has been done at PM compatibility issues form, making plugins not work with forks, which there are getting more and more of nowadays.

**Comment by SuperMaXAleX** [comment]
Stop now, and come DM on Twitter when you can @dktapps

**Comment by archie426** [comment]
@SuperMaXAleX Are you just trying to shove me out of things?

**Comment by daniktheboss** [comment]
My thoughts... Pocketmine was a great software with great future but since @shoghi left, people thought that Pocketmine will start dieing, so instead of helping and making pr, they decided to make spoons. Yes genisys, clearsky, and imagicalmine was all great softwares. But now @dktapps has a great plan! We all (some) are great developers! So instead of making fork,spoons, knifes, let's all work on one project! Pmmp!

**Comment by TDMidkwhatisxd** [comment]
No

**Comment by daniktheboss** [comment]
OK you please be quiet!

**Comment by SuperMaXAleX** [comment]
@archie426 What .-. ?

**Comment by archie426** [comment]
@TDMidkwhatisxd How is 'no' a reason. Just 'no'? Nothing else?

**Comment by TDMidkwhatisxd** [comment]
Yep, "NO" !

**Comment by TDMidkwhatisxd** [comment]
So this fork is popular? Great! We are no ants? Awesome!

**Comment by archie426** [comment]
@TDMidkwhatisxd It is a SPOONNNNNN. Just get that in your head mate. And also, please remove the link to the Pocketmine Forums and the Plugin Repo. This won't be supported.

**Comment by TDMidkwhatisxd** [comment]
I can + this fork is not mine, i just help if i can! 

I just hate stupid kids like you! Its just funny, u all try to make stupid comments... Oups i mean smart !!

**Comment by Sandertv** [comment]
We do not try to make 'smart' comments, we just speak the truth. PocketMine was not made to copy from and thus pretty disrespectful to make a spoon like this to get all the honour for updating to 0.16. You probably don't even understand why we're trying to make this point, but just know that we're not doing this to just annoy you. This spoon is trying to destroy PocketMine JUST when it's at it's weak point and trying to being revived. I'm done with this discussion, this is how it is.

**Comment by archie426** [comment]
@TDMidkwhatisxd How many times?!?!?!?!? IT IS A SPOOONNN. 'No' does not mean anything without a reason

**Comment by dktapps** [comment]
_/me unsubscribes from notifications_

**Comment by SuperMaXAleX** [comment]
Something is going to change on this fork / spoon to no longer have problems and everyone is going to be happy. PS: Not a Elywing's update

**Comment by dktapps** [comment]
Ugh, is GitHub bugged or something? This is like the third time I've had to unsubscribe >_<

**Comment by SuperMaXAleX** [comment]
I have problems with GitHub since tomorrow, and sorry for mentioned you.

**Comment by KingDeadKnight** [comment]
This fork or "spoon" isn't trying to destroy Pocketmine, but some people yes, by coming harassing us or other "spoon". Don't come say something about copying and pasting dktapps work (even it's better to say pocketmine community's work but it's not only dktapps, even he's doing great work). Don't forget what open-source means.  If you're smart enough (if you are someone who's harrasing), don't care about those spoons and let they die slowly like imagicalmine, and other (like you said). It's just my opinion..

**Comment by Sandertv** [comment]
Like I said before. Nothing is forbidden if it is not in the license, yet it's very disrespectful to make a spoon and get away with the honour. Okay I'm done now, would be appreciated if a member could lock this.

**Comment by KingDeadKnight** [comment]
I'm according to you but I don't think that H4PM's members made this for the honor

**Comment by SuperMaXAleX** [comment]
nop

**Comment by archie426** [comment]
Well why did you make it then?

**Comment by SuperMaXAleX** [comment]
You will see. :)

**Comment by archie426** [comment]
@SuperMaXAleX Wouldn't it be easier to answer my question now. Stop (if you are) trying to abandon the point.

**Comment by SuperMaXAleX** [comment]
I'm not going to abandon it. But, hehe

**Comment by archie426** [comment]
@SuperMaXAleX ?

**Comment by dktapps** [comment]
Just lock the damn issue already.

**Comment by daniktheboss** [comment]
😂

**Comment by SuperMaXAleX** [comment]
To respect the work of @dktapps, Elywing is going to be a plugin.
