### ISSUE TITLE
Server crashing with PopulationTask error

### ISSUE THREAD

**Issue by StaticGamerYT** [H4PM/Elywing#87]
Hi,

my server is crashing frequently with the following error since I'm using Elywing:

Notice: Undefined Offset: 2048 in /home/Gold-Reset/src/pocketmine/level/generator/PopulationTask.php on line 266
Warning: include( /home/Gold-Reset/src/pocketmine/level/generator/PopulationTask.php): failed to open stream: Too many open files in /home/Gold-Reset/src/spl/BaseClassLoader.php on line 128
Warning: include(): Failed opening '/home/Gold-Reset/src/pocketmine/level/generator/PopulationTask.php' for inclusion (include_path='.:') in /home/Gold-Reset/src/spl/BaseClassLoader.php at line 128
02:02:24 | Elywing thread:CRITICAL > ClassNotFoundException: "Class pocketmine\level\generator\PopulationTask not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 131

Can anyone help me fixing this? Thanks in advance

**Comment by TDMidkwhatisxd** [comment]
What u did to reproduce this? Im using it just fine !

**Comment by StaticGamerYT** [comment]
Nothing. I just let my server run for 1-2 hours and then it crashes with that error.

**Comment by TDMidkwhatisxd** [comment]
Is not good to run a server for more than 1 hour, install RestartMe! 
My server restart every 1 hour and no problems at all!
