### ISSUE TITLE
cant pickup items

### ISSUE THREAD

**Issue by caspervanneck** [H4PM/Elywing#92]
05.11 11:34:30 [Server] | Elywing thread:DEBUG  Unhandled inbound packet pocketmine\network\protocol\LevelSoundEventPacket from DragonForgedBoy
05.11 11:34:30 [Server] | Elywing thread:DEBUG  Unhandled inbound packet pocketmine\network\protocol\LevelSoundEventPacket from DragonForgedBoy
05.11 11:34:29 [Server] | Elywing thread:DEBUG  Unhandled inbound packet pocketmine\network\protocol\LevelSoundEventPacket from DragonForgedBoy
05.11 11:34:29 [Server] | Elywing thread:DEBUG  Unhandled inbound packet pocketmine\network\protocol\LevelSoundEventPacket from DragonForgedBoy
05.11 11:34:29 [Server] | Elywing thread:DEBUG  Unhandled inbound packet pocketmine\network\protocol\LevelSoundEventPacket from DragonForgedBoy
05.11 11:34:29 [Server] | Elywing thread:DEBUG  Unhandled inbound packet pocketmine\network\protocol\LevelSoundEventPacket from DragonForgedBoy
05.11 11:34:26 [Server] | Elywing thread:INFO  biboe joined the game
05.11 11:34:26 [Server] | Elywing thread:DEBUG  Unhandled inbound packet pocketmine\network\protocol\LevelSoundEventPacket from DragonForgedBoy
05.11 11:34:26 [Server] | Elywing thread:DEBUG  Unhandled inbound packet pocketmine\network\protocol\LevelSoundEventPacket from DragonForgedBoy
05.11 11:34:25 [Server] | Elywing thread:DEBUG  Unhandled inbound packet pocketmine\network\protocol\LevelSoundEventPacket from DragonForgedBoy
05.11 11:34:25 [Server] | Elywing thread:DEBUG  Unhandled inbound packet pocketmine\network\protocol\ResourcePackClientResponsePacket from biboe

**Comment by TDMidkwhatisxd** [comment]
Really? How for me it works?

**Comment by TDMidkwhatisxd** [comment]
Use the phar from pool request!
Sorry for double posting :D

**Comment by caspervanneck** [comment]
@TDMidkwhatisxd  i use your link

**Comment by TDMidkwhatisxd** [comment]
Still have the error?

**Comment by caspervanneck** [comment]
@TDMidkwhatisxd yes

**Comment by caspervanneck** [comment]
i have still the eror

**Comment by TDMidkwhatisxd** [comment]
Give me your ip pls 0.0

**Comment by caspervanneck** [comment]
i run now clearsky @TDMidkwhatisxd

**Comment by TDMidkwhatisxd** [comment]
.........

**Comment by caspervanneck** [comment]
yes i know but i wanth a stable server

**Comment by vzlomka76** [comment]
I have everything working perfectly

**Comment by TDMidkwhatisxd** [comment]
No xd... Its just becouse i cant test and see what server u got. Xd

**Comment by TDMidkwhatisxd** [comment]
@vzlomka76  Elywing is working ok for u? I made phar file :D

**Comment by vzlomka76** [comment]
@TDMidkwhatisxd 
there is a bug with death, I can leave here ip server? something that you would look for the bug. It's hard to explain

**Comment by TDMidkwhatisxd** [comment]
Sure! And what bug is? I wonder!

**Comment by vzlomka76** [comment]
@TDMidkwhatisxd play.shadowpixel.ru:33333, go to the server, I'll come, too, and will show you all

**Comment by vzlomka76** [comment]
@TDMidkwhatisxd i fix it. Thanks :D

**Comment by TheAppleGamer** [comment]
Enable cheats

**Comment by caspervanneck** [comment]
it works finaly

**Comment by TDMidkwhatisxd** [comment]
What it works?

**Comment by caspervanneck** [comment]
Yes it works
