### ISSUE TITLE
dont give up

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [H4PM/Elywing#93]
Will this Stable Fork be on github?
I hear that u wanna to make it a plugin @SuperMaXAleX

**Comment by SuperMaXAleX** [comment]
Sure. A big update is coming.

**Comment by TDMidkwhatisxd** [comment]
I really hope that u wont give up from what others will say!
I hate internet "bullying"

**Comment by caspervanneck** [comment]
yes dont give up im get bullyt  on school and i dont give up

**Comment by caspervanneck** [comment]
@TDMidkwhatisxd  @SuperMaXAleX

**Comment by TDMidkwhatisxd** [comment]
I was bullyed in middle school, then in highschool i say "Enough" , xd !
And wen i saw bullyes in action i love to start making fun of them. Just dont be afraid, use all u need to pay them back, just be smart!

I see that Elywing is stable so far! Players report inventory gliches, but is they own fault for gliching!
(They report gliches with inventory from 0.11 LOL )

**Comment by TDMidkwhatisxd** [comment]
@SuperMaXAleX  what plugin Elywing will be?
