### ISSUE TITLE
Anvils & Enchanting

### ISSUE THREAD

**Issue by SuperDude36** [H4PM/Elywing#99]
When I do something with anvil or enchant table it just pops the item out. I put it in name it to "test" and it pops out. Same when I enchant things.

**Comment by TDMidkwhatisxd** [comment]
Idk! Did u try with cheats on? From genisys.yml?

**Comment by daniktheboss** [comment]
It's a bug since 0.16. Also if you arnt a dev, don't comment trying to be smart and say Idk, like they are asking you.

**Comment by SuperDude36** [comment]
Yay! Thanks @TDMidkwhatisxd! It works!!
